/* Independent TCP relay ports; customer termination and accounting stay at destination. */
(function(){
'use strict';
const oldNav=navItems,oldPage=enginePage,oldAction=runAction;
const L=(en,fa)=>(localStorage.getItem('dark_lang')||'en')==='fa'?fa:en;
const S={data:null,busy:false,diagnostics:{}};
const writable=()=>isOwner()&&state.me?.writes_enabled===true;
const stamp=t=>t?new Date(t*1000).toLocaleString((localStorage.getItem('dark_lang')||'en')==='fa'?'fa-IR':'en-US'):'—';
const phase=r=>({disabled:L('Disabled','خاموش'),enabled:L('Enabled','فعال'),enabling:L('Enable pending','در انتظار فعال‌سازی'),disabling:L('Disable pending','در انتظار خاموش‌شدن'),deleting:L('Delete pending','در انتظار حذف')}[r.phase]||r.phase);
enginePages.swap=['DARK SWAP'];
navItems=function(){const n=oldNav();if(isOwner()&&!n.some(x=>x[0]==='swap')){const i=n.findIndex(x=>x[0]==='nodes');n.splice(i<0?n.length:i+1,0,['swap','DARK SWAP','node']);}return n;};
function nodeName(id){return S.data.nodes.find(n=>n.id===id)?.name||id;}
function action(label,act,r,disabled=false){return `<button class="btn" data-act="${act}" data-swap-id="${r.id}" ${disabled?'disabled':''}>${label}</button>`;}
function routeCard(r){const src=r.sourceState||{},dst=r.exitState||{},pending=src.pending||dst.pending,p=S.diagnostics[r.id],errors=[r.configurationError,src.last_error,dst.last_error].filter(Boolean);return `<article class="swap-card" data-swap-route="${r.id}"><div class="swap-card-head"><h2 dir="ltr">${e(nodeName(r.sourceNodeId))}:${r.sourcePort} → ${e(nodeName(r.exitNodeId))}:${r.exitPort}</h2><span class="tag ${r.phase==='enabled'&&!pending&&!errors.length?'green':'amber'}" data-swap-phase>${e(phase(r))}</span></div><p>${e(r.name)} · ${L('Destination inbound','اینباند مقصد')} #${r.inboundId}</p><p>${L('Automatic subscription endpoint','مسیر خودکار ساب')}: <b dir="ltr">${e(r.entryAddress)}:${r.entryPort}</b> · ${L('destination credentials','احراز هویت مقصد')}</p><p>${L('Configuration ACK (relay / destination)','تأیید تنظیمات (واسط / مقصد)')}: ${src.applied_revision||0}/${src.revision||0} · ${dst.applied_revision||0}/${dst.revision||0} ${pending?L('· pending','· در انتظار'):''}</p><p>${L('Last ACK','آخرین تأیید')}: ${e(stamp(src.applied_at))} · ${e(stamp(dst.applied_at))}</p>${errors.length?`<div class="notice error">${errors.map(e).join('<br>')}</div>`:''}<div class="swap-probe">${p?`${L('Diagnostics at','عیب‌یابی در')} ${e(stamp(p.checkedAt))}<br>${L('Relay listener','شنونده واسط')}: ${p.relayListenerReady?L('Ready','آماده'):L('Unavailable','در دسترس نیست')}<br>${L('Destination internet IP','IP اینترنت مقصد')}: <b dir="ltr">${e(p.destinationInternet?.egress?.ip||'—')}</b><br>`:''}${L('Diagnostics check the relay listener and destination internet separately. Test the generated customer link to verify the complete Iran → relay → destination path.','عیب‌یابی، شنونده واسط و اینترنت مقصد را جدا بررسی می‌کند. برای تأیید کل مسیر ایران ← واسط ← مقصد، لینک ساخته‌شده مشتری را تست کن.')}</div>${writable()?`<div class="swap-actions">${r.phase!=='deleting'?action(L('Enable / retry','فعال‌سازی / تلاش مجدد'),'swapenable',r)+action(L('Disable / retry','خاموش / تلاش مجدد'),'swapdisable',r):''}${action(L('Diagnostics','عیب‌یابی'),'swapdiagnostics',r,r.phase!=='enabled'||pending||!!r.configurationError)}${action(L('Edit','ویرایش'),'swapedit',r,r.phase!=='disabled')}${action(L('Delete / retry','حذف / تلاش مجدد'),'swapdelete',r,!['disabled','deleting'].includes(r.phase))}</div>`:''}</article>`;}
enginePage=async function(){if(state.page!=='swap')return oldPage();if(!isOwner())return heading('DARK SWAP',L('Owner only','فقط مالک'));const owner=state.me.id,data=await api('/api/swap');if(!isOwner()||state.me?.id!==owner)return '';S.data=data;return heading('DARK SWAP',L('Dedicated port → destination inbound','پورت اختصاصی ← اینباند مقصد'),writable()?'<button class="btn primary" data-act="swapnew">'+L('+ New route','+ مسیر جدید')+'</button>':'')+`<div class="notice">${L('Example: Iran entry → Netherlands :6801 → Germany inbound. Existing Netherlands :6800 and Germany Direct stay independent. The new subscription link uses destination credentials and bills usage once at the destination. No manual duplicate Host is needed.','مثال: ورودی ایران ← هلند :6801 ← اینباند آلمان. پورت قبلی هلند :6800 و مستقیم آلمان مستقل می‌مانند. لینک جدید ساب از احراز هویت مقصد استفاده می‌کند و مصرف فقط یک‌بار در مقصد محاسبه می‌شود. هاست تکراری دستی لازم نیست.')}</div><div class="notice warning">${L('Saved routes are disabled. Applying a listener can reconnect sessions. Configure the Iran tunnel externally to forward the entry port to the relay port. A failed destination cannot fall back to relay internet.','مسیر ذخیره‌شده خاموش است. اعمال شنونده ممکن است اتصال‌ها را دوباره برقرار کند. تونل ایران را جدا تنظیم کن تا پورت ورودی را به پورت واسط منتقل کند. خرابی مقصد به خروج اینترنت واسط برنمی‌گردد.')}</div>${data.legacyRoutes.length?`<div class="notice warning">${L('Legacy inbound-wide exit routes exist. Disable/delete the old routes below before using the new port model.','مسیر خروجی قدیمی برای کل اینباند وجود دارد. پیش از استفاده از مدل پورت، مسیر قدیمی را با دکمه‌های زیر خاموش/حذف کن.')}${data.legacyRoutes.map(r=>`<p dir="ltr">${e(r.sourceNodeId)} #${r.sourceInboundId} → ${e(r.exitNodeId)} #${r.exitInboundId} · ${e(r.phase)} ${writable()?`<button class="btn" data-act="swaplegacydisable" data-source="${e(r.sourceNodeId)}" data-inbound="${r.sourceInboundId}">${L('Disable / retry','خاموش / تلاش مجدد')}</button><button class="btn" data-act="swaplegacydelete" data-source="${e(r.sourceNodeId)}" data-inbound="${r.sourceInboundId}" ${['disabled','deleting'].includes(r.phase)?'':'disabled'}>${L('Delete / retry','حذف / تلاش مجدد')}</button>`:''}</p>`).join('')}</div>`:''}<div class="swap-toolbar"><button class="btn" data-act="swaprefresh">${L('Refresh status','تازه‌سازی وضعیت')}</button><span>${data.routes.length} ${L('routes','مسیر')}</span></div><div class="swap-routes">${data.routes.map(routeCard).join('')||'<div class="notice">'+L('No SWAP routes configured.','مسیر SWAP تعریف نشده است.')+'</div>'}</div>`;};
async function routeForm(existing=null,seed={}){
 if(!writable())return;const owner=state.me.id,data=await api('/api/swap');if(!writable()||state.me.id!==owner)return;S.data=data;
 const nodes=data.nodes.filter(n=>n.enabled),inbounds=data.inbounds.filter(i=>i.enable!==false&&['vless','vmess','trojan','shadowsocks'].includes(i.protocol)&&['tcp','raw','grpc','ws','httpupgrade','xhttp'].includes(i.network));
 if(nodes.length<2||!inbounds.length){toast(L('Pair two enabled nodes and assign a TCP inbound to the destination first.','ابتدا دو نود فعال داشته باش و یک اینباند TCP به مقصد تخصیص بده.'),true);return;}
 const opts=nodes.map(n=>`<option value="${e(n.id)}">${e(n.name||n.id)}</option>`).join('');
 dialog('DARK SWAP · '+L(existing?'Edit route':'New route',existing?'ویرایش مسیر':'مسیر جدید'),`<div class="swap-form"><label>${L('Route name','نام مسیر')}<input name="swapName" required maxlength="160" value="${e(existing?.name||'Germany SWAP')}"></label><label>${L('Destination logical inbound','اینباند مشترک مقصد')}<select name="swapInbound">${inbounds.map(i=>`<option value="${i.id}">#${i.id} · ${e(i.remark||i.tag)} · ${e(i.network)}</option>`).join('')}</select></label><label>${L('Relay node (Netherlands)','نود واسط (هلند)')}<select name="swapSource">${opts}</select></label><label>${L('Independent relay port','پورت مستقل واسط')}<input name="swapSourcePort" type="number" min="1" max="65535" required value="${existing?.sourcePort||6801}"></label><label>${L('Destination node (Germany)','نود مقصد (آلمان)')}<select name="swapDestination"></select></label><label>${L('Destination tunnel listener','شنونده تونلی مقصد')}<input name="swapExitPort" type="number" min="1" max="65535" required value="${existing?.exitPort||6802}"></label><label>${L('Iran entry IP / domain','IP / دامنه ورودی ایران')}<input name="swapEntryAddress" required maxlength="253" dir="ltr" value="${e(existing?.entryAddress||'')}"></label><label>${L('Iran entry port','پورت ورودی ایران')}<input name="swapEntryPort" type="number" min="1" max="65535" required value="${existing?.entryPort||6801}"></label></div><div class="notice">${L('Choose a free relay port. An existing destination Tunnel Port is reused; otherwise a separate shadow listener is prepared without changing Direct. Saving leaves SWAP disabled.','پورت آزاد برای واسط انتخاب کن. پورت تانل موجود مقصد استفاده می‌شود؛ در غیر این صورت شنونده جدا آماده می‌شود و Direct تغییر نمی‌کند. SWAP پس از ذخیره خاموش می‌ماند.')}</div>`,async(fd,form)=>{
  if(!form.isConnected||!writable()||state.me.id!==owner)return;
  const body={name:String(fd.get('swapName')),inboundId:Number(fd.get('swapInbound')),sourceNodeId:String(fd.get('swapSource')),sourcePort:Number(fd.get('swapSourcePort')),exitNodeId:String(fd.get('swapDestination')),exitPort:Number(form.elements.swapExitPort.value),entryAddress:String(fd.get('swapEntryAddress')),entryPort:Number(fd.get('swapEntryPort'))};
  await api('/api/swap'+(existing?'/'+existing.id:''),existing?'PUT':'POST',body);
  if(!form.isConnected||!writable()||state.me.id!==owner)return;delete S.diagnostics[existing?.id];closeDialog();toast(L('Saved disabled.','ذخیره شد؛ خاموش است.'));await go('swap');
 });
 const form=document.querySelector('#dialog-form'),src=form.elements.swapSource,ib=form.elements.swapInbound,dst=form.elements.swapDestination,port=form.elements.swapExitPort;
 ib.value=String(existing?.inboundId||seed.inboundId||inbounds[0].id);src.value=existing?.sourceNodeId||seed.sourceNodeId||nodes.find(n=>n.id!==seed.exitNodeId)?.id||nodes[0].id;
 const fillPort=()=>{const p=inbounds.find(i=>i.id===Number(ib.value))?.tunnelPorts?.['node:'+dst.value];port.value=p||existing?.exitPort||6802;port.readOnly=!!p;};
 const fillDest=()=>{const prev=dst.value;dst.innerHTML=nodes.filter(n=>n.id!==src.value&&n.inboundIds.includes(Number(ib.value))&&n.data_address).map(n=>`<option value="${e(n.id)}">${e(n.name||n.id)}</option>`).join('');if([...dst.options].some(o=>o.value===prev))dst.value=prev;fillPort();};
 fillDest();if(existing?.exitNodeId||seed.exitNodeId){dst.value=existing?.exitNodeId||seed.exitNodeId;fillPort();}src.addEventListener('change',fillDest);ib.addEventListener('change',fillDest);dst.addEventListener('change',fillPort);
}
runAction=async function(act,el){
 if(act==='nv2exit'){if(!writable())return;closeDialog();await go('swap');await routeForm(null,{sourceNodeId:el.dataset.id});return;}
 if(act==='swapinboundconfigure'){if(!writable())return;const id=Number(el.dataset.inbound);if(!id){toast(L('Save the inbound and destination assignment first.','ابتدا اینباند و تخصیص مقصد را ذخیره کن.'),true);return;}const data=await api('/api/swap'),r=data.routes.find(x=>x.id===Number(el.dataset.swapId));if(!writable())return;if(r&&r.phase!=='disabled'){toast(L('Disable and synchronize SWAP before editing.','پیش از ویرایش، SWAP را خاموش و همگام کن.'),true);return;}if(!confirm(L('Open SWAP settings? Unsaved inbound edits will be discarded.','تنظیمات SWAP باز شود؟ تغییرات ذخیره‌نشده اینباند کنار گذاشته می‌شود.')))return;closeDialog();await go('swap');await routeForm(r||null,{inboundId:id,exitNodeId:el.dataset.exit});return;}
 if(!act.startsWith('swap'))return oldAction(act,el);if(!isOwner()||S.busy)return;if(act==='swaprefresh')return renderPage();if(!writable())return;if(act==='swapnew')return routeForm();if(act==='swaplegacydisable'||act==='swaplegacydelete'){if(!confirm(L('Disable or delete the legacy inbound-wide route? Existing legacy sessions may reconnect.','مسیر قدیمی کل اینباند خاموش یا حذف شود؟ ممکن است اتصال‌های آن دوباره برقرار شوند.')))return;const path='/api/nodes/'+enc(el.dataset.source)+'/exits/'+Number(el.dataset.inbound);S.busy=true;try{await api(path,act==='swaplegacydelete'?'DELETE':'POST',act==='swaplegacydelete'?undefined:{enabled:false});}finally{S.busy=false;if(isOwner()&&state.page==='swap')await renderPage();}return;}const r=S.data?.routes.find(x=>x.id===Number(el.dataset.swapId));if(!r)return;if(act==='swapedit')return routeForm(r);
 const prompts={swapenable:L('Enable only this dedicated relay port? Applying configuration may reconnect sessions.','فقط این پورت اختصاصی واسط فعال شود؟ اعمال تنظیمات ممکن است اتصال‌ها را دوباره برقرار کند.'),swapdisable:L('Disable this SWAP endpoint?','این مسیر SWAP خاموش شود؟'),swapdelete:L('Delete this disabled route and remove its prepared shadow listener?','مسیر خاموش و شنونده آماده‌شده آن حذف شود؟')};if(prompts[act]&&!confirm(prompts[act]))return;
 const owner=state.me.id;S.busy=true;el.disabled=true;try{if(act==='swapdiagnostics')S.diagnostics[r.id]=await api('/api/swap/'+r.id+'/diagnostics','POST',{});else if(act==='swapdelete'){await api('/api/swap/'+r.id,'DELETE');delete S.diagnostics[r.id];}else if(['swapenable','swapdisable'].includes(act)){await api('/api/swap/'+r.id+'/state','POST',{enabled:act==='swapenable'});delete S.diagnostics[r.id];}}finally{S.busy=false;if(isOwner()&&state.me.id===owner&&state.page==='swap')await renderPage();}
};
document.addEventListener('change',async ev=>{const el=ev.target;if(!el.matches('input[name=swapEnable]'))return;const enabled=el.checked;el.checked=!enabled;if(!writable()||S.busy)return;if(!confirm(L('Apply this DARK SWAP change now? It is independent of Save Inbound; sessions may reconnect.','این تغییر DARK SWAP همین حالا اعمال شود؟ مستقل از ذخیره اینباند است و ممکن است اتصال‌ها دوباره برقرار شوند.')))return;el.checked=enabled;S.busy=true;el.disabled=true;try{const row=await api('/api/swap/'+Number(el.dataset.swapId)+'/state','POST',{enabled});if(el.isConnected){el.checked=row.enabled;const status=el.closest('.iv3-swap-route')?.querySelector('[data-swap-inline-phase]');if(status)status.textContent=phase(row);el.closest('.iv3-swap-route').dataset.swapPhase=row.phase;}}catch(ex){toast(ex.message,true);try{const data=await api('/api/swap'),r=data.routes.find(x=>x.id===Number(el.dataset.swapId));if(r&&el.isConnected){el.checked=r.enabled;el.closest('.iv3-swap-route').dataset.swapPhase=r.phase;el.closest('.iv3-swap-route').querySelector('[data-swap-inline-phase]').textContent=phase(r);}}catch{}}finally{S.busy=false;if(el.isConnected)el.disabled=false;}});
globalThis.DarkPortSwap={routeForm};
})();
