/* DARK XRAY Hosts V2 — client-facing endpoint overrides that actually affect generated links. */
(function(){
'use strict';
if(typeof enginePage!=='function'||typeof runAction!=='function')return;
const baseEnginePage=enginePage,baseRunAction=runAction;
state.hv2={inbound:'all',search:''};
const L=(en,fa)=>((localStorage.getItem('dark_lang')||'en')==='fa'?fa:en);
function htags(h){let t=[];if(h.sni)t.push('SNI '+h.sni);if(h.host)t.push('Host '+h.host);if(h.path)t.push('Path '+h.path);if(h.alpn)t.push('ALPN '+h.alpn);if(h.fingerprint)t.push('FP '+h.fingerprint);return t;}
function inboundName(id){let i=state.inbounds.find(x=>x.id===id);return i?(i.remark||i.tag):'#'+id;}
async function hostsPage(){let hosts=(await api('/api/settings/hosts')).value||[],q=(state.hv2.search||'').toLowerCase();let rows=hosts.map((h,i)=>({...h,_index:i})).filter(h=>(state.hv2.inbound==='all'||String(h.inboundId)===String(state.hv2.inbound))&&(!q||JSON.stringify(h).toLowerCase().includes(q)));return heading(L('Hosts','هاست‌ها'),L('Public/tunnel endpoints used when DARK builds customer links.','آدرس‌های عمومی/تانل که DARK هنگام ساخت لینک مشتری استفاده می‌کند.'),button(L('New host','هاست جدید'),'hv2new','plus','',true))+`<div class="hv2"><article class="panel" style="padding:12px"><div class="hv2-toolbar"><input id="hv2search" class="field-input" type="search" placeholder="${L('Search host / address / SNI','جستجوی هاست / آدرس / SNI')}" value="${e(state.hv2.search)}"><div class="hv2-filter"><button class="${state.hv2.inbound==='all'?'active':''}" data-act="hv2filter" data-id="all">${L('All','همه')}</button>${state.inbounds.map(i=>`<button class="${String(state.hv2.inbound)===String(i.id)?'active':''}" data-act="hv2filter" data-id="${i.id}">${e(i.remark||i.tag)}</button>`).join('')}</div><div class="spacer"></div><span class="tag">${rows.length}</span></div></article><div class="hv2-grid">${rows.length?rows.map(h=>`<article class="panel hv2-card"><div class="hv2-card-head"><div><h3>${e(h.remark||inboundName(h.inboundId))}</h3><small>${e(inboundName(h.inboundId))} · inbound #${h.inboundId}</small></div><span class="tag ${h.enable===false?'red':'green'}">${h.enable===false?L('Disabled','غیرفعال'):L('Enabled','فعال')}</span></div><div class="hv2-endpoint">${e(h.address)}:${h.port}</div><div class="hv2-tags">${htags(h).map(x=>`<span>${e(x)}</span>`).join('')||`<span>${L('No client override','بدون Override')}</span>`}</div><div class="hv2-actions">${button(L('Edit','ویرایش'),'hv2edit','edit',`data-index="${h._index}"`)}${button(L('Clone','کپی'),'hv2clone','copy',`data-index="${h._index}"`)}${button(L('Delete','حذف'),'hv2delete','trash',`data-index="${h._index}"`)}</div></article>`).join(''):empty(L('No hosts match this filter.','هاستی با این فیلتر پیدا نشد.'))}</div><div class="notice">${L('These fields are not decorative: address/port/SNI/Host/Path/ALPN/fingerprint are consumed by DARK link generation.','این فیلدها نمایشی نیستند: address/port/SNI/Host/Path/ALPN/fingerprint مستقیماً در ساخت لینک DARK استفاده می‌شوند.')}</div></div>`;}
enginePage=async function(){if(state.page==='hosts')return hostsPage();return baseEnginePage();};
async function editHost(index=null,clone=false){let list=(await api('/api/settings/hosts')).value||[],h=index==null?{inboundId:state.inbounds[0]?.id||0,address:'',port:443,remark:'',sni:'',host:'',path:'',alpn:'',fingerprint:'chrome',enable:true}:JSON.parse(JSON.stringify(list[index]));if(clone)h.remark=(h.remark||'HOST')+' COPY';dialog(index==null?L('New host','هاست جدید'):L('Edit host','ویرایش هاست'),`<div class="hv2-form">${select(L('Inbound','اینباند'),'inboundId',state.inbounds.map(i=>[i.id,(i.remark||i.tag)+' :'+i.port]),h.inboundId)}${select(L('Status','وضعیت'),'enable',[['true',L('Enabled','فعال')],['false',L('Disabled','غیرفعال')]],String(h.enable!==false))}${field(L('Public / tunnel address','آدرس عمومی / تانل'),'address',h.address||'','text','required dir="ltr"')}${field(L('Public / tunnel port','پورت عمومی / تانل'),'port',h.port||443,'number','required min="1" max="65535"')}${field(L('Remark','نام نمایشی'),'remark',h.remark||'')}${field('SNI','sni',h.sni||'','text','dir="ltr"')}${field('Host','host',h.host||'','text','dir="ltr"')}${field('Path','path',h.path||'','text','dir="ltr"')}${field('ALPN','alpn',h.alpn||'','text','dir="ltr"')}${field(L('Fingerprint','فینگرپرینت'),'fingerprint',h.fingerprint||'chrome','text','dir="ltr"')}<div class="span-2 notice">${L('Leave optional override fields empty to inherit the inbound values.','برای استفاده از مقدار خود Inbound فیلدهای اختیاری را خالی بگذار.')}</div></div>`,async f=>{let v={inboundId:Number(f.get('inboundId')),address:String(f.get('address')||'').trim(),port:Number(f.get('port')),remark:String(f.get('remark')||'').trim(),sni:String(f.get('sni')||'').trim(),host:String(f.get('host')||'').trim(),path:String(f.get('path')||'').trim(),alpn:String(f.get('alpn')||'').trim(),fingerprint:String(f.get('fingerprint')||'').trim(),enable:f.get('enable')==='true'};if(index==null||clone)list.push(v);else list[index]=v;await api('/api/settings/hosts','PUT',{value:list});closeDialog();toast(L('Host saved.','هاست ذخیره شد.'));await refresh();});}
runAction=async function(act,el){if(act==='hv2new'){await editHost();return;}if(act==='hv2edit'){await editHost(Number(el.dataset.index));return;}if(act==='hv2clone'){await editHost(Number(el.dataset.index),true);return;}if(act==='hv2delete'){let list=(await api('/api/settings/hosts')).value||[];if(confirm(L('Delete this host?','این هاست حذف شود؟'))){list.splice(Number(el.dataset.index),1);await api('/api/settings/hosts','PUT',{value:list});await refresh();}return;}if(act==='hv2filter'){state.hv2.inbound=el.dataset.id;await renderPage();return;}return baseRunAction(act,el);};
let ht;document.addEventListener('input',ev=>{if(ev.target.id==='hv2search'){state.hv2.search=ev.target.value;clearTimeout(ht);ht=setTimeout(async()=>{await renderPage();$('#hv2search')?.focus();},180);}});
})();
