/* DARK XRAY Inbounds V2 — cyber UI, native controls, no remote-panel dependency. */
(function(){
'use strict';
if(!globalThis.DarkInbound)return;
const M=globalThis.DarkInbound;
const baseRunAction=runAction, baseLoad=load, baseCloseDialog=closeDialog;
const details={};
const ui={query:'',protocol:'all',transport:'all',security:'all',status:'all',sort:'newest',expanded:new Set(),selected:new Set(),priming:false,lastPrime:0,createMenu:false,bulkMenu:false};
const L=(en,fa)=>((localStorage.getItem('dark_lang')||'en')==='fa'?fa:en);
const txt={
 create:()=>L('Create Inbound','اینباند جدید'), validate:()=>L('Validate Core','اعتبارسنجی هسته'), export:()=>L('Export','خروجی'), bulk:()=>L('Bulk Actions','عملیات گروهی'),
 search:()=>L('Search inbounds, tags, ports…','جست‌وجوی اینباند، تگ یا پورت…'), allProtocols:()=>L('All Protocols','همه پروتکل‌ها'), allTransport:()=>L('All Transports','همه انتقال‌ها'), allSecurity:()=>L('All Security','همه امنیت‌ها'),
 all:()=>L('All','همه'), online:()=>L('Online','آنلاین'), offline:()=>L('Disabled','غیرفعال'), newest:()=>L('Newest','جدیدترین'), name:()=>L('Name','نام'), port:()=>L('Port','پورت'), clients:()=>L('Clients','کاربران'),
};
const protocolOptions=['all','vless','vmess','trojan','shadowsocks','socks','http','dokodemo-door','tunnel'];
const transportOptions=['all','tcp','ws','grpc','httpupgrade','xhttp','kcp'];
const securityOptions=['all','none','tls','reality'];
const iconSafe=n=>icon(n||'settings');
const attr=v=>e(String(v??''));
function currentLang(){return localStorage.getItem('dark_lang')||'en';}
function optionLabel(v){if(v==='all')return L('All','همه');if(v==='httpupgrade')return 'HTTP Upgrade';if(v==='xhttp')return 'XHTTP';if(v==='kcp')return 'mKCP';return String(v).toUpperCase();}
function runtimeOnline(){return !!state.sync?.runtime?.running;}
function related(id){return state.clients.filter(c=>(c.inboundIds||[]).includes(id));}
function clientUsage(c){const total=Number(c.client?.totalGB||0),used=Number(c.used_bytes||0);return {used,total,pct:total?Math.min(100,100*used/total):0};}
function humanExpiry(c){const x=Number(c.client?.expiryTime||0);if(x>0)return new Date(x).toLocaleDateString(currentLang()==='fa'?'fa-IR':'en-GB');if(x<0)return L('First connection','اولین اتصال');return L('Unlimited','بدون انقضا');}
function clientStatus(c){if((c.block_reasons||[]).length)return ['danger',L('Blocked','محدود')];if(c.client?.enable===false)return ['muted',L('Disabled','قطع')];if(c.data_plane_state==='running')return ['ok',L('Online','آنلاین')];return ['warn',L('Pending','در انتظار')];}
async function primeDetails(force=false){
 if(!isOwner()||ui.priming)return;
 const now=Date.now();if(!force&&now-ui.lastPrime<12000&&state.inbounds.every(x=>details[x.id]))return;
 ui.priming=true;
 try{await Promise.all(state.inbounds.map(async r=>{try{details[r.id]=await api('/api/inbounds/'+r.id);}catch{}}));ui.lastPrime=Date.now();}
 finally{ui.priming=false;}
}
load=async function(){await baseLoad();if(state.page==='inbounds')await primeDetails();};
closeDialog=function(){document.querySelector('#overlay')?.classList.remove('inbounds-v2-overlay');baseCloseDialog();};
function schedulePrime(){if(!isOwner()||ui.priming||Date.now()-ui.lastPrime<12000)return;setTimeout(async()=>{await primeDetails();if(state.page==='inbounds')renderPage();},0);}
function comboFilter(kind,label,value,options,ic='settings'){
 const open=ui._openFilter===kind;
 return `<div class="iv2-filter-combo ${open?'open':''}"><button class="iv2-filter-btn" type="button" data-v2-action="filter-menu" data-kind="${attr(kind)}">${iconSafe(ic)}<span>${e(value==='all'?label:optionLabel(value))}</span>${iconSafe('chevron')}</button>${open?`<div class="iv2-popover iv2-filter-pop"><div class="iv2-pop-search">${iconSafe('search')}<input data-v2-filter-search type="search" placeholder="${attr(L('Search…','جست‌وجو…'))}"></div><div class="iv2-pop-list">${options.map(v=>`<button type="button" data-v2-action="filter-set" data-kind="${attr(kind)}" data-value="${attr(v)}" class="${v===value?'active':''}"><span class="iv2-radio"></span><span>${e(v==='all'?label:optionLabel(v))}</span></button>`).join('')}</div></div>`:''}</div>`;
}
function statCard(ic,value,label,klass=''){return `<article class="iv2-stat ${klass}">${iconSafe(ic)}<div><strong>${e(value)}</strong><span>${e(label)}</span></div></article>`;}
function page(){
 schedulePrime();
 const st=M.stats(state.inbounds,state.clients),rows=M.filterRows(state.inbounds,details,state.clients,ui);
 if(!ui.expanded.size&&rows[0])ui.expanded.add(rows[0].id);
 const totalTraffic=bytes(st.usage),online=state.inbounds.filter(r=>r.enable!==false).length;
 return `<div class="inbounds-v2">
  <section class="iv2-hero"><div><div class="iv2-eyebrow">DARK XRAY / INBOUND CONTROL</div><h1>${L('Inbounds','اینباندها')}</h1><p>${L('Build, filter and operate Xray listeners with explicit client ownership.','شنونده‌های Xray را با مالکیت شفاف کاربران بساز و مدیریت کن.')}</p></div><div class="iv2-system ${runtimeOnline()?'ok':'warn'}"><span></span>${runtimeOnline()?L('Core operational','هسته فعال'):L('Core stopped','هسته متوقف')}</div></section>
  <div class="iv2-stats">${statCard('server',st.total,L('Total Inbounds','کل اینباندها'))}${statCard('users',st.clients,L('Managed Clients','کاربران مدیریت‌شده'))}${statCard('activity',totalTraffic,L('Observed Usage','مصرف ثبت‌شده'))}${statCard('check',`${online}/${st.total}`,L('Enabled','فعال'))}${statCard('alert',st.blocked,L('Client Alerts','هشدار کاربران'),st.blocked?'danger':'')}</div>
  <section class="iv2-toolbar panel"><div class="iv2-primary-actions"><div class="iv2-action-wrap"><button class="btn btn-primary iv2-create" data-v2-action="create-menu">${iconSafe('plus')}${txt.create()}${iconSafe('chevron')}</button>${ui.createMenu?templateMenu():''}</div><div class="iv2-action-wrap"><button class="btn" data-v2-action="bulk-menu">${iconSafe('users')}${txt.bulk()}${iconSafe('chevron')}</button>${ui.bulkMenu?bulkMenu():''}</div><button class="btn" data-v2-action="core-validate">${iconSafe('check')}${txt.validate()}</button><button class="btn" data-v2-action="export">${iconSafe('download')}${txt.export()}</button></div>
   <div class="iv2-search">${iconSafe('search')}<input id="iv2-search" type="search" value="${attr(ui.query)}" placeholder="${attr(txt.search())}"><kbd>Ctrl K</kbd></div>
   <div class="iv2-filters">${comboFilter('protocol',txt.allProtocols(),ui.protocol,protocolOptions,'server')}${comboFilter('transport',txt.allTransport(),ui.transport,transportOptions,'activity')}${comboFilter('security',txt.allSecurity(),ui.security,securityOptions,'lock')}
    <div class="iv2-segment" role="group">${['all','online','offline'].map(v=>`<button type="button" data-v2-action="status" data-value="${v}" class="${ui.status===v?'active':''}">${e(v==='all'?txt.all():v==='online'?txt.online():txt.offline())}</button>`).join('')}</div>
    ${comboFilter('sort',txt.newest(),ui.sort,['newest','name','port','clients'],'refresh')}
   </div></section>
  <div class="iv2-list">${rows.length?rows.map(card).join(''):`<div class="iv2-empty panel">${iconSafe('server')}<h3>${L('No inbounds match these filters','هیچ اینباندی با این فیلترها نیست')}</h3><p>${L('Clear filters or create a new inbound template.','فیلترها را پاک کن یا یک اینباند جدید بساز.')}</p></div>`}</div>
  <div class="iv2-footer"><span>${L('Showing','نمایش')} ${rows.length} / ${state.inbounds.length}</span><span>DARK XRAY · NATIVE XRAY CONTROL</span></div>
 </div>`;
}
function templateMenu(){const items=[['vless-reality','VLESS · TCP · REALITY','shield'],['vless-ws-tls','VLESS · WS · TLS','globe'],['trojan-reality-grpc','TROJAN · gRPC · REALITY','lock'],['shadowsocks-tcp','SHADOWSOCKS · TCP','activity'],['custom',L('Custom inbound','اینباند سفارشی'),'settings']];return `<div class="iv2-popover iv2-action-menu">${items.map(([k,l,ic])=>`<button type="button" data-v2-action="new-template" data-template="${k}">${iconSafe(ic)}<span>${e(l)}</span></button>`).join('')}</div>`;}
function bulkMenu(){return `<div class="iv2-popover iv2-action-menu"><button type="button" data-v2-action="bulk-state" data-enable="true">${iconSafe('check')}<span>${L('Enable selected','فعال‌سازی انتخاب‌شده‌ها')}</span></button><button type="button" data-v2-action="bulk-state" data-enable="false">${iconSafe('power')}<span>${L('Disable selected','غیرفعال‌سازی انتخاب‌شده‌ها')}</span></button><button type="button" data-v2-action="clear-selection">${iconSafe('close')}<span>${L('Clear selection','پاک‌کردن انتخاب')}</span></button></div>`;}
function card(row){
 const d=details[row.id]||{},m=M.meta(row,d),clients=related(row.id),expanded=ui.expanded.has(row.id),usage=clients.reduce((n,c)=>n+Number(c.used_bytes||0),0),blocked=clients.filter(c=>(c.block_reasons||[]).length).length;
 const up=Number(row.up||0),down=Number(row.down||0),traffic=up+down||usage;
 return `<article class="iv2-card panel ${expanded?'expanded':''} ${row.enable===false?'disabled':''}">
  <div class="iv2-card-main"><label class="iv2-check"><input type="checkbox" data-v2-select="${row.id}" ${ui.selected.has(row.id)?'checked':''}><span></span></label><div class="iv2-core-glyph">${iconSafe('server')}</div>
   <div class="iv2-identity"><div class="iv2-name-row"><strong>${e(row.remark||row.tag)}</strong><span class="iv2-pill ${row.enable===false?'muted':'ok'}"><i></i>${row.enable===false?L('Disabled','غیرفعال'):L('Enabled','فعال')}</span>${blocked?`<span class="iv2-pill danger">${blocked} ${L('alerts','هشدار')}</span>`:''}</div><div class="iv2-tags"><span>${e(m.protocol.toUpperCase())}</span><span>${e(optionLabel(m.network))}</span><span class="secure">${e(optionLabel(m.security))}</span><bdi>${e(row.tag||'auto-tag')}</bdi></div></div>
   <div class="iv2-card-stat"><span>${L('Listen','شنود')}</span><strong class="mono">${e(row.listen||'0.0.0.0')}:${e(row.port)}</strong><small>#${row.id}</small></div>
   <div class="iv2-card-stat"><span>${L('Traffic','ترافیک')}</span><strong>${bytes(traffic)}</strong><small>${L('observed','ثبت‌شده')}</small></div>
   <div class="iv2-card-stat"><span>${L('Clients','کاربران')}</span><strong>${clients.length}</strong><small>${blocked?blocked+' '+L('limited','محدود'):L('managed','مدیریت‌شده')}</small></div>
   <div class="iv2-signal ${runtimeOnline()&&row.enable!==false?'online':''}" title="${attr(L('Decorative core heartbeat; not a fabricated traffic history.','نشانگر تزئینی سلامت هسته؛ نمودار ترافیک ساختگی نیست.'))}"><i></i><i></i><i></i><i></i><i></i></div>
   <div class="iv2-card-actions">${isOwner()?`<button class="iv2-icon" data-v2-action="edit" data-id="${row.id}" title="${attr(L('Edit','ویرایش'))}">${iconSafe('edit')}</button><button class="iv2-icon" data-v2-action="clone" data-id="${row.id}" title="${attr(L('Clone','کپی'))}">${iconSafe('copy')}</button>`:''}${can('clients.create')?`<button class="iv2-icon accent" data-v2-action="add-client" data-id="${row.id}" title="${attr(L('Add client','افزودن کاربر'))}">${iconSafe('plus')}</button>`:''}<button class="iv2-icon" data-v2-action="expand" data-id="${row.id}" title="${attr(L('Expand','باز/بسته'))}">${iconSafe('chevron')}</button></div>
  </div>${expanded?expandedBody(row,clients):''}
 </article>`;
}
function expandedBody(row,clients){return `<div class="iv2-expanded"><div class="iv2-subbar"><div class="iv2-subtabs"><button class="active">${iconSafe('users')}${L('Clients','کاربران')} <span>${clients.length}</span></button><button type="button" data-v2-action="edit" data-id="${row.id}">${iconSafe('settings')}${L('Settings','تنظیمات')}</button></div><div class="iv2-sub-actions">${can('clients.create')?`<button class="btn btn-primary" data-v2-action="add-client" data-id="${row.id}">${iconSafe('plus')}${L('Add Client','افزودن کاربر')}</button>`:''}${isOwner()?`<button class="btn" data-v2-action="toggle-inbound" data-id="${row.id}" data-enable="${row.enable===false?'true':'false'}">${iconSafe('power')}${row.enable===false?L('Enable','فعال کن'):L('Disable','غیرفعال کن')}</button><button class="btn danger" data-v2-action="delete-inbound" data-id="${row.id}">${iconSafe('trash')}${L('Delete','حذف')}</button>`:''}</div></div>${clientTableV2(clients)}</div>`;}
function clientTableV2(rows){if(!rows.length)return `<div class="iv2-no-clients">${iconSafe('users')}<p>${L('No managed clients on this inbound yet.','هنوز کاربر مدیریت‌شده‌ای روی این اینباند نیست.')}</p></div>`;return `<div class="iv2-client-search">${iconSafe('search')}<input data-v2-client-search type="search" placeholder="${attr(L('Search clients…','جست‌وجوی کاربران…'))}"></div><div class="iv2-table-wrap"><table class="iv2-table"><thead><tr><th>${L('Client','کاربر')}</th><th>${L('Usage','مصرف')}</th><th>${L('Status','وضعیت')}</th><th>${L('IP Policy','سیاست IP')}</th><th>${L('Expiry','انقضا')}</th><th>${L('Actions','عملیات')}</th></tr></thead><tbody>${rows.map(c=>{const u=clientUsage(c),[klass,status]=clientStatus(c),ip=c.client?.limitIp||0,hw=c.client?.limitHwid||0;return `<tr data-v2-client-row="${attr(c.email)}"><td><b class="mono">${e(c.email)}</b><small>${e(c.owner||'')}</small></td><td><div class="iv2-usage"><span>${bytes(u.used)} / ${u.total?bytes(u.total):'∞'}</span><i><b style="width:${u.total?u.pct:0}%"></b></i></div></td><td><span class="iv2-pill ${klass}"><i></i>${e(status)}</span></td><td><span class="iv2-policy">IP ${ip||'∞'} · HWID ${hw||'∞'}</span></td><td>${e(humanExpiry(c))}</td><td><div class="iv2-row-actions">${can('clients.credentials',c.owner)?`<button data-v2-action="client-links" data-email="${attr(c.email)}" title="Links / QR">${iconSafe('link')}</button>`:''}${can('clients.edit',c.owner)?`<button data-v2-action="client-edit" data-email="${attr(c.email)}" title="Edit">${iconSafe('edit')}</button>`:''}${can('clients.ip',c.owner)?`<button data-v2-action="client-ips" data-email="${attr(c.email)}" title="IP / HWID">${iconSafe('shield')}</button>`:''}${can('clients.edit',c.owner)?`<button data-v2-action="client-toggle" data-email="${attr(c.email)}" data-enable="${c.client?.enable===false?'true':'false'}" title="Toggle">${iconSafe('power')}</button>`:''}</div></td></tr>`;}).join('')}</tbody></table></div>`;}
function control(label,name,options,value,help='',search=true){return `<label class="iv2-control"><span>${e(label)}</span><div class="iv2-combo" data-v2-combo><input type="hidden" name="${attr(name)}" value="${attr(value)}"><button type="button" class="iv2-combo-button" data-v2-action="combo-toggle"><b data-v2-combo-label>${e(optionLabel(value))}</b>${iconSafe('chevron')}</button><div class="iv2-combo-menu" hidden>${search?`<div class="iv2-pop-search">${iconSafe('search')}<input data-v2-combo-search type="search" placeholder="${attr(L('Search options…','جست‌وجوی گزینه…'))}"></div>`:''}<div class="iv2-combo-options">${options.map(o=>{const v=Array.isArray(o)?o[0]:o,l=Array.isArray(o)?o[1]:optionLabel(o);return `<button type="button" data-v2-action="combo-set" data-value="${attr(v)}" class="${String(v)===String(value)?'active':''}"><span class="iv2-radio"></span><span>${e(l)}</span></button>`;}).join('')}</div></div></div>${help?`<small>${e(help)}</small>`:''}</label>`;}
function fieldV2(label,name,value='',type='text',help='',attrs=''){return `<label class="iv2-control"><span>${e(label)}</span><input class="iv2-input" name="${attr(name)}" type="${type}" value="${attr(value)}" ${attrs}>${help?`<small>${e(help)}</small>`:''}</label>`;}
function areaV2(label,name,value,help=''){return `<label class="iv2-control iv2-span-2"><span>${e(label)}</span><textarea class="iv2-input iv2-code" name="${attr(name)}" spellcheck="false">${e(typeof value==='string'?value:JSON.stringify(value,null,2))}</textarea>${help?`<small>${e(help)}</small>`:''}</label>`;}
function switchV2(label,name,on,help=''){return `<label class="iv2-switch-row"><div><b>${e(label)}</b>${help?`<small>${e(help)}</small>`:''}</div><input type="hidden" name="${attr(name)}" value="${on?'true':'false'}"><button type="button" class="iv2-switch ${on?'on':''}" data-v2-action="switch"><i></i></button></label>`;}
function editorHTML(d,id){
 const st=d.streamSettings||{},sec=st.realitySettings||st.tlsSettings||{},sn=d.sniffing||{},settings=d.settings||{},net=st.network||'tcp',security=st.security||'none';
 const fallbacks=Array.isArray(settings.fallbacks)?settings.fallbacks:[];
 return `<div class="iv2-drawer-shell"><aside class="iv2-drawer"><form id="iv2-editor"><header class="iv2-drawer-head"><div class="iv2-drawer-title"><span class="iv2-lock">${iconSafe('lock')}</span><div><span>${id?L('Edit Inbound','ویرایش اینباند'):L('Create Inbound','ساخت اینباند')}</span><strong>${e(d.remark||'DARK INBOUND')}</strong></div></div><button type="button" class="iv2-icon" data-v2-action="drawer-close">${iconSafe('close')}</button></header>
 <nav class="iv2-tabs">${[['general',L('General','عمومی')],['transport',L('Transport','انتقال')],['security','TLS / REALITY'],['sniffing',L('Sniffing','اسنیفینگ')],['routing',L('Routing','روتینگ')],['advanced',L('Advanced','پیشرفته')]].map(([k,l],i)=>`<button type="button" data-v2-action="tab" data-tab="${k}" class="${i===0?'active':''}">${e(l)}</button>`).join('')}</nav>
 <div class="iv2-drawer-body">
  <section class="iv2-tabpane active" data-v2-pane="general"><div class="iv2-section-title"><i></i><div><b>${L('Basic Information','اطلاعات پایه')}</b><span>${L('Identity, listener and protocol.','هویت، شنونده و پروتکل.')}</span></div></div><div class="iv2-form-grid">${fieldV2(L('Name','نام'),'remark',d.remark||'DARK INBOUND','text','', 'required maxlength="200"')}${fieldV2('Tag','tag',d.tag||'','text',L('Leave blank for automatic tag on new inbounds.','برای تگ خودکار در اینباند جدید خالی بگذار.'),'dir="ltr"')}${control(L('Protocol','پروتکل'),'protocol',['vless','vmess','trojan','shadowsocks','socks','http','dokodemo-door','tunnel'],d.protocol||'vless')}${fieldV2(L('Port','پورت'),'port',d.port||443,'number','', 'required min="1" max="65535"')}${fieldV2(L('Listen Address','آدرس Listen'),'listen',d.listen||'0.0.0.0','text','', 'required dir="ltr"')}${control(L('Shadowsocks Cipher','رمزنگاری Shadowsocks'),'ssmethod',['aes-128-gcm','aes-256-gcm','chacha20-poly1305'],settings.method||'aes-128-gcm','',false)}<div class="iv2-span-2 iv2-switch-grid">${switchV2(L('Enabled','فعال'),'enable',d.enable!==false,L('Enable this listener in generated Xray config.','این شنونده در کانفیگ Xray فعال باشد.'))}</div></div></section>
  <section class="iv2-tabpane" data-v2-pane="transport"><div class="iv2-section-title"><i></i><div><b>${L('Transport Layer','لایه انتقال')}</b><span>${L('Custom cyber controls replace native dropdowns.','کنترل‌های سفارشی جایگزین کشویی‌های ساده شده‌اند.')}</span></div></div><div class="iv2-form-grid">${control(L('Network','شبکه'),'network',['tcp','ws','grpc','httpupgrade','xhttp','kcp'],net)}${fieldV2('Path','path',st[net+'Settings']?.path||st.wsSettings?.path||'/','text','', 'dir="ltr" data-v2-net-field="path"')}${fieldV2('Host','host',st.wsSettings?.headers?.Host||st[net+'Settings']?.host||'','text','', 'dir="ltr" data-v2-net-field="host"')}${fieldV2('gRPC serviceName','serviceName',st.grpcSettings?.serviceName||'','text','', 'dir="ltr" data-v2-net-field="grpc"')}${fieldV2('gRPC authority','authority',st.grpcSettings?.authority||'','text','', 'dir="ltr" data-v2-net-field="grpc"')}${fieldV2('XHTTP mode','xhttpMode',st.xhttpSettings?.mode||'auto','text','', 'dir="ltr" data-v2-net-field="xhttp"')}${fieldV2('mKCP MTU','mtu',st.kcpSettings?.mtu||1350,'number','', 'min="576" max="1460" data-v2-net-field="kcp"')}${fieldV2('mKCP TTI','tti',st.kcpSettings?.tti||50,'number','', 'min="10" max="5000" data-v2-net-field="kcp"')}</div></section>
  <section class="iv2-tabpane" data-v2-pane="security"><div class="iv2-section-title"><i></i><div><b>${L('Transport Security','امنیت انتقال')}</b><span>${L('TLS and REALITY are validated by the backend and Xray core.','TLS و REALITY توسط بک‌اند و هسته Xray اعتبارسنجی می‌شوند.')}</span></div></div><div class="iv2-form-grid">${control(L('Security','امنیت'),'security',['none','tls','reality'],security)}${control(L('Client Fingerprint Hint','Fingerprint کلاینت'),'fingerprint',['chrome','firefox','safari','edge','randomized'],'chrome',L('Subscription fingerprint is ultimately controlled by Host profiles.','Fingerprint اشتراک نهایتاً از بخش Hosts کنترل می‌شود.'),false)}<div class="iv2-security-block iv2-span-2" data-v2-security="reality"><div class="iv2-form-grid">${fieldV2('Target / Destination','realityTarget',sec.target||sec.dest||'','text',L('Example: www.cloudflare.com:443','مثال: www.cloudflare.com:443'),'dir="ltr"')}${fieldV2('Server Names / SNI','realitySni',(sec.serverNames||[]).join(','),'text',L('Comma separated','با کاما جدا کن'),'dir="ltr"')}${fieldV2('Private Key','privateKey',sec.privateKey||'','password','', 'autocomplete="off" dir="ltr"')}${fieldV2('Short IDs','shortIds',(sec.shortIds||[]).join(','),'text',L('Hex, comma separated','هگز، با کاما جدا کن'),'dir="ltr"')}${fieldV2('SpiderX','spiderX',sec.spiderX||'/','text','', 'dir="ltr"')}<div class="iv2-control"><span>X25519</span><button class="btn iv2-generate" type="button" data-v2-action="gen-x25519">${iconSafe('lock')}${L('Generate Secure Keys','ساخت کلید امن')}</button><small data-v2-public-key>${L('Public key will appear here after generation.','کلید عمومی بعد از ساخت اینجا نمایش داده می‌شود.')}</small></div></div></div><div class="iv2-security-block iv2-span-2" data-v2-security="tls"><div class="iv2-form-grid">${fieldV2('TLS Server Name','tlsServerName',sec.serverName||'','text','', 'dir="ltr"')}${fieldV2('Certificate File','cert',sec.certificates?.[0]?.certificateFile||'','text','', 'dir="ltr"')}${fieldV2('Private Key File','key',sec.certificates?.[0]?.keyFile||'','text','', 'dir="ltr"')}</div></div><div class="iv2-span-2 iv2-fallbacks"><div class="iv2-fallback-head"><div><b>${L('Fallbacks','Fallbacks')}</b><span>${L('Optional VLESS/Trojan fallback destinations.','مقصدهای اختیاری fallback برای VLESS/Trojan.')}</span></div><button type="button" class="btn" data-v2-action="fallback-add">${iconSafe('plus')}${L('Add Fallback','افزودن Fallback')}</button></div><div data-v2-fallback-list>${fallbacks.map(fallbackRow).join('')}</div></div></div></section>
  <section class="iv2-tabpane" data-v2-pane="sniffing"><div class="iv2-section-title"><i></i><div><b>${L('Sniffing & Flow Detection','Sniffing و تشخیص جریان')}</b><span>${L('Keep defaults unless routing requires protocol/domain discovery.','مگر برای روتینگ نیاز داری، پیش‌فرض‌ها مناسب‌اند.')}</span></div></div><div class="iv2-switch-grid">${switchV2(L('Enable sniffing','فعال‌سازی sniffing'),'sniffEnabled',sn.enabled!==false)}${switchV2('routeOnly','routeOnly',sn.routeOnly!==false)}</div><div class="iv2-chip-control"><span>destOverride</span><div>${['http','tls','quic','fakedns'].map(v=>`<button type="button" data-v2-action="chip-toggle" data-value="${v}" class="${(sn.destOverride||['http','tls']).includes(v)?'active':''}">${v.toUpperCase()}</button>`).join('')}</div></div></section>
  <section class="iv2-tabpane" data-v2-pane="routing"><div class="iv2-section-title"><i></i><div><b>${L('Routing References','ارجاعات روتینگ')}</b><span>${L('Routing remains a shared global section; this view shows references to this inbound tag.','روتینگ بخش مشترک است؛ اینجا ارجاعات به تگ این اینباند نمایش داده می‌شود.')}</span></div></div><div class="iv2-routing-context" data-v2-routing-context><div class="iv2-loader"></div></div><button class="btn" type="button" data-v2-action="open-routing">${iconSafe('arrow')}${L('Open Routing Workspace','بازکردن بخش روتینگ')}</button></section>
  <section class="iv2-tabpane" data-v2-pane="advanced"><div class="iv2-section-title"><i></i><div><b>${L('Advanced JSON','JSON پیشرفته')}</b><span>${L('Native fields win for the values shown elsewhere; unknown advanced fields are preserved.','فیلدهای گرافیکی اولویت دارند و جزئیات پیشرفته حفظ می‌شوند.')}</span></div></div><div class="iv2-form-grid">${areaV2('Protocol settings','settingsJson',settings)}${areaV2('Stream settings','streamJson',st)}${areaV2('Sniffing','sniffingJson',sn)}</div></section>
 </div><footer class="iv2-drawer-foot"><button class="btn" type="button" data-v2-action="drawer-close">${L('Cancel','انصراف')}</button><button class="btn" type="button" data-v2-action="editor-validate">${iconSafe('check')}${L('Validate Core','اعتبارسنجی')}</button><button class="btn btn-primary" type="submit">${iconSafe('check')}${id?L('Save Changes','ذخیره تغییرات'):L('Create Inbound','ساخت اینباند')}</button></footer></form></aside></div>`;
}
function fallbackRow(f={}){return `<div class="iv2-fallback-row"><input class="iv2-input" name="fallbackPath" placeholder="Path (optional)" value="${attr(f.path||'')}"><input class="iv2-input" name="fallbackDest" placeholder="Destination" value="${attr(f.dest??'')}"><input class="iv2-input" name="fallbackXver" type="number" min="0" max="2" value="${attr(f.xver??0)}"><button type="button" class="iv2-icon danger" data-v2-action="fallback-remove">${iconSafe('trash')}</button></div>`;}
async function openEditor(id=null,draft=null){
 if(!isOwner())return toast(L('Owner access required.','دسترسی مالک لازم است.'),true);
 let d=draft?M.clone(draft):(id?(details[id]||await api('/api/inbounds/'+id)):M.template('custom',M.nextPort(state.inbounds,443)));
 if(id)details[id]=d;
 const o=$('#overlay');o.classList.add('show','inbounds-v2-overlay');o.style.display='flex';o.innerHTML=editorHTML(d,id);
 const form=$('#iv2-editor');form.dataset.id=id||'';form.addEventListener('submit',async ev=>{ev.preventDefault();await saveEditor(form,id);});
 syncEditorConditions(form);loadRoutingContext(form,d);
}
function syncEditorConditions(root){const net=root.querySelector('[name=network]')?.value||'tcp',sec=root.querySelector('[name=security]')?.value||'none',proto=root.querySelector('[name=protocol]')?.value||'vless';root.querySelectorAll('[data-v2-net-field]').forEach(el=>{const k=el.dataset.v2NetField;el.closest('.iv2-control').hidden=!((k==='path'&&['ws','httpupgrade','xhttp'].includes(net))||(k==='host'&&['ws','httpupgrade','xhttp'].includes(net))||(k==='grpc'&&net==='grpc')||(k==='xhttp'&&net==='xhttp')||(k==='kcp'&&net==='kcp'));});root.querySelectorAll('[data-v2-security]').forEach(el=>el.hidden=el.dataset.v2Security!==sec);const ss=root.querySelector('[name=ssmethod]')?.closest('.iv2-control');if(ss)ss.hidden=proto!=='shadowsocks';}
async function loadRoutingContext(form,d){const box=form.querySelector('[data-v2-routing-context]');if(!box)return;try{const routing=(await api('/api/settings/routing')).value,tag=d.tag||'',rules=(routing.rules||[]).filter(r=>(r.inboundTag||[]).includes(tag));box.innerHTML=rules.length?`<div class="iv2-route-list">${rules.map((r,i)=>`<div><b>#${i+1}</b><code>${e(JSON.stringify(r))}</code></div>`).join('')}</div>`:`<div class="iv2-empty-inline">${L('No routing rule currently references this inbound tag.','هیچ قانون روتینگی فعلاً به این تگ اشاره نمی‌کند.')}</div>`;}catch(ex){box.innerHTML=`<div class="notice error">${e(ex.message)}</div>`;}}
function parseJSONField(form,name){try{return JSON.parse(form.elements[name].value||'{}');}catch{throw Error(L('Invalid JSON in ','JSON نامعتبر در ')+name);}}
function collectFallbacks(form){const rows=[...form.querySelectorAll('.iv2-fallback-row')],out=[];for(const r of rows){const path=r.querySelector('[name=fallbackPath]').value.trim(),raw=r.querySelector('[name=fallbackDest]').value.trim(),xver=Number(r.querySelector('[name=fallbackXver]').value||0);if(!raw&&!path)continue;let dest=/^\d+$/.test(raw)?Number(raw):raw;const f={dest,xver};if(path)f.path=path;out.push(f);}return out;}
function buildBody(form,id){
 const fd=new FormData(form),settings=parseJSONField(form,'settingsJson'),st=parseJSONField(form,'streamJson'),sn=parseJSONField(form,'sniffingJson');
 const protocol=fd.get('protocol'),net=fd.get('network'),security=fd.get('security'),port=Number(fd.get('port'));
 if(!Number.isInteger(port)||port<1||port>65535)throw Error(L('Port must be between 1 and 65535.','پورت باید بین ۱ تا ۶۵۵۳۵ باشد.'));
 if(state.inbounds.some(r=>r.id!==id&&Number(r.port)===port))throw Error(L('This port is already used by another inbound.','این پورت توسط اینباند دیگری استفاده شده است.'));
 st.network=net;st.security=security;
 for(const k of ['wsSettings','grpcSettings','httpupgradeSettings','xhttpSettings','kcpSettings'])if(k!==net+'Settings')delete st[k];
 if(['ws','httpupgrade','xhttp'].includes(net)){const k=net+'Settings';st[k]={...(st[k]||{}),path:fd.get('path')||'/'};if(net==='ws')st[k].headers={...(st[k].headers||{}),Host:fd.get('host')||''};else st[k].host=fd.get('host')||'';if(net==='xhttp')st[k].mode=fd.get('xhttpMode')||'auto';}
 if(net==='grpc')st.grpcSettings={...(st.grpcSettings||{}),serviceName:fd.get('serviceName')||'',authority:fd.get('authority')||''};
 if(net==='kcp')st.kcpSettings={...(st.kcpSettings||{}),mtu:Number(fd.get('mtu')||1350),tti:Number(fd.get('tti')||50)};
 if(security==='reality'){delete st.tlsSettings;const key=fd.get('privateKey')||'',target=fd.get('realityTarget')||'',names=M.list(fd.get('realitySni')),ids=M.list(fd.get('shortIds'));st.realitySettings={...(st.realitySettings||{}),show:false,target,serverNames:names,privateKey:key,shortIds:ids,spiderX:fd.get('spiderX')||'/'};}
 else if(security==='tls'){delete st.realitySettings;const cert=fd.get('cert')||'',key=fd.get('key')||'';st.tlsSettings={...(st.tlsSettings||{}),serverName:fd.get('tlsServerName')||'',certificates:cert||key?[{certificateFile:cert,keyFile:key}]:[]};}
 else{delete st.realitySettings;delete st.tlsSettings;}
 if(protocol==='vless')settings.decryption=settings.decryption||'none';if(protocol==='shadowsocks')settings.method=fd.get('ssmethod')||'aes-128-gcm';
 const fallbacks=collectFallbacks(form);if(fallbacks.length)settings.fallbacks=fallbacks;else delete settings.fallbacks;
 sn.enabled=fd.get('sniffEnabled')==='true';sn.routeOnly=fd.get('routeOnly')==='true';sn.destOverride=[...form.querySelectorAll('[data-v2-action="chip-toggle"].active')].map(x=>x.dataset.value);
 const body={remark:String(fd.get('remark')||'DARK INBOUND').trim(),protocol,listen:String(fd.get('listen')||'0.0.0.0').trim(),port,enable:fd.get('enable')==='true',settings,streamSettings:st,sniffing:sn};const tag=String(fd.get('tag')||'').trim();if(tag)body.tag=tag;return body;
}
async function saveEditor(form,id,validateOnly=false){const body=buildBody(form,id);const submit=form.querySelector('button[type=submit]');if(submit)submit.disabled=true;try{if(validateOnly){toast(L('Local form checks passed. Save the inbound to run Xray-core validation.','بررسی فرم موفق بود؛ برای تست هسته ابتدا ذخیره کن.'));return;}await api('/api/inbounds'+(id?'/'+id:''),id?'PUT':'POST',body);ui.lastPrime=0;try{await api('/api/core/validate','POST',{});toast(L('Inbound saved and Xray validation passed.','اینباند ذخیره شد و اعتبارسنجی Xray موفق بود.'));}catch(ex){toast(L('Saved, but Xray validation reported: ','ذخیره شد، ولی اعتبارسنجی Xray گفت: ')+ex.message,true);}closeDialog();await refresh();}finally{if(submit?.isConnected)submit.disabled=false;}}
async function toggleInbound(id,enable){const d=details[id]||await api('/api/inbounds/'+id);const body=M.clone(d);delete body.id;delete body.applied;body.enable=enable;await api('/api/inbounds/'+id,'PUT',body);details[id]=body;toast(enable?L('Inbound enabled.','اینباند فعال شد.'):L('Inbound disabled.','اینباند غیرفعال شد.'));await refresh();}
async function bulkState(enable){if(!ui.selected.size)return toast(L('Select at least one inbound.','حداقل یک اینباند انتخاب کن.'),true);for(const id of [...ui.selected])await toggleInbound(Number(id),enable);ui.selected.clear();ui.bulkMenu=false;}
async function exportInbounds(){await primeDetails(true);const payload=state.inbounds.map(r=>details[r.id]||r),blob=new Blob([JSON.stringify({project:'DARK XRAY',schema:1,exported_at:new Date().toISOString(),inbounds:payload},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='dark-xray-inbounds-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function cloneInbound(id){const d=details[id]||await api('/api/inbounds/'+id),draft=M.cloneInbound(d,M.nextPort(state.inbounds,Number(d.port||443)+1));openEditor(null,draft);}
async function generateKeys(btn){try{const r=await api('/api/keys/x25519','POST',{}),form=btn.closest('form');form.elements.privateKey.value=r.privateKey;form.elements.shortIds.value=r.shortId||'';const out=form.querySelector('[data-v2-public-key]');if(out)out.textContent=L('Public key: ','کلید عمومی: ')+r.publicKey;toast(L('X25519 key pair generated.','جفت کلید X25519 ساخته شد.'));}catch(ex){toast(ex.message,true);}}
runAction=async function(act,el){if(act==='inboundnew')return openEditor();if(act==='inboundedit')return openEditor(Number(el.dataset.id));return baseRunAction(act,el);};
inboundPage=page;inboundForm=openEditor;
document.addEventListener('click',async ev=>{
 const el=ev.target.closest('[data-v2-action]');if(!el)return;const act=el.dataset.v2Action;
 try{
  if(act==='filter-menu'){ui._openFilter=ui._openFilter===el.dataset.kind?null:el.dataset.kind;renderPage();return;}
  if(act==='filter-set'){ui[el.dataset.kind]=el.dataset.value;ui._openFilter=null;renderPage();return;}
  if(act==='status'){ui.status=el.dataset.value;renderPage();return;}
  if(act==='create-menu'){ui.createMenu=!ui.createMenu;ui.bulkMenu=false;renderPage();return;}
  if(act==='bulk-menu'){ui.bulkMenu=!ui.bulkMenu;ui.createMenu=false;renderPage();return;}
  if(act==='new-template'){ui.createMenu=false;return openEditor(null,M.template(el.dataset.template,M.nextPort(state.inbounds,el.dataset.template==='vless-ws-tls'?443:2020)));}
  if(act==='core-validate'){await api('/api/core/validate','POST',{});toast(L('Xray-core validation passed.','اعتبارسنجی Xray موفق بود.'));return;}
  if(act==='export')return exportInbounds();if(act==='bulk-state')return bulkState(el.dataset.enable==='true');if(act==='clear-selection'){ui.selected.clear();ui.bulkMenu=false;renderPage();return;}
  if(act==='expand'){const id=Number(el.dataset.id);ui.expanded.has(id)?ui.expanded.delete(id):ui.expanded.add(id);renderPage();return;}
  if(act==='edit')return openEditor(Number(el.dataset.id));if(act==='clone')return cloneInbound(Number(el.dataset.id));if(act==='add-client')return clientForm(null,Number(el.dataset.id));
  if(act==='toggle-inbound')return toggleInbound(Number(el.dataset.id),el.dataset.enable==='true');
  if(act==='delete-inbound'){const id=Number(el.dataset.id);if(confirm(L('Delete this inbound? All clients/hosts/routes must be detached first.','این اینباند حذف شود؟ ابتدا همه کاربران/هاست‌ها/روت‌ها باید جدا شده باشند.'))){await api('/api/inbounds/'+id,'DELETE');delete details[id];await refresh();}return;}
  if(act==='client-edit')return clientForm(el.dataset.email);if(act==='client-links')return showLinks(el.dataset.email);if(act==='client-ips')return ipsDialog(el.dataset.email);if(act==='client-toggle')return confirmAction(el.dataset.email,el.dataset.enable==='true'?'enable':'disable');
  if(act==='drawer-close'){closeDialog();return;}if(act==='tab'){const form=el.closest('form');form.querySelectorAll('[data-v2-action=tab]').forEach(x=>x.classList.toggle('active',x===el));form.querySelectorAll('[data-v2-pane]').forEach(x=>x.classList.toggle('active',x.dataset.v2Pane===el.dataset.tab));return;}
  if(act==='combo-toggle'){const box=el.closest('[data-v2-combo]'),menu=box.querySelector('.iv2-combo-menu');document.querySelectorAll('.iv2-combo-menu').forEach(x=>{if(x!==menu)x.hidden=true;});menu.hidden=!menu.hidden;menu.querySelector('input')?.focus();return;}
  if(act==='combo-set'){const box=el.closest('[data-v2-combo]'),input=box.querySelector('input[type=hidden]'),label=box.querySelector('[data-v2-combo-label]');input.value=el.dataset.value;label.textContent=el.textContent.trim();box.querySelectorAll('.iv2-combo-options button').forEach(x=>x.classList.toggle('active',x===el));box.querySelector('.iv2-combo-menu').hidden=true;syncEditorConditions(el.closest('form'));return;}
  if(act==='switch'){const b=el,hidden=b.parentElement.querySelector('input[type=hidden]');b.classList.toggle('on');hidden.value=b.classList.contains('on')?'true':'false';return;}
  if(act==='chip-toggle'){el.classList.toggle('active');return;}if(act==='fallback-add'){el.closest('form').querySelector('[data-v2-fallback-list]').insertAdjacentHTML('beforeend',fallbackRow());return;}if(act==='fallback-remove'){el.closest('.iv2-fallback-row').remove();return;}
  if(act==='gen-x25519')return generateKeys(el);if(act==='editor-validate')return saveEditor(el.closest('form'),Number(el.closest('form').dataset.id)||null,true);if(act==='open-routing'){closeDialog();return go('routing');}
 }catch(ex){toast(ex.message,true);}
});
document.addEventListener('change',ev=>{if(ev.target.matches('[data-v2-select]')){const id=Number(ev.target.dataset.v2Select);ev.target.checked?ui.selected.add(id):ui.selected.delete(id);}});
document.addEventListener('input',ev=>{if(ev.target.id==='iv2-search'){ui.query=ev.target.value;clearTimeout(ui._timer);ui._timer=setTimeout(()=>{if(state.page==='inbounds')renderPage();},120);return;}if(ev.target.matches('[data-v2-filter-search],[data-v2-combo-search]')){const q=ev.target.value.toLowerCase();ev.target.closest('.iv2-popover,.iv2-combo-menu')?.querySelectorAll('.iv2-pop-list button,.iv2-combo-options button').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(q));return;}if(ev.target.matches('[data-v2-client-search]')){const q=ev.target.value.toLowerCase(),card=ev.target.closest('.iv2-expanded');card.querySelectorAll('[data-v2-client-row]').forEach(r=>r.hidden=!r.dataset.v2ClientRow.toLowerCase().includes(q));}});
document.addEventListener('click',ev=>{if(!ev.target.closest('.iv2-filter-combo')&&ui._openFilter){ui._openFilter=null;if(state.page==='inbounds')renderPage();}if(!ev.target.closest('[data-v2-combo]'))document.querySelectorAll('.iv2-combo-menu').forEach(x=>x.hidden=true);});
})();
