'use strict';
/* Real API client. No offline fallback or credential persistence. */
const ICONS={
 grid:'<rect x="3" y="3" width="7" height="7" rx="1.4"/><rect x="14" y="3" width="7" height="7" rx="1.4"/><rect x="3" y="14" width="7" height="7" rx="1.4"/><rect x="14" y="14" width="7" height="7" rx="1.4"/>',
 server:'<rect x="3" y="3" width="18" height="7" rx="2"/><rect x="3" y="14" width="18" height="7" rx="2"/><path d="M7 6.5h.01M7 17.5h.01M16 6.5h2M16 17.5h2"/>',
 users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/><circle cx="9" cy="7" r="4"/>',
 reseller:'<path d="m12 3 9 5v8l-9 5-9-5V8l9-5Z M3 8l9 5 9-5M12 13v8"/>',
 shield:'<path d="m12 3 8 3v5c0 5-3 8-8 10-5-2-8-5-8-10V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
 node:'<rect x="8" y="3" width="8" height="6" rx="1"/><rect x="2" y="16" width="7" height="5" rx="1"/><rect x="15" y="16" width="7" height="5" rx="1"/><path d="M12 9v4M5.5 16v-3h13v3"/>',
 wallet:'<path d="M20 7V5a2 2 0 0 0-2-2H6a3 3 0 0 0 0 6h14v11H5a3 3 0 0 1-3-3V6"/><path d="M20 12h-5v5h5M16 14.5h.01"/>',
 log:'<path d="M7 3h10l3 3v15H4V3h3M8 8h5M8 12h8M8 16h5"/>',
 settings:'<path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M5.6 18.4 7 17M17 7l1.4-1.4"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
 arrow:'<path d="M19 12H5M10 7l-5 5 5 5"/>',
 chevron:'<path d="m6 9 6 6 6-6"/>',
 activity:'<path d="M2 12h4l3-8 5 16 3-8h5"/>',
 lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 close:'<path d="m6 6 12 12M18 6 6 18"/>',
 alert:'<path d="m12 3 10 18H2L12 3ZM12 9v5M12 17h.01"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 10v6M12 7h.01"/>',
 eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
 edit:'<path d="m15 4 5 5M4 20l5-1L21 7l-5-5L4 14v6Z"/>',
 refresh:'<path d="M20 7V3l-3 3a8 8 0 1 0 3 10M20 7h-5"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
 download:'<path d="M12 3v12M7 10l5 5 5-5M4 17v4h16v-4"/>',
 cpu:'<rect x="6" y="6" width="12" height="12" rx="2"/><rect x="9" y="9" width="6" height="6" rx="1"/><path d="M9 2v4M15 2v4M9 18v4M15 18v4M2 9h4M2 15h4M18 9h4M18 15h4"/>',
 globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
 power:'<path d="M12 2v10M6.3 5.7a8 8 0 1 0 11.4 0"/>',
 link:'<path d="m10 13 4-4M8 16l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0M16 8l1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0" transform="translate(0 -1) scale(.95)"/>',
 trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/>',
 terminal:'<path d="m5 6 5 5-5 5M13 17h6"/>',
 copy:'<rect x="8" y="8" width="13" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>'
};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const PANEL_BASE=location.pathname==='/'?'':location.pathname.replace(/\/+$/,'');
const appUrl=path=>PANEL_BASE+(String(path).startsWith('/')?String(path):'/'+String(path));
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${ICONS[n]||ICONS.grid}</svg>`;
const gb=1024**3, enc=encodeURIComponent, fa=n=>Number(n||0).toLocaleString((localStorage.getItem('dark_lang')||'en')==='fa'?'fa-IR':'en-US');
const date=t=>{if(!t)return '—';const lang=(localStorage.getItem('dark_lang')||'en')==='fa'?'fa-IR':'en-US',cal=state?.me?.ui?.datepicker==='jalalian'?'-u-ca-persian':'',zone=state?.me?.ui?.timezone||'UTC';try{return new Date(t*1000).toLocaleString(lang+cal,{timeZone:zone});}catch{return new Date(t*1000).toLocaleString(lang);}};
function bytes(v){if(v===undefined||v===null)return '—';v=Number(v);if(!Number.isFinite(v))return '—';let u=0;while(v>=1024&&u<4){v/=1024;u++;}return `${v.toFixed(u?1:0)} ${['B','KiB','MiB','GiB','TiB'][u]}`;}
const state={me:null,page:'dashboard',clients:[],owners:[],resellers:[],inbounds:[],sync:null,system:null,errors:{},expanded:new Set(),selected:new Set(),search:'',busy:false,history:[],renderSeq:0};
const can=(key,owner=state.me?.id)=>state.me?.role==='owner'||state.me?.permissions?.[key]==='all'||(state.me?.permissions?.[key]==='own'&&owner===state.me?.id);
const isOwner=()=>state.me?.role==='owner';
const labelState={applied:'ذخیره‌شده در DARK',pending:'در صف',error:'خطای اجرا',conflict:'تعارض',uncertain:'نتیجه نامشخص',deleted:'حذف‌شده',reset_inflight:'در حال ریست',missing:'در دیتابیس اجرا یافت نشد'};
const reasons={client_manual:'قطع دستی مشتری',owner_manual:'قطع دستی نماینده',client_quota:'اتمام حجم مشتری',expired:'منقضی',owner_account_disabled:'حساب نماینده غیرفعال',engine_manual_or_external_disable:'قطع دستی در موتور محلی'};
function toast(text,error=false){let el=document.createElement('div');el.className='toast'+(error?' error':'');el.innerHTML=icon(error?'alert':'check')+`<span>${e(text)}</span>`;$('#toasts').append(el);setTimeout(()=>el.remove(),6500);}
function errText(x){if(typeof x==='string')return x;if(Array.isArray(x))return x.map(v=>`${v.loc?.join('.')||''}: ${v.msg||JSON.stringify(v)}`).join(' / ');return JSON.stringify(x);}
async function api(path,method='GET',body){const headers={Accept:'application/json'};if(body!==undefined)headers['Content-Type']='application/json';if(method!=='GET')headers['X-Dark-CSRF']=state.me?.csrf||'';let res;try{res=await fetch(appUrl(path),{method,headers,credentials:'same-origin',body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});}catch{throw Error('ارتباط با سرویس DARK برقرار نیست.');}let data=await res.json().catch(()=>({detail:'پاسخ نامعتبر سرور'}));if(!res.ok){if(res.status===401&&path!=='/api/auth/login'){state.me=null;loginPage();}throw Error(errText(data.detail||data.msg||`HTTP ${res.status}`));}return data;}
function brand(){return `<div class="brand"><div class="brand-mark">${icon('shield')}</div><div><div class="brand-name">DARK <span>XRAY</span></div><div class="brand-sub">LOCAL ENGINE · DARK CONTROL</div></div></div>`;}
const enginePages={hosts:['آدرس‌های عمومی'],outbounds:['اوتباندها'],routing:['روتینگ'],xray:['تنظیمات Xray'],nodes:['نودها'],settings:['تنظیمات پنل']};
function navItems(){let n=[['dashboard','نمای کلی','grid'],['inbounds','اینباندها','server'],['clients','کاربران','users']];if(isOwner())n.push(['resellers','نمایندگان','reseller']);n.push(['ipguard','محدودیت IP و دستگاه','lock']);if(can('finance.read'))n.push(['finance','دفتر حساب','wallet']);n.push(['sync','همگام‌سازی','refresh']);if(isOwner())n.push(['hosts','آدرس‌های عمومی','globe'],['outbounds','اوتباندها','arrow'],['routing','روتینگ','node'],['nodes','نودها','server'],['xray','تنظیمات Xray','terminal'],['settings','تنظیمات پنل','settings']);n.push(['account','حساب و امنیت','shield']);return n;}
function shell(){const ui=state.me?.ui||{};document.body.dataset.darkDensity=ui.density||'comfortable';document.body.classList.toggle('dark-reduced-motion',!!ui.reduced_motion);document.title=(ui.title||'DARK XRAY')+' | Cyber Control Center';const nav=navItems();const active=nav.find(n=>n[0]===state.page)?.[1]||enginePages[state.page]?.[0]||'DARK XRAY';$('#app').innerHTML=`<aside class="sidebar">${brand()}<div class="nav-section-label">مرکز کنترل</div><nav>${nav.map(([id,title,ic])=>`<button class="nav-btn ${id===state.page?'active':''}" data-page="${id}">${icon(ic)}<span>${title}</span></button>`).join('')}</nav><div class="side-bottom"><span class="code-caption">${e((state.me?.version||'0.7').replace('-standalone-lab',''))} · STANDALONE</span><span class="login-note">پنل مستقل · مدیریت مستقیم Xray-core</span></div></aside><main class="main"><header class="topbar"><button class="icon-btn mobile-menu" data-act="menu" aria-label="منو">${icon('menu')}</button><span class="breadcrumb">مرکز کنترل / <b>${e(active)}</b></span><div class="spacer"></div><span class="tag ${isOwner()?'green':'purple'}">${isOwner()?'مالک اصلی':'دسترسی محدود'}</span><span class="mono">${e(state.me.id)}</span><button class="icon-btn" data-act="refresh" aria-label="بروزرسانی">${icon('refresh')}</button><button class="icon-btn" data-act="logout" aria-label="خروج">${icon('power')}</button></header><div class="live-banner ${state.me.test_engine||!state.me.writes_enabled?'warning':''}">${icon(state.me.test_engine?'alert':'activity')} ${state.me.test_engine?'محیط آزمون خودکار — هستهٔ شبیه‌ساز؛ این اعداد دادهٔ VPS نیستند.':`حالت متصل · بدون دادهٔ نمونه · ${state.me.writes_enabled?'ذخیره در دیتابیس مستقل DARK فعال است':'حالت فقط خواندنی؛ نوشتن غیرفعال است'}`}</div><section class="content" id="content"></section></main>`;}
function heading(title,sub,actions=''){return `<div class="page-heading"><div><div class="eyebrow">DARK OPERATIONS / ${e(state.page.toUpperCase())}</div><h1>${title}</h1><p>${sub}</p></div><div class="heading-actions">${actions}</div></div>`;}
function button(text,act,ic='plus',extra='',primary=false){return `<button class="btn ${primary?'btn-primary':''}" data-act="${act}" ${extra}>${icon(ic)}${text}</button>`;}
function empty(text){return `<div class="empty-state">${icon('info')}<p>${text}</p></div>`;}
function notices(){return Object.entries(state.errors).map(([k,v])=>`<div class="notice error"><b>${e(k)}</b> — ${e(v)}<br>اطلاعات این بخش دریافت نشده؛ با دادهٔ نمونه جایگزین نشده است.</div>`).join('');}
async function load(){if(!state.me)return;const specs=[['clients','/api/clients'],['inbounds','/api/inbounds'],['owners','/api/owners'],['sync','/api/sync']];if(isOwner())specs.push(['resellers','/api/resellers']);if(can('system.read'))specs.push(['system','/api/system']);await Promise.all(specs.map(async([key,path])=>{try{state[key]=await api(path);delete state.errors[key];}catch(ex){state.errors[key]=ex.message;if(key!=='sync')state[key]=key==='system'?null:[];}}));if(state.system?.engine){let n=state.system.engine;let v=Number(n.cpu);if(Number.isFinite(v)){state.history.push(v);state.history=state.history.slice(-60);}}}
async function refresh(){
 if(state.busy){
  await new Promise(resolve=>{
   const wait=()=>state.busy?setTimeout(wait,20):resolve();
   wait();
  });
  return refresh();
 }
 state.busy=true;
 try{await load();if(state.me)await renderPage();}
 finally{state.busy=false;}
}
function badge(r){if(r.state!=='applied')return `<span class="tag amber">${e(labelState[r.state]||r.state)}</span>`;if(r.block_reasons?.length)return `<span class="tag red" title="${e(r.block_reasons.map(x=>reasons[x]||x).join('، '))}">محدود شده</span>`;return `<span class="tag ${r.data_plane_state==='running'?'green':'amber'}">${r.observed_enable===false?'غیرفعال':r.data_plane_state==='running'?'نسخهٔ هسته همسان است':'ذخیره‌شده؛ هنوز روی هسته اجرا نشده'}</span>`;}
function clientTable(rows){if(!rows.length)return empty('کاربر تحت مدیریت DARK در این فهرست نیست. مشتری‌های قدیمی باید صریحاً به مالک تخصیص داده شوند.');return `<div class="table-wrap"><table class="clients-table"><thead><tr><th></th><th>کاربر / مالک</th><th>وضعیت همگام‌سازی</th><th>مصرف / سهمیه</th><th>انقضا</th><th>IP / HWID</th><th>عملیات</th></tr></thead><tbody>${rows.map(r=>{let c=r.client||{};return `<tr><td><input type="checkbox" data-select="${e(r.email)}" ${state.selected.has(r.email)?'checked':''} aria-label="انتخاب ${e(r.email)}"></td><td><b class="client-name">${e(r.email)}</b><br><span class="owner-label">${e(r.owner)}</span></td><td>${badge(r)}${r.error?`<div class="data-error">${e(r.error)}</div>`:''}</td><td><span class="mono">${bytes(r.used_bytes)}</span><br><span class="muted">${c.totalGB?bytes(c.totalGB):'نامحدود'}</span></td><td>${c.expiryTime>0?new Date(c.expiryTime).toLocaleDateString('fa-IR'):c.expiryTime<0?'شروع از اتصال اول':'بدون انقضا'}</td><td><span class="mono">${c.limitIp||'∞'} / ${c.limitHwid||'پیش‌فرض'}</span></td><td><div class="row-actions">${can('clients.edit',r.owner)?button('ویرایش','edit','edit',`data-id="${e(r.email)}"`):''}${can('clients.credentials',r.owner)?button('لینک','links','link',`data-id="${e(r.email)}"`):''}${can('clients.ip',r.owner)?button('IP / دستگاه','ips','shield',`data-id="${e(r.email)}"`):''}${can('clients.edit',r.owner)?button(c.enable===false?'فعال':'قطع','toggle','power',`data-id="${e(r.email)}"`):''}${can('clients.reset',r.owner)?button('ریست','reset','refresh',`data-id="${e(r.email)}"`):''}${can('clients.delete',r.owner)?button('حذف','delete','trash',`data-id="${e(r.email)}"`):''}</div></td></tr>`;}).join('')}</tbody></table></div>`;}
function filtered(rows){let q=state.search.toLowerCase().trim();return rows.filter(r=>!q||r.email.toLowerCase().includes(q)||r.owner.toLowerCase().includes(q));}
function searchbar(){return `<div class="table-toolbar"><input class="field-input" id="search" type="search" placeholder="جست‌وجوی نام کاربر یا مالک" value="${e(state.search)}"><span class="list-summary">${fa(state.clients.length)} مشتری ثبت‌شده</span><div class="spacer"></div>${button('عملیات انتخاب‌شده','bulk','users')}</div>`;}
function metric(title,value,sub,color='var(--green)'){return `<article class="panel resource-card" style="--metric:${color}"><div class="kpi-title">${icon('activity')}${title}</div><div class="metric-number mono">${e(value)}</div><div class="metric-footer">${e(sub)}</div></article>`;}
function percent(x){if(!x)return '—';let v=typeof x==='number'?x:x.total?100*(x.current??x.used??0)/x.total:null;return v==null||!Number.isFinite(v)?'—':v.toFixed(1)+'%';}
function dashboard(){let n=state.system?.engine||{},sync=state.sync||{};return heading('نمای کلی','منابع هسته و وضعیت مدیریت کاربران؛ داده‌ها از سرویس دریافت می‌شوند.',isOwner()?button('همگام‌سازی','syncnow','refresh'):'')+notices()+`<div class="metrics-grid">${metric('CPU',n.cpu===undefined?'—':Number(n.cpu).toFixed(1)+'%','LOCAL HOST')}${metric('حافظه RAM',percent(n.mem),`${bytes(n.mem?.current)} / ${bytes(n.mem?.total)}`,'var(--cyan)')}${metric('دیسک',percent(n.disk),`${bytes(n.disk?.current)} / ${bytes(n.disk?.total)}`,'var(--purple)')}${metric('Swap',percent(n.swap),`${bytes(n.swap?.current)} / ${bytes(n.swap?.total)}`,'var(--amber)')}</div><div class="metrics-grid">${metric('کاربران مدیریت‌شده',fa(state.clients.length),'OWNERSHIP REGISTER')}${metric('محدود شده',fa(state.clients.filter(c=>c.block_reasons?.length).length),'POLICY BLOCKERS','var(--amber)')}${metric('ارسال / ثانیه',bytes(n.netIO?.up),'TX · LOCAL','var(--cyan)')}${metric('دریافت / ثانیه',bytes(n.netIO?.down),'RX · LOCAL','var(--purple)')}</div><div class="overview-grid"><article class="panel"><div class="panel-head"><h2>نمونه‌های زندهٔ CPU در این نشست</h2><span class="tag">${fa(state.history.length)} مشاهده</span></div><div class="panel-body">${state.history.length>1?`<svg class="sparkline" viewBox="0 0 600 130" preserveAspectRatio="none"><path d="M0 120H600M0 65H600M0 10H600" stroke="#ffffff0b"/><polyline fill="none" stroke="var(--green)" stroke-width="2" points="${state.history.map((v,i)=>`${i*600/(state.history.length-1)},${120-Math.min(100,Math.max(0,v))*1.1}`).join(' ')}"/></svg>`:empty('برای نمودار حداقل دو پاسخ واقعی لازم است.')}<p class="legend-note">فقط پاسخ‌های دریافت‌شده؛ بدون نقاط تصادفی یا تاریخچهٔ ساختگی.</p></div></article><article class="panel"><div class="panel-head"><h2>وضعیت ارتباط</h2>${icon('server')}</div><div class="panel-body"><p>هسته: <b class="mono">${e(n.xray?.state||n.xrayState||'—')}</b></p><p>آپ‌تایم: <b class="mono">${n.uptime===undefined?'—':Math.floor(n.uptime/3600)+' h'}</b></p><p>نسخهٔ Xray محلی: <b class="mono">${e(sync.engine_version||'تأیید نشده')}</b></p><p>آخرین دریافت: ${date(sync.last_poll)}</p><div class="notice ${sync.error?'error':''}">${e(sync.error||'پذیرش درخواست توسط API به معنی تأیید انتقال بسته‌های شبکه نیست.')}</div></div></article></div><article class="panel" style="margin-top:18px"><div class="panel-head"><h2>آخرین کاربران</h2>${button('همه کاربران','allclients','users')}</div>${clientTable(state.clients.slice(-5).reverse())}</article>`;}
function inboundPage(){return heading('اینباندها','شنونده‌های مستقل Xray؛ کاربران زیر همان اینباند مدیریت می‌شوند.',isOwner()?button('اینباند جدید','inboundnew','plus','',true):'')+notices()+
 `<div class="notice ${state.sync?.runtime?.running?'':'warning'}">هسته: ${state.sync?.runtime?.running?'در حال اجرا':'متوقف'} · ${state.sync?.runtime?.dirty?'تنظیمات ذخیره‌شده هنوز با نسخهٔ اجرا همسان نیست':'نسخهٔ اجرا همسان است'}</div>`+
 (state.inbounds.length?state.inbounds.map(i=>`<article class="panel inbound-item"><div class="panel-head"><div><h2>${e(i.remark||i.tag)}</h2><span class="mono">${e(i.protocol)} / ${e(i.listen||'0.0.0.0')}:${i.port}</span> <span class="tag ${i.enable?'green':'red'}">${i.enable?'فعال در تنظیمات':'غیرفعال'}</span></div><div class="row-actions">${button('کاربران','expand','users',`data-id="${i.id}"`)}${can('clients.create')?button('کاربر جدید','new','plus',`data-inbound="${i.id}"`):''}${isOwner()?button('ویرایش','inboundedit','edit',`data-id="${i.id}"`)+button('حذف','inbounddelete','trash',`data-id="${i.id}"`):''}</div></div>${state.expanded.has(i.id)?clientTable(state.clients.filter(c=>c.inboundIds.includes(i.id))):''}</article>`).join(''):empty('هنوز اینباندی نساخته‌ای. از «اینباند جدید» شروع کن.'));}

function clientsPage(){return heading('کاربران','حجم، زمان، IP و اشتراک؛ ذخیره و اجرا از طریق API.',`${isOwner()?button('تخصیص مشتری قدیمی','adopt','link'):''}${can('clients.create')?button('افزودن کاربر','new','plus','',true):''}`)+notices()+`<article class="panel">${searchbar()}${clientTable(filtered(state.clients))}</article>`;}
function resellerPage(){const rows=state.resellers||[];return heading('نمایندگان','اعتبار فروش حجمی و نامحدود، حساب ورود، سیاست مشتری و اینباندهای هر نماینده از همین بخش مدیریت می‌شود.',button('افزودن نماینده','ownernew','plus','',true))+`<div class="notice">DARK فقط یک مالک اصلی دارد. اعتبار نماینده پول نیست: سرویس حجمی از Volume Credit رزرو می‌کند و هر سرویس نامحدود یک Unlimited Credit می‌گیرد. مصرف واقعی Xray فقط گزارش است و از اعتبار فروش کم نمی‌شود.</div><div class="reseller-list">${rows.length?rows.map(o=>`<article class="panel reseller-card"><div class="page-heading"><div><h2>${e(o.name)}</h2><small class="mono">${e(o.id)}</small></div><span class="tag ${o.enabled?'green':o.login_ready?'amber':'red'}">${o.enabled?'فعال':o.login_ready?'غیرفعال':'ورود ساخته نشده'}</span></div><div class="details"><div><span>Volume Credit باقی‌مانده</span><b>${bytes(o.volume_credit_remaining_bytes??0)} / ${bytes(o.volume_credit_bytes??0)}</b></div><div><span>حجم رزروشده مشتری‌ها</span><b>${bytes(o.allocated_volume_bytes??0)}</b></div><div><span>Unlimited Credit باقی‌مانده</span><b>${fa(o.unlimited_credit_remaining??0)} / ${fa(o.unlimited_credit??0)}</b></div><div><span>نامحدودهای رزروشده</span><b>${fa(o.allocated_unlimited??0)}</b></div><div><span>مصرف واقعی دوره</span><b>${bytes(o.used_bytes??0)}</b></div><div><span>سقف تعداد مشتری</span><b>${o.max_clients||'∞'}</b></div><div><span>Prefix مشتری</span><b class="mono">${e(o.prefix||'—')}</b></div><div><span>Max IP / HWID هر مشتری</span><b>${o.max_client_ips||'∞'} / ${o.max_client_hwid||'∞'}</b></div><div><span>اینباندهای مجاز</span><b>${e((o.allowed||[]).join(', ')||'هیچ')}</b></div></div><div class="row-actions">${button('مدیریت نماینده','owneredit','edit',`data-id="${e(o.id)}"`)}${button('تنظیم اعتبار','resourcecredit','wallet',`data-id="${e(o.id)}"`,true)}${button('دوره آمار جدید','period','refresh',`data-id="${e(o.id)}"`)}${button('حذف نماینده','ownerdelete','trash',`data-id="${e(o.id)}"`)}</div></article>`).join(''):empty('هنوز نماینده‌ای ساخته نشده است.')}</div>`;}
function jsonBox(obj){return `<pre class="json-box">${e(JSON.stringify(obj,null,2))}</pre>`;}
async function ipPage(){let status=null;try{status=await api('/api/security-center');}catch(ex){status={error:ex.message};}return heading('مرکز امنیت DARK','سیاست Native برای IP و دستگاه با nftables محلی و تجمیع Local + Node.')+`<div class="ip-shell"><article class="panel"><span class="code-caption">DARK NATIVE SECURITY</span><h2>وضعیت Security Center</h2>${status?.error?`<div class="notice error">${e(status.error)}</div>`:'<p>ماژول Security Center V4 وضعیت دقیق Guard، Node telemetry و سیاست کاربران را نمایش می‌دهد.</p>'}<div class="notice">Enforcement محلی توسط Broker محدود و root-owned خود DARK روی nftables انجام می‌شود.</div></article></div>`;}
async function financePage(){const credits=await api('/api/ledger/credits');let traffic=[];try{traffic=await api('/api/ledger/traffic');}catch{}return heading('اعتبار و دفتر نمایندگان','اعتبار Volume/Unlimited از مصرف واقعی Xray جداست؛ قیمت فروش مشتری داخل DARK نگهداری نمی‌شود.')+`<div class="notice">کاربر حجمی از Volume Credit و کاربر نامحدود از Unlimited Credit رزرو می‌کند. مصرف واقعی فقط گزارش است و اعتبار فروش را خرج نمی‌کند.</div><article class="panel"><div class="panel-head"><h2>تغییرات اعتبار نمایندگان</h2></div>${ledgerTable(credits,'credits')}</article><article class="panel" style="margin-top:18px"><div class="panel-head"><h2>مصرف ثبت‌شده از Xray</h2></div>${ledgerTable(traffic,'traffic')}</article>`;}
function ledgerTable(rows,kind){const traffic=kind==='traffic';return rows.length?`<div class="table-wrap"><table><thead><tr><th>زمان</th><th>نماینده</th><th>${traffic?'مشتری':'نوع'}</th><th>${traffic?'مصرف':'تغییر اعتبار'}</th><th>مرجع</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${date(traffic?r.observed_at:r.at)}</td><td>${e(r.owner)}</td><td>${e(traffic?r.client_id:r.kind)}</td><td class="mono">${traffic?bytes(Number(r.up_bytes||0)+Number(r.down_bytes||0)):`Volume ${r.volume_bytes>=0?'+':''}${bytes(Math.abs(r.volume_bytes||0))} · Unlimited ${r.unlimited_units>=0?'+':''}${fa(r.unlimited_units||0)}`}</td><td class="mono">${e(r.event_id)}</td></tr>`).join('')}</tbody></table></div>`:empty('رویدادی ثبت نشده است.');}
async function auditPage(){const rows=await api('/api/audit');return heading('گزارش عملیات','رویدادهای DARK با هویت اجراکننده؛ این گزارش با لاگ اتصال Xray جداست.')+`<article class="panel"><div class="table-wrap"><table><thead><tr><th>زمان</th><th>اجراکننده</th><th>عملیات</th><th>هدف</th><th>جزئیات</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${date(r.at)}</td><td>${e(r.actor)}</td><td class="mono">${e(r.action)}</td><td>${e(r.target)}</td><td>${e(r.detail)}</td></tr>`).join('')}</tbody></table></div></article>`;}
function syncPage(){let s=state.sync||{};return heading('همگام‌سازی','وضعیت درخواست و پاسخ هسته؛ عملیات ناموفق به‌جای موفقیت صوری ثبت می‌شود.',isOwner()?button('دریافت و تطبیق','syncnow','refresh','',true):'')+`<div class="notice ${s.error?'error':''}">${e(s.error||'خطایی در آخرین دور ثبت نشده است.')}<br>آخرین دریافت: ${date(s.last_poll)} · نسخهٔ هسته: <span class="mono">${e(s.engine_version||'نامشخص')}</span></div><article class="panel"><div class="table-wrap"><table><thead><tr><th>مشتری</th><th>مالک</th><th>عملیات</th><th>وضعیت</th><th>خطا</th></tr></thead><tbody>${(s.items||[]).map(r=>`<tr><td class="mono">${e(r.email)}</td><td>${e(r.owner)}</td><td>${e(r.op)}</td><td>${e(labelState[r.state]||r.state)}</td><td class="data-error">${e(r.error)}${r.state==='uncertain'&&isOwner()?button('پذیرش وضعیت فعلی','resolvereset','refresh',`data-id="${e(r.email)}"`):''}</td></tr>`).join('')}</tbody></table></div></article><div class="notice warning">نتیجهٔ نامشخصِ ریست خودکار تکرار نمی‌شود؛ ابتدا وضعیت هستهٔ محلی و دفتر مصرف را بررسی کن. ذخیره در DARK به معنی اجرای موفق هسته یا تأیید فایروال نیست.</div>`;}
async function accountPage(){let keys=can('api.manage')?await api('/api/keys'):[],sessions=await api('/api/auth/sessions');return heading('حساب و امنیت','رمز، نشست، ورود دومرحله‌ای و کلید مستقل برای اتصال نرم‌افزارها.')+`<div class="account-grid"><article class="panel"><h2>ورود دومرحله‌ای TOTP</h2><p>وضعیت: ${state.me.totp_enabled?'فعال':'غیرفعال'}؛ تنظیمات این بخش برای ورود DARK است، ورود دوم دیگری وجود ندارد.</p>${button(state.me.totp_enabled?'غیرفعال‌سازی با تأیید':'راه‌اندازی TOTP',state.me.totp_enabled?'mfadisable':'mfasetup','shield')}</article><article class="panel"><h2>رمز حساب</h2><p>با تغییر رمز، تمام نشست‌های این حساب باطل می‌شوند.</p>${button('تغییر رمز','password','lock')}</article><article class="panel"><h2>نشست‌های فعال</h2><p>${sessions.length} نشست فعال برای این حساب ثبت شده است.</p>${sessions.length>1?button('خروج از همه نشست‌های دیگر','sessionsothers','power'):''}${sessions.map(s=>`<div class="connection-strip"><span><b>${s.current?'این نشست':'نشست دیگر'}</b> · ${e(s.source||'unknown')}<br><small>${s.created_at?date(s.created_at):'زمان ساخت نامشخص'} → ${date(s.expires_at)} · ${e(s.user_agent||'User-Agent نامشخص')}</small></span>${s.current?'<span class="tag green">CURRENT</span>':button('ابطال','sessiondelete','trash',`data-id="${e(s.id)}"`)}</div>`).join('')}</article>${can('api.manage')?`<article class="panel"><h2>کلید API</h2><p>مجوز کلید بیشتر از حساب سازنده نیست. کلید فقط یک‌بار نمایش داده می‌شود. این API فقط برای اتصال ابزارهای مجاز به DARK XRAY است و سطح دسترسی آن از حساب سازنده فراتر نمی‌رود.</p>${button('ساخت کلید','keynew','plus')}${keys.map(k=>`<div class="connection-strip"><span>${e(k.name)} · ${k.revoked?'باطل':date(k.expires_at)}</span>${k.revoked?'':button('ابطال','keydelete','trash',`data-id="${e(k.id)}"`)}</div>`).join('')}</article>`:''}${isOwner()?`<article class="panel"><h2>بکاپ دیتابیس DARK</h2><p>این فایل تمام جدول‌های DARK را شامل می‌شود. این دانلود فقط دیتابیس است. برای دیتابیس همراه کلید TOTP و تنظیمات، از دستور darkxray backup و بستهٔ رمزدار استفاده کن.</p><a class="btn" href="${appUrl('/api/backup')}">${icon('download')}بکاپ DARK</a></article>`:''}</div>`;}
async function enginePage(){
 const title=enginePages[state.page][0];
 if(state.page==='nodes')return heading(title,'معماری نود مستقل؛ بدون استفاده از پنل دیگری.')+`<div class="notice warning">مدیریت نودهای دوردست هنوز در نسخهٔ مستقل پیاده‌سازی نشده است. این صفحه نود یا وضعیت ساختگی نمایش نمی‌دهد.</div>`;
 if(state.page==='xray'){
  const rt=await api('/api/core/state'),cfg=await api('/api/core/config');
  return heading(title,'باینری محلی Xray مستقیماً زیر مدیریت DARK است.',button('اعتبارسنجی','corevalidate','check')+button('راه‌اندازی / اعمال','corestart','power','',true)+button('توقف','corestop','power'))+
  `<div class="notice ${rt.running?'':'warning'}">وضعیت: <b>${rt.running?'در حال اجرا':'متوقف'}</b> · ${rt.dirty?'تغییرات اعمال‌نشده داریم':'نسخهٔ اجرا همسان است'} · ${rt.core_binary_present?'فایل هسته موجود است':'باینری Xray هنوز نصب نشده است'}<br>${e(rt.last_error||'')}<br>اعمال تنظیمات در این نسخه ممکن است Xray را دوباره راه‌اندازی کند و اتصال‌های جاری قطع شوند.</div>`+
  `<div class="row-actions">${[['dns','DNS'],['policy','Policy'],['observatory','Observatory']].map(([k,l])=>button(l,'sectionedit','settings',`data-section="${k}"`)).join('')}</div><article class="panel" style="margin-top:20px"><h2>پیکربندی ساخته‌شده از دیتابیس DARK</h2><p>این نمایش شامل کلیدهاست؛ آن را عمومی منتشر نکن.</p>${jsonBox(cfg)}</article>`;
 }
 const key=state.page==='settings'?'panel':state.page,data=await api('/api/settings/'+key);
 const notes={hosts:'Endpoint عمومی یا تانل که در لینک و Subscription مشتری استفاده می‌شود.',outbounds:'تنظیمات خروجی مستقیم Xray؛ بدون API پنل واسط.',routing:'ترتیب قواعد در JSON، ترتیب اجرای مسیر است.',settings:'تنظیمات نمایش. پورت، دامنهٔ ورود و مسیر باینری در config.json مدیریت می‌شوند.'};
 return heading(title,notes[state.page],button('ویرایش','sectionedit','edit',`data-section="${key}"`,'true'))+
 `<div class="notice">این داده‌ها متعلق به خود DARK هستند. ذخیره در دیتابیس با اعمال موفق روی Xray متفاوت است؛ وضعیت هسته را بررسی کن.</div><article class="panel">${jsonBox(data.value)}</article>`;
}
async function renderPage(){
 const requestedPage=state.page,seq=++state.renderSeq;
 let html;
 try{
  if(enginePages[requestedPage])html=await enginePage();
  else switch(requestedPage){
   case'inbounds':html=inboundPage();break;
   case'clients':html=clientsPage();break;
   case'resellers':html=resellerPage();break;
   case'ipguard':html=await ipPage();break;
   case'finance':html=await financePage();break;
   case'audit':html=await auditPage();break;
   case'sync':html=syncPage();break;
   case'account':html=await accountPage();break;
   default:html=dashboard();
  }
 }catch(ex){
  html=heading('دریافت اطلاعات ناموفق','این صفحه بدون پاسخ معتبر، دادهٔ ساختگی نشان نمی‌دهد.')+`<div class="notice error">${e(ex.message)}</div>`;
 }
 if(seq!==state.renderSeq||requestedPage!==state.page)return;
 const content=$('#content');if(!content)return;
 const support=state.me?.ui?.support_url||'';
 content.innerHTML=html+`<footer><span>DARK API · DARK DATABASE · Xray-core${support?` · <a href="${e(support)}" target="_blank" rel="noopener noreferrer">Support</a>`:''}</span><span class="mono">${e(state.me?.version||'DARK')} </span></footer>`;
}
async function go(page){state.page=page;state.search='';state.selected.clear();shell();await renderPage();}
function closeDialog(){const o=$('#overlay');o.classList.remove('show');o.style.display='none';o.innerHTML='';}
function dialog(title,body,onSubmit=null,label='ذخیره'){const o=$('#overlay');o.innerHTML=`<div class="dialog" role="dialog" aria-modal="true" aria-label="${e(title)}"><form id="dialog-form"><header class="dialog-head"><h2>${e(title)}</h2><button type="button" class="icon-btn" data-act="close">${icon('close')}</button></header><div class="dialog-body">${body}<div class="form-error" id="form-error"></div></div><footer class="dialog-foot"><button type="button" class="btn" data-act="close">بستن</button>${onSubmit?`<button class="btn btn-primary" type="submit" id="submit-dialog">${e(label)}</button>`:''}</footer></form></div>`;o.style.display='flex';o.classList.add('show');if(onSubmit)$('#dialog-form').addEventListener('submit',async ev=>{ev.preventDefault();const b=$('#submit-dialog');b.disabled=true;$('#form-error').textContent='';try{await onSubmit(new FormData(ev.target),ev.target);}catch(ex){if($('#form-error'))$('#form-error').textContent=ex.message;else toast(ex.message,true);}finally{if(b.isConnected)b.disabled=false;}});setTimeout(()=>o.querySelector('input,select,button')?.focus(),20);}
function field(label,name,value='',type='text',attrs=''){return `<label>${label}<input class="field-input" name="${name}" type="${type}" value="${e(value)}" ${attrs}></label>`;}
const select=(label,name,options,value)=>`<label>${label}<select name="${name}">${options.map(([v,l])=>`<option value="${e(v)}" ${String(v)===String(value)?'selected':''}>${e(l)}</option>`).join('')}</select></label>`;
function num(f,key){let n=Number(f.get(key));if(!Number.isFinite(n))throw Error('عدد نامعتبر: '+key);return n;}
function inputIds(f){return f.getAll('inbound').map(Number);}
function selection(ids,allowed){const customerProtocols=new Set(['vless','vmess','trojan','shadowsocks','socks','http']);return `<div class="check-list">${state.inbounds.filter(i=>(!allowed||allowed.includes(i.id))&&(customerProtocols.has(i.protocol)||ids.includes(i.id))).map(i=>`<label><input name="inbound" type="checkbox" value="${i.id}" ${ids.includes(i.id)?'checked':''}><span>${e(i.remark||i.tag)} <span class="mono">:${i.port} · ${e(i.protocol)}${customerProtocols.has(i.protocol)?'':' · NOT FOR CLIENTS'}</span></span></label>`).join('')}</div>`;}
async function clientForm(email=null,inbound=null){let detail=email?await api('/api/clients/'+enc(email)):null,c=detail?.client||{},owner=detail?.owner||state.me.id,ids=detail?.inboundIds||(inbound?[Number(inbound)]:[]);let expiration=c.expiryTime>0?new Date(c.expiryTime).toISOString().slice(0,16):'',body=`<div class="form-grid">${field('نام / شناسهٔ مشتری','email',email||'','text',email?'readonly':'required maxlength="128" dir="ltr"')}${select('مالک مشتری','owner',state.owners.map(o=>[o.id,o.name+' — '+o.id]),owner)}${field('حجم (GiB) · صفر نامحدود','totalGB',(c.totalGB||0)/gb,'number','min="0" max="8388607" step="0.01" required')}${field('انقضا (زمان واردشده UTC)','expiry',expiration,'datetime-local')}${field('حداکثر IP · صفر نامحدود','limitIp',c.limitIp??1,'number','min="0" max="1000" required')}${field('حداکثر HWID · صفر بدون محدودیت','limitHwid',c.limitHwid??0,'number','min="0" max="1000" required')}${select('وضعیت دستی','enable',[['true','فعال'],['false','قطع دستی']],String(c.enable!==false))}${select('Flow (برای VLESS سازگار)','flow',[['','بدون Flow'],['xtls-rprx-vision','xtls-rprx-vision'],['xtls-rprx-vision-udp443','xtls-rprx-vision-udp443']],c.flow||'')}${field('شناسه تلگرام','tgId',c.tgId||0,'number','min="0" step="1"')}${select('Traffic reset schedule','resetMode',[['never','Never'],['hourly','Hourly'],['daily','Daily'],['weekly','Weekly'],['monthly','Monthly'],['interval','Custom interval']],(c.resetTraffic&&c.resetTraffic!=='never')?c.resetTraffic:(c.reset>0?'interval':'never'))}${field('Custom reset interval (days)','resetDays',c.reset||0,'number','min="0" max="3650"')}${field('Monthly reset day (1-31)','resetTrafficDay',c.resetTrafficDay||0,'number','min="0" max="31"')}${field('Maximum resets · 0 unlimited','resetCount',c.resetCount||0,'number','min="0" max="100000"')}${field('گروه','group',c.group||'')}${field('یادداشت','comment',c.comment||'')}<div class="span-2"><label>اینباندهای مشتری</label><div id="inbound-select">${selection(ids,state.owners.find(o=>o.id===owner)?.allowed||[])}</div></div><div class="span-2 notice">شناسه و رمز خالی در ساخت جدید توسط سرور تولید می‌شوند. هنگام ویرایش فقط فیلدهایی که در اختیار تو هستند تغییر می‌کنند؛ اطلاعات پنهان پاک نمی‌شود.</div><div class="span-2" id="secret-fields"></div></div>`;
 dialog(email?'ویرایش '+email:'افزودن مشتری',body,async f=>{let resetMode=f.get('resetMode'),resetDays=num(f,'resetDays'),resetDay=num(f,'resetTrafficDay');if(resetMode==='interval'&&resetDays<1)throw Error('Custom reset interval requires at least 1 day.');if(resetMode==='monthly'&&(resetDay<1||resetDay>31))throw Error('Monthly reset requires a day from 1 to 31.');let payload={limitIp:num(f,'limitIp'),limitHwid:num(f,'limitHwid'),totalGB:Math.round(num(f,'totalGB')*gb),enable:f.get('enable')==='true',flow:f.get('flow'),tgId:num(f,'tgId'),reset:resetMode==='interval'?resetDays:0,resetTraffic:['hourly','daily','weekly','monthly'].includes(resetMode)?resetMode:'never',resetTrafficDay:resetMode==='monthly'?resetDay:0,resetCount:num(f,'resetCount'),group:f.get('group'),comment:f.get('comment')};if(f.get('expiry'))payload.expiryTime=new Date(f.get('expiry')+'Z').getTime();else if(!email||c.expiryTime>=0)payload.expiryTime=0;for(let k of ['id','password','auth'])if(f.has(k)&&f.get(k))payload[k]=f.get(k);let result;if(email){result=await api('/api/clients/'+enc(email),'PATCH',{client:payload,inboundIds:inputIds(f)});}else{payload.email=f.get('email').trim();result=await api('/api/clients','POST',{owner:f.get('owner'),client:payload,inboundIds:inputIds(f)});}closeDialog();toast(result.state==='applied'?'در دیتابیس DARK ذخیره شد؛ وضعیت اجرای هسته در جدول جداست.':'درخواست ثبت شد: '+(labelState[result.state]||result.state),result.state!=='applied');await refresh();});
 const ownerSelect=$('#dialog-form select[name="owner"]');if(email)ownerSelect.disabled=true;ownerSelect.addEventListener('change',()=>{$('#inbound-select').innerHTML=selection([],state.owners.find(o=>o.id===ownerSelect.value)?.allowed||[]);secretsForm();});
 function secretsForm(){for(const key of ['id','password','auth']){const el=$('#secret-fields [name="'+key+'"]');if(el)c[key]=el.value;}let checked=$$('#dialog-form input[name="inbound"]:checked').map(i=>Number(i.value)),protocols=state.inbounds.filter(i=>checked.includes(i.id)).map(i=>i.protocol);let allowed=!email||can('clients.credentials',owner);$('#secret-fields').innerHTML=allowed?`<div class="form-grid">${protocols.some(p=>['vless','vmess'].includes(p))?field('UUID (VLESS / VMess)','id',c.id||'','text','dir="ltr"'):''}${protocols.some(p=>['trojan','shadowsocks'].includes(p))?field('Password (Trojan / Shadowsocks)','password',c.password||'','password','autocomplete="new-password"'):''}${protocols.some(p=>['hysteria','hysteria2'].includes(p))?field('Auth (Hysteria2)','auth',c.auth||'','password','autocomplete="new-password"'):''}</div>`:'';}
 $('#inbound-select').addEventListener('change',secretsForm);secretsForm();}
async function ownerForm(id=null){
 const o=id?(state.resellers||[]).find(x=>x.id===id)||{}:{};
 dialog(id?'مدیریت نماینده '+id:'نماینده جدید',`<div class="form-grid">
   ${field('شناسه نماینده','id',id||'','text',id?'readonly':'required pattern="[a-zA-Z0-9_.@+-]+" dir="ltr"')}
   ${field('نام نمایشی','name',o.name||'','text','required maxlength="128"')}
   ${field(id?'رمز جدید (خالی = بدون تغییر)':'رمز ورود (حداقل ۸ کاراکتر)','password','','password',id?'minlength="8" autocomplete="new-password"':'required minlength="8" autocomplete="new-password"')}
   ${select('وضعیت نماینده','enabled',[['true','فعال'],['false','غیرفعال']],String(id?!!o.enabled:true))}
   ${field('Volume Credit کل (GiB)','volume_credit',(o.volume_credit_bytes||0)/gb,'number','min="0" step="0.01" required')}
   ${field('Unlimited Credit کل','unlimited_credit',o.unlimited_credit||0,'number','min="0" max="1000000" step="1" required')}
   ${field('سقف تعداد کاربران · صفر نامحدود','max_clients',o.max_clients||0,'number','min="0" max="1000000"')}
   ${field('Prefix اجباری مشتری · خالی = آزاد','prefix',o.prefix||'','text','maxlength="64" dir="ltr" pattern="[A-Za-z0-9_.@+\\-]*"')}
   ${field('بیشترین IP هر مشتری · صفر آزاد','max_client_ips',o.max_client_ips||0,'number','min="0" max="1000"')}
   ${field('بیشترین HWID هر مشتری · صفر آزاد','max_client_hwid',o.max_client_hwid||0,'number','min="0" max="1000"')}
   <div class="span-2"><label>اینباندهای مجاز</label>${selection(o.allowed||[])}</div>
   <div class="span-2 notice">نماینده Role یا Permission قابل انتخاب ندارد؛ سطح دسترسی نماینده ثابت و محدود به منابع خودش است. اعتبار پولی در DARK وجود ندارد. مشتری حجمی به اندازه حجم تعریف‌شده از Volume Credit رزرو می‌کند؛ مشتری نامحدود یک واحد Unlimited Credit رزرو می‌کند. غیرفعال‌کردن مشتری رزرو را آزاد نمی‌کند؛ حذف یا تغییر پلن آن را آزاد می‌کند. کاهش اعتبار پایین‌تر از رزرو فعلی رد می‌شود.</div>
 </div>`,async f=>{
   const rid=f.get('id');
   const body={name:f.get('name'),enabled:f.get('enabled')==='true',allowed:inputIds(f),
     volume_credit_bytes:Math.round(num(f,'volume_credit')*gb),unlimited_credit:num(f,'unlimited_credit'),
     max_clients:num(f,'max_clients'),prefix:String(f.get('prefix')||'').trim(),
     max_client_ips:num(f,'max_client_ips'),max_client_hwid:num(f,'max_client_hwid')};
   if(f.get('password'))body.password=f.get('password');
   await api('/api/resellers/'+enc(rid),'PUT',body);
   closeDialog();toast('نماینده و اعتبارهای فروش ذخیره شدند.');await refresh();
 });
}
async function ipsDialog(id,tab='ips'){const data=await api('/api/clients/'+enc(id)+'/'+tab);dialog((tab==='ips'?'IPهای ثبت‌شده: ':'دستگاه‌های اشتراک: ')+id,`<div class="row-actions">${button('IPها','ips','globe',`data-id="${e(id)}"`)}${button('HWID','devices','lock',`data-id="${e(id)}"`)}${button(tab==='ips'?'پاک‌کردن تاریخچه (نه رفع بن)':'پاک‌کردن دستگاه‌ها',tab==='ips'?'clearips':'cleardevices','trash',`data-id="${e(id)}"`)}</div>${jsonBox(data)}<div class="notice">این پاسخ از دیتابیس و لاگ محلی DARK دریافت شده است.</div>`);}
async function showLinks(id){let result=await api('/api/clients/'+enc(id)+'/links');dialog('اشتراک و لینک: '+id,`${result.subscription_url?`<label>اشتراک کنترل‌شده توسط DARK</label><pre class="json-box key-result">${e(result.subscription_url)}</pre><div id="qr-box" style="max-width:230px;margin:15px auto"></div>`:''}<label>خروجی ساخته‌شده توسط DARK</label>${jsonBox(result.engine)}<div class="notice warning">این لینک‌ها حاوی اعتبارنامه مشتری هستند. این لینک‌ها همین‌جا ساخته شده‌اند. وضعیت اجرای هسته را جداگانه بررسی کن.</div>`);if(result.subscription_url){const q=qrcode(0,'L');q.addData(result.subscription_url);q.make();$('#qr-box').innerHTML=q.createSvgTag();}}
async function adoptForm(){let rows=await api('/api/unmanaged');dialog('تخصیص صریح مشتری موجود',`<div class="notice warning">مشتری حذف یا دوباره ساخته نمی‌شود. مصرف فعلی فقط به‌عنوان مبنای آمار ثبت می‌شود؛ اعتبار نماینده بر اساس حجم پلن یا اسلات نامحدود رزرو می‌شود و به مصرف واقعی وابسته نیست.</div><div class="form-grid">${select('مشتری فعلی','email',rows.map(x=>[x.email,x.email]),'')}${select('مالک','owner',state.owners.map(x=>[x.id,x.name]),state.me.id)}</div>`,async f=>{await api('/api/adopt','POST',{email:f.get('email'),owner:f.get('owner')});closeDialog();toast('مالکیت ثبت شد.');await refresh();});}
async function confirmAction(id,action){if(!confirm(`${{delete:'حذف مشتری (دفتر مصرف حفظ می‌شود)',reset:'ریست مصرف مشتری (مصرف نماینده کم نمی‌شود)',enable:'فعال‌کردن مشتری با حفظ سایر محدودیت‌ها',disable:'قطع دستی مشتری'}[action]}\n${id}\nتأیید می‌کنی؟`))return;const result=await api('/api/clients/'+enc(id)+'/action','POST',{action});toast('نتیجه: '+(labelState[result.state]||result.state));await refresh();}
async function runAction(act,el){const id=el?.dataset.id;switch(act){case'inboundnew':await inboundForm();return;case'inboundedit':await inboundForm(+id);return;case'inbounddelete':if(confirm('اینباند حذف شود؟ در صورت داشتن مشتری یا هاست، درخواست رد می‌شود.')){await api('/api/inbounds/'+id,'DELETE');await refresh();}return;case'sectionedit':await sectionForm(el.dataset.section);return;case'corevalidate':case'corestart':case'corestop':{if(act!=='corevalidate'&&!confirm('این عملیات روی هستهٔ مستقل اجرا می‌شود و ممکن است اتصال‌ها قطع شوند. ادامه؟'))return;let result=await api('/api/core/'+({corevalidate:'validate',corestart:'start',corestop:'stop'}[act]),'POST',{});toast('نتیجه از سرویس محلی دریافت شد.');await refresh();return;}case'xkey':{const k=await api('/api/keys/x25519','POST',{});document.querySelector('[name=privateKey]').value=k.privateKey;document.querySelector('[name=shortId]').value=k.shortId;toast('جفت‌کلید معتبر X25519 ساخته شد.');return;}case'itab':{document.querySelectorAll('[data-isection]').forEach(x=>x.hidden=x.dataset.isection!==el.dataset.tab);return;}case'close':closeDialog();return;case'menu':$('.sidebar')?.classList.toggle('open');return;case'refresh':await refresh();return;case'logout':await api('/api/auth/logout','POST',{});state.me=null;closeDialog();loginPage();return;case'allclients':await go('clients');return;case'engineinbounds':await inboundForm();return;case'expand':state.expanded.has(+id)?state.expanded.delete(+id):state.expanded.add(+id);await renderPage();return;case'new':await clientForm(null,el.dataset.inbound);return;case'edit':await clientForm(id);return;case'ownernew':await ownerForm();return;case'owneredit':await ownerForm(id);return;case'ownerdelete':if(confirm('نماینده حذف شود؟ فقط وقتی هیچ مشتری فعالی نداشته باشد حذف می‌شود و تاریخچه مصرف/اعتبار پاک نمی‌شود.')){await api('/api/resellers/'+enc(id),'DELETE');toast('نماینده حذف شد.');await refresh();}return;case'links':await showLinks(id);return;case'ips':await ipsDialog(id);return;case'devices':await ipsDialog(id,'devices');return;case'adopt':await adoptForm();return;case'delete':case'reset':await confirmAction(id,act);return;case'toggle':{const c=await api('/api/clients/'+enc(id));await confirmAction(id,c.client.enable===false?'enable':'disable');return;}case'clearips':case'cleardevices':if(confirm(act==='clearips'?'فقط تاریخچهٔ IP پاک شود؟ رفع مسدودی فایروال انجام نمی‌شود.':'ثبت دستگاه‌های این مشتری پاک شود؟')){await api('/api/clients/'+enc(id)+(act==='clearips'?'/ips':'/devices'),'DELETE');await ipsDialog(id,act==='clearips'?'ips':'devices');}return;case'syncnow':await api('/api/sync','POST',{});toast('دور همگام‌سازی اجرا شد.');await refresh();return;case'period':if(confirm('دورهٔ جدید آمار مصرف آغاز شود؟ این کار هیچ Volume/Unlimited Credit را شارژ یا کم نمی‌کند و سوابق قبلی حذف نمی‌شوند.')){await api('/api/owners/'+enc(id)+'/reset-period','POST',{});await refresh();}return;
case'resourcecredit':{const rep=(state.resellers||[]).find(x=>x.id===id)||{};dialog('تنظیم اعتبار نماینده: '+id,`<div class="form-grid">${field('تغییر Volume Credit (GiB)','volume_delta',0,'number','step="0.01" required')}${field('تغییر Unlimited Credit','unlimited_delta',0,'number','step="1" min="-1000000" max="1000000" required')}<div class="span-2 notice">عدد مثبت شارژ و عدد منفی کسر می‌کند. وضعیت فعلی: Volume ${bytes(rep.volume_credit_remaining_bytes??0)} باقی‌مانده از ${bytes(rep.volume_credit_bytes??0)} · Unlimited ${fa(rep.unlimited_credit_remaining??0)} باقی‌مانده از ${fa(rep.unlimited_credit??0)}. کاهش پایین‌تر از رزرو مشتری‌های فعلی رد می‌شود.</div></div>`,async f=>{const volume_bytes=Math.round(Number(f.get('volume_delta')||0)*gb),unlimited_units=num(f,'unlimited_delta');if(!volume_bytes&&!unlimited_units)throw Error('حداقل یکی از اعتبارها باید تغییر کند.');await api('/api/resellers/'+enc(id)+'/credits','POST',{volume_bytes,unlimited_units,event_id:crypto.randomUUID()});closeDialog();toast('اعتبار نماینده ثبت شد.');await refresh();});return;}
case'bulk':if(!state.selected.size){toast('ابتدا مشتری‌ها را انتخاب کن.',true);return;}dialog('عملیات روی '+fa(state.selected.size)+' مشتری',select('عملیات','action',[['disable','قطع دستی'],['enable','فعال‌سازی'],['reset','ریست مصرف'],['delete','حذف']],'disable'),async f=>{if(!confirm('عملیات روی همهٔ مشتری‌های انتخاب‌شده انجام شود؟'))return;const out=await api('/api/clients/bulk','POST',{emails:[...state.selected],action:f.get('action')});state.selected.clear();dialog('نتیجهٔ هر مشتری',jsonBox(out));await refresh();});return;
case'password':dialog('تغییر رمز DARK',`<div class="form-grid">${field('رمز فعلی','old_password','','password','required')}${field('رمز جدید','new_password','','password','required minlength="8"')}</div>`,async f=>{await api('/api/auth/password','POST',{old_password:f.get('old_password'),new_password:f.get('new_password')});closeDialog();state.me=null;loginPage();toast('رمز تغییر کرد. دوباره وارد شو.');});return;
case'mfasetup':dialog('راه‌اندازی TOTP',field('رمز فعلی DARK','password','','password','required'),async f=>{let r=await api('/api/auth/totp/setup','POST',{password:f.get('password')});dialog('ثبت در برنامهٔ Authenticator',`<pre class="json-box key-result">${e(r.secret)}</pre><div id="qr-box" style="max-width:240px;margin:12px auto"></div>${field('کد شش‌رقمی','code','','text','required inputmode="numeric" autocomplete="one-time-code"')}`,async f2=>{let v=await api('/api/auth/totp/enable','POST',{code:f2.get('code')});dialog('کدهای بازیابی — همین حالا امن نگهداری کن',`<div class="notice warning">نشست‌ها باطل شدند. هر کد یک‌بار مصرف است. پس از ذخیره، صفحه را بازخوانی کن و با TOTP وارد شو.</div>${jsonBox(v.recovery_codes)}`);state.me=null;});let q=qrcode(0,'L');q.addData(r.uri);q.make();$('#qr-box').innerHTML=q.createSvgTag();});return;
case'mfadisable':dialog('غیرفعال‌سازی TOTP',`<div class="form-grid">${field('رمز فعلی','password','','password','required')}${field('کد TOTP یا بازیابی','code','','text','required')}</div>`,async f=>{await api('/api/auth/totp/disable','POST',{password:f.get('password'),code:f.get('code')});closeDialog();state.me=null;loginPage();});return;
case'keynew':dialog('کلید API مستقل',`<div class="form-grid">${field('نام کلید','name','','text','required')}${field('اعتبار (روز)','days',30,'number','min="1" max="365" required')}<div class="span-2 notice">کلید با مجوزهای خواندن/مدیریت مشتریان خود ساخته می‌شود. برای مجوزهای متفاوت از API صریح استفاده کن؛ کلید به ویرایشگر مالک دسترسی ندارد.</div></div>`,async f=>{let p={};for(let k of ['clients.read','clients.create','clients.edit','clients.delete','clients.credentials','clients.ip','inbounds.read','owners.read'])if(can(k))p[k]='own';let r=await api('/api/keys','POST',{name:f.get('name'),days:num(f,'days'),permissions:p});dialog('کلید فقط همین بار نمایش داده می‌شود',`<pre class="json-box key-result">${e(r.key)}</pre><div class="notice">کلید را امن نگهداری کن؛ در فهرست دوباره قابل مشاهده نیست.</div>`);});return;
case'resolvereset':if(confirm('وضعیت فعلی Xray محلی پذیرفته شود؟ ریست دوباره اجرا نمی‌شود و مصرف تاریخی برنمی‌گردد.')){await api('/api/clients/'+enc(id)+'/resolve-reset','POST',{confirmation:id});await refresh();}return;
case'sessiondelete':if(confirm('این نشست فعال باطل شود؟')){await api('/api/auth/sessions/'+enc(id),'DELETE');toast('نشست باطل شد.');await renderPage();}return;
case'sessionsothers':if(confirm('از تمام نشست‌های دیگر این حساب خارج شود؟')){let r=await api('/api/auth/sessions/revoke-others','POST',{});toast(`${r.revoked_others} نشست دیگر باطل شد.`);await renderPage();}return;
case'keydelete':if(confirm('این کلید باطل شود؟')){await api('/api/keys/'+enc(id),'DELETE');await renderPage();}return;
}}
document.addEventListener('click',async ev=>{let el=ev.target.closest('[data-page],[data-act]');if(!el)return;try{if(el.dataset.page){await go(el.dataset.page);return;}await runAction(el.dataset.act,el);}catch(ex){toast(ex.message,true);}});
document.addEventListener('change',ev=>{if(ev.target.dataset.select){ev.target.checked?state.selected.add(ev.target.dataset.select):state.selected.delete(ev.target.dataset.select);}});
let searchTimer;document.addEventListener('input',ev=>{if(ev.target.id==='search'){state.search=ev.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{const p=ev.target.selectionStart;await renderPage();$('#search')?.focus();try{$('#search')?.setSelectionRange(p,p);}catch{}},250);}});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape')closeDialog();});
function loginPage(){state.clients=[];state.owners=[];state.resellers=[];state.inbounds=[];state.errors={};$('#app').innerHTML=`<div class="login-wrap"><article class="panel login-card">${brand()}<div class="login-caption">INDEPENDENT OPERATIONS CONSOLE</div><h1>ورود به مرکز کنترل DARK</h1><p class="login-note">این صفحه به سرویس و دیتابیس متصل است. حساب پیش‌فرض یا ورود نمایشی ندارد.</p><form id="login-form">${field('نام کاربری','username','','text','required autocomplete="username" dir="ltr"')}${field('رمز عبور','password','','password','required autocomplete="current-password"')}${field('کد TOTP یا بازیابی (در صورت فعال‌بودن)','otp','','text','autocomplete="one-time-code" dir="ltr"')}<div class="form-error" id="login-error"></div><button type="submit" class="btn btn-primary">${icon('lock')}ورود امن</button></form><p class="login-note">یک پنل، یک ورود و یک دیتابیس؛ هیچ پنل دیگری نصب نمی‌شود. هستهٔ محلی Xray را از همین پروژه مدیریت می‌کنی.</p></article></div>`;$('#login-form').addEventListener('submit',async ev=>{ev.preventDefault();let form=ev.target,b=form.querySelector('button[type="submit"]');b.disabled=true;try{let f=new FormData(form);await api('/api/auth/login','POST',{username:f.get('username'),password:f.get('password'),otp:f.get('otp')});state.me=await api('/api/me');if(!localStorage.getItem('dark_lang'))localStorage.setItem('dark_lang',state.me.ui?.language||'en');state.page='dashboard';shell();await refresh();}catch(ex){if($('#login-error'))$('#login-error').textContent=ex.message;}finally{if(b.isConnected)b.disabled=false;}});}
(async()=>{try{state.me=await api('/api/me');if(!localStorage.getItem('dark_lang'))localStorage.setItem('dark_lang',state.me.ui?.language||'en');shell();await refresh();}catch{loginPage();}})();
setInterval(()=>{if(state.me&&!document.hidden&&!$('#overlay').classList.contains('show')&&!enginePages[state.page])refresh();},12000);

function area(label,name,value,rows=7){return `<label class="span-2">${e(label)}<textarea class="field-input" dir="ltr" style="font-family:monospace;min-height:${rows*21}px" name="${e(name)}">${e(JSON.stringify(value,null,2))}</textarea></label>`;}
async function sectionForm(section){
 const data=await api('/api/settings/'+section);let sample='';
 if(section==='hosts')sample='Public Endpoint از ویرایشگر Guided مدیریت می‌شود؛ آدرس، پورت، SNI و Transport override مستقیماً روی لینک مشتری اثر دارند.';
 if(section==='outbounds')sample='هر خروجی باید tag یکتا و protocol داشته باشد. قواعد وابسته مانع حذف خروجی می‌شوند.';
 if(section==='routing')sample='قواعد باید یکی از outboundTag یا balancerTag داشته باشند. ترتیب آرایهٔ rules حفظ می‌شود.';
 dialog('تنظیمات مستقل '+section,`<div class="notice">${e(sample||'پیکربندی این بخش مستقیماً در دیتابیس DARK ذخیره می‌شود.')}<br>فرم سادهٔ بومی برای همهٔ جزئیات این بخش هنوز تکمیل نشده؛ فعلاً ویرایشگر JSON خود DARK است.</div>${area('JSON','value',data.value,17)}`,
 async f=>{let value;try{value=JSON.parse(f.get('value'));}catch{throw Error('JSON معتبر نیست.');}await api('/api/settings/'+section,'PUT',{value});closeDialog();toast('ذخیره شد؛ وضعیت اعمال هسته را بررسی کن.');await refresh();});
}
async function inboundForm(id=null){
 const r=id?await api('/api/inbounds/'+id):{remark:'DARK INBOUND',protocol:'vless',listen:'0.0.0.0',port:2020,enable:true,settings:{decryption:'none'},streamSettings:{network:'tcp',security:'none'},sniffing:{enabled:true,destOverride:['http','tls'],routeOnly:true}};
 const st=r.streamSettings||{},sec=st.realitySettings||st.tlsSettings||{},transport=st[st.network+'Settings']||{};
 const tabs=[['general','عمومی'],['transport','انتقال'],['security','TLS / REALITY'],['advanced','پیشرفته']];
 dialog(id?'ویرایش اینباند '+r.remark:'اینباند مستقل جدید',`<div class="row-actions">${tabs.map(([k,l])=>button(l,'itab','settings',`data-tab="${k}"`)).join('')}</div>
 <div class="notice">این فرم متعلق به DARK است. کاربران و مالکیتشان از بخش کاربران مدیریت می‌شوند؛ قرار دادن clients در JSON اینباند مجاز نیست.</div>
 <section data-isection="general"><div class="form-grid">${field('نام اینباند','remark',r.remark,'text','required maxlength="200"')}${select('پروتکل','protocol',['vless','vmess','trojan','shadowsocks','socks','http','dokodemo-door','tunnel'].map(x=>[x,x]),r.protocol)}${field('Listen IP','listen',r.listen,'text','required dir="ltr"')}${field('پورت','port',r.port,'number','required min="1" max="65535"')}${field('Tag (خالی = ساخت خودکار)','tag',r.tag||'','text','dir="ltr"')}${select('وضعیت','enable',[['true','فعال'],['false','غیرفعال']],String(r.enable))}</div></section>
 <section data-isection="transport" hidden><div class="form-grid">${select('انتقال','network',['tcp','ws','grpc','httpupgrade','xhttp','kcp'].map(x=>[x,x]),st.network||'tcp')}${field('gRPC serviceName','serviceName',st.grpcSettings?.serviceName||'','text','dir="ltr"')}${field('Path (WS / XHTTP / HTTPUpgrade)','path',transport.path||'/','text','dir="ltr"')}${field('Host','host',transport.host||transport.headers?.Host||'','text','dir="ltr"')}${field('gRPC authority','grpcAuthority',st.grpcSettings?.authority||'','text','dir="ltr"')}${field('XHTTP padding','padding',st.xhttpSettings?.xPaddingBytes||'100-1000')}${field('mKCP MTU','mtu',st.kcpSettings?.mtu||1350,'number','min="576" max="1460"')}${field('mKCP TTI','tti',st.kcpSettings?.tti||50,'number','min="10" max="5000"')}${select('XHTTP mode','xhttpmode',['auto','packet-up','stream-up','stream-one'].map(x=>[x,x]),st.xhttpSettings?.mode||'auto')}</div></section>
 <section data-isection="security" hidden><div class="form-grid">${select('امنیت','security',['none','tls','reality'].map(x=>[x,x]),st.security||'none')}${field('SNI / serverNames','sni',sec.serverName||(sec.serverNames||[]).join(','),'text','dir="ltr"')}${field('REALITY target','target',sec.target||sec.dest||'','text','dir="ltr" placeholder="example.com:443"')}${field('REALITY privateKey','privateKey',sec.privateKey||'','password','autocomplete="off" dir="ltr"')}${field('Short ID','shortId',(sec.shortIds||[]).join(','),'text','dir="ltr"')}${field('TLS certificateFile','cert',sec.certificates?.[0]?.certificateFile||'','text','dir="ltr"')}${field('TLS keyFile','key',sec.certificates?.[0]?.keyFile||'','text','dir="ltr"')}<div class="span-2">${button('ساخت کلید X25519','xkey','lock')}</div></div></section>
 <section data-isection="advanced" hidden><div class="form-grid">${area('Protocol settings — بدون clients','settings',r.settings||{})}${area('Sniffing','sniffing',r.sniffing||{})}${area('Stream settings تکمیلی — فیلدهای فرم اولویت دارند','stream',st)}</div></section>`,async f=>{
 let settings,sniffing,stream;try{settings=JSON.parse(f.get('settings'));sniffing=JSON.parse(f.get('sniffing'));stream=JSON.parse(f.get('stream'));}catch{throw Error('JSON معتبر نیست.');}
 const net=f.get('network'),security=f.get('security'),protocol=f.get('protocol');stream.network=net;stream.security=security;
 if(net==='grpc')stream.grpcSettings={...(stream.grpcSettings||{}),serviceName:f.get('serviceName'),authority:f.get('grpcAuthority')||''};
 if(['ws','httpupgrade','xhttp'].includes(net)){
  const key=net+'Settings';stream[key]={...(stream[key]||{}),path:f.get('path')||'/'};
  if(net==='ws')stream[key].headers={...(stream[key].headers||{}),Host:f.get('host')};else stream[key].host=f.get('host');
  if(net==='xhttp'){stream[key].mode=f.get('xhttpmode');stream[key].xPaddingBytes=f.get('padding');}
 }
 if(security==='reality'){
  if(!f.get('privateKey')||!f.get('target')||!f.get('sni'))throw Error('کلید، مقصد و SNI در REALITY لازم‌اند.');
  stream.realitySettings={...(stream.realitySettings||{}),show:false,target:f.get('target'),serverNames:f.get('sni').split(',').map(x=>x.trim()).filter(Boolean),privateKey:f.get('privateKey'),shortIds:f.get('shortId').split(',').map(x=>x.trim())};
 }else if(security==='tls'){
  if(!f.get('cert')||!f.get('key'))throw Error('مسیر فایل گواهی و کلید TLS لازم است.');
  stream.tlsSettings={...(stream.tlsSettings||{}),serverName:f.get('sni'),certificates:[{certificateFile:f.get('cert'),keyFile:f.get('key')}]};
 }
 if(protocol==='vless')settings.decryption=settings.decryption||'none';
 if(protocol==='shadowsocks')settings.method=settings.method||'aes-128-gcm';
 if(net==='kcp')stream.kcpSettings={...(stream.kcpSettings||{}),mtu:num(f,'mtu'),tti:num(f,'tti')};
 const body={remark:f.get('remark'),protocol,listen:f.get('listen'),port:num(f,'port'),enable:f.get('enable')==='true',settings,streamSettings:stream,sniffing};
 if(f.get('tag'))body.tag=f.get('tag');
 await api('/api/inbounds'+(id?'/'+id:''),id?'PUT':'POST',body);closeDialog();toast('اینباند در DARK ذخیره شد. وضعیت هسته را بررسی کن.');await refresh();});
}
