/* DARK XRAY Nodes V2 — real HTTPS node registry and dedicated agent tokens. */
(function(){
'use strict';
if(typeof enginePage!=='function'||typeof runAction!=='function')return;
const baseEnginePage=enginePage,baseRunAction=runAction;
const L=(en,fa)=>((localStorage.getItem('dark_lang')||'en')==='fa'?fa:en);
state.nv2={nodes:[],tokens:[]};
async function loadNodes(){const [nodes,tokens]=await Promise.all([api('/api/nodes'),api('/api/node-agent/tokens')]);state.nv2={nodes,tokens};return state.nv2;}
function healthMetric(label,value){return `<div><small>${e(label)}</small><b>${e(value??'—')}</b></div>`;}
function assignedNames(n){return (n.inboundIds||[]).map(id=>{let ib=state.inbounds.find(x=>x.id===id);return ib?(ib.remark||ib.tag):'#'+id;});}
function nodeCard(n){
 const h=n.health||{},core=h.core||{},status=!n.enabled?'disabled':n.online?'online':n.last_error?'error':'offline',assigned=assignedNames(n);
 const syncErrors=(n.assignments||[]).filter(x=>x.last_error);
 const remote=n.enabled?`${button(L('Probe','پروب'),'nv2probe','activity',`data-id="${e(n.id)}"`)}${button(L('Sync assigned','همگام‌سازی'),'nv2sync','refresh',`data-id="${e(n.id)}"`,true)}${button(L('Remote inbounds','اینباندهای نود'),'nv2inbounds','server',`data-id="${e(n.id)}"`)}${button(L('Validate','اعتبارسنجی'),'nv2core','check',`data-id="${e(n.id)}" data-core="validate"`)}${button(L('Restart Xray','ری‌استارت Xray'),'nv2core','refresh',`data-id="${e(n.id)}" data-core="restart"`)}`:'';
 return `<article class="panel nv2-node"><div class="nv2-head"><div><h3>${e(n.name)}</h3><small>${e(n.id)} · ${e(n.origin)}</small></div><div class="nv2-status ${status}"><i></i><b>${e(status)}</b></div></div><div class="nv2-assigned"><span>${L('ASSIGNED INBOUNDS','اینباندهای این نود')}</span><div>${assigned.length?assigned.map(x=>`<i>${e(x)}</i>`).join(''):`<small>${L('No inbound assigned','اینباندی انتخاب نشده')}</small>`}</div></div><div class="nv2-metrics">${healthMetric('Latency',n.last_latency_ms?`${n.last_latency_ms} ms`:'—')}${healthMetric('Xray',core.state||'—')}${healthMetric(L('Assigned','اختصاص‌یافته'),assigned.length)}${healthMetric(L('Remote total','کل روی نود'),h.inbounds??'—')}${healthMetric(L('Last seen','آخرین مشاهده'),n.last_seen?date(n.last_seen):'—')}</div>${n.last_error?`<div class="nv2-error">${e(n.last_error)}</div>`:''}${syncErrors.length?`<div class="nv2-error">${e(syncErrors.map(x=>'#'+x.local_inbound_id+': '+x.last_error).join(' · '))}</div>`:''}${!n.enabled?`<div class="notice warning">${L('This node is disabled. Enable it from Edit before remote operations.','این نود غیرفعال است. قبل از عملیات راه‌دور از بخش ویرایش فعالش کن.')}</div>`:''}<div class="nv2-actions">${remote}${button(L('Edit assignment','ویرایش نود'),'nv2edit','edit',`data-id="${e(n.id)}"`)}${button(L('Delete','حذف'),'nv2delete','trash',`data-id="${e(n.id)}"`)}</div></article>`;
}
function tokenList(tokens){const now=Date.now()/1000;return tokens.length?`<div class="xv2-list">${tokens.map(t=>{const active=!!t.enabled&&Number(t.expires_at)>now,stateLabel=!t.enabled?L('Revoked','باطل'):active?L('Enabled','فعال'):L('Expired','منقضی');return `<div class="xv2-item"><div class="xv2-item-head"><div><b>${e(t.name)}</b><br><small>${e(t.id)} · ${stateLabel} · ${L('expires','انقضا')} ${date(t.expires_at)}</small></div>${active?button(L('Revoke','ابطال'),'nv2tokenrevoke','trash',`data-id="${e(t.id)}"`):''}</div></div>`;}).join('')}</div>`:empty(L('No agent tokens on this server.','Agent Token روی این سرور وجود ندارد.'));}
async function nodesPage(){let d=await loadNodes();return heading(L('Nodes','نودها'),L('Real DARK-to-DARK HTTPS agents. No synthetic remote status.','Agent واقعی DARK-to-DARK روی HTTPS؛ بدون وضعیت ساختگی.'),button(L('Add node','افزودن نود'),'nv2new','plus','',true))+`<div class="nv2"><div class="notice">${L('Choose exactly which local inbounds belong to each node. DARK mirrors only those inbound definitions and their attached client credentials; unassigned inbounds are never deployed to that node.','برای هر نود مشخص کن کدام اینباندهای محلی متعلق به همان نود هستند. DARK فقط همان اینباندها و Credential کاربران متصل به آن‌ها را Mirror می‌کند؛ اینباند انتخاب‌نشده روی نود Deploy نمی‌شود.')}</div><div class="nv2-grid">${d.nodes.length?d.nodes.map(nodeCard).join(''):empty(L('No remote nodes registered.','نود راه‌دوری ثبت نشده است.'))}</div><div class="nv2-agent"><article class="panel xv2-card"><div class="xv2-toolbar"><div><h3>${L('This server as a node','این سرور به‌عنوان نود')}</h3><p>${L('Create an agent token here, then paste it into the central DARK panel.','اینجا Agent Token بساز و آن را در Central DARK وارد کن.')}</p></div><div class="spacer"></div>${button(L('New agent token','توکن جدید'),'nv2tokennew','plus','',true)}</div>${tokenList(d.tokens)}</article><article class="panel xv2-card"><h3>${L('Multi-node boundary','مرز Multi-node')}</h3><p>${L('Health, remote inbound inventory and core control are live. Distributed customer/traffic convergence remains a separate data-plane feature and is not claimed here.','Health، فهرست Inbound راه‌دور و کنترل Core واقعی است. همگرایی توزیع‌شده مشتری/ترافیک یک قابلیت Data-plane جداست و اینجا ادعای آن نمی‌شود.')}</p><div class="ov2-command">Authorization: Bearer dkn_...</div></article></div></div>`;}
enginePage=async function(){if(state.page==='nodes')return nodesPage();return baseEnginePage();};
function inboundPicker(selected=[]){return `<div class="nv2-picker">${state.inbounds.map(ib=>{let on=selected.includes(ib.id);return `<label class="${on?'active':''}"><input type="checkbox" name="inboundIds" value="${ib.id}" ${on?'checked':''}><span class="nv2-pick-dot"></span><span><b>${e(ib.remark||ib.tag)}</b><small>#${ib.id} · ${e(ib.protocol)} · ${e(ib.network||'tcp')} / ${e(ib.security||'none')} · :${ib.port}</small></span></label>`;}).join('')}</div>`;}
async function nodeDialog(id=null){let n=id?state.nv2.nodes.find(x=>x.id===id):null;if(!state.inbounds.length)throw Error(L('Create at least one inbound before adding a node.','قبل از افزودن نود حداقل یک اینباند بساز.'));dialog(id?L('Edit node assignment','ویرایش نود'):L('Add remote node','افزودن نود راه‌دور'),`<div class="nv2-form">${field(L('Node ID','شناسه نود'),'id',n?.id||'','text',id?'readonly':'required pattern="[A-Za-z0-9_.@+-]+"')}${field(L('Display name','نام نمایشی'),'name',n?.name||'','text','required maxlength="128"')}${field('HTTPS Origin','origin',n?.origin||'https://','url','required dir="ltr"')}${field(L('Agent token','Agent Token'),'token','','password',id?'placeholder="Paste a new token to rotate"':'required placeholder="dkn_..."')}<label>${L('Enabled','فعال')}<select name="enabled"><option value="true" ${(n?.enabled??1)?'selected':''}>true</option><option value="false" ${n&&!n.enabled?'selected':''}>false</option></select></label><div class="span-2"><div class="nv2-form-title"><b>${L('Assign inbounds to this node','انتخاب اینباندهای این نود')}</b><small>${L('Only selected inbounds and their attached clients are mirrored to this node.','فقط اینباندهای انتخاب‌شده و کاربران متصل به همان‌ها روی این نود Mirror می‌شوند.')}</small></div>${inboundPicker(n?.inboundIds||[])}</div><div class="span-2 notice">${L('The Agent Token is encrypted at rest. Saving an enabled node immediately tries to sync the selected inbounds; background monitoring keeps them synchronized afterwards.','Agent Token رمزنگاری می‌شود. با ذخیره نود فعال، اینباندهای انتخاب‌شده فوراً Sync می‌شوند و مانیتور پس‌زمینه هم آن‌ها را همگام نگه می‌دارد.')}</div></div>`,async f=>{let inboundIds=f.getAll('inboundIds').map(Number);if(!inboundIds.length)throw Error(L('Select at least one inbound for this node.','حداقل یک اینباند برای نود انتخاب کن.'));let body={id:f.get('id'),name:f.get('name'),origin:f.get('origin'),enabled:f.get('enabled')==='true',inboundIds};if(f.get('token'))body.token=f.get('token');else if(id)body.keep_token=true;let saved=await api('/api/nodes'+(id?'/'+enc(id):''),id?'PATCH':'POST',body);let syncError='';if(body.enabled){try{await api('/api/nodes/'+enc(saved.id)+'/sync','POST',{});}catch(ex){syncError=ex.message;}}closeDialog();toast(syncError?L('Node saved, but first sync failed: ','نود ذخیره شد ولی Sync اولیه خطا داد: ')+syncError:L('Node saved and assigned inbounds synced.','نود ذخیره شد و اینباندهای انتخاب‌شده Sync شدند.'),!!syncError);await renderPage();});let form=$('#dialog-form');if(form)form.addEventListener('change',ev=>{if(ev.target.name==='inboundIds')ev.target.closest('label')?.classList.toggle('active',ev.target.checked);});}
async function createToken(){dialog(L('New node agent token','Agent Token جدید'),`<div class="nv2-form">${field(L('Token name','نام توکن'),'name','central','text','required maxlength="64"')}${field(L('Validity days','اعتبار روز'),'days',365,'number','required min="1" max="3650"')}</div>`,async f=>{let r=await api('/api/node-agent/tokens','POST',{name:f.get('name'),days:Number(f.get('days'))});await renderPage();dialog(L('Copy this token now','این توکن را همین حالا کپی کن'),`<div class="notice warning">${L('The plaintext token will never be shown again.','متن اصلی توکن دیگر نمایش داده نمی‌شود.')}</div><div class="nv2-token">${e(r.token)}</div>`);});}
async function showNodeInbounds(id){let r=await api('/api/nodes/'+enc(id)+'/inbounds');dialog(L('Remote inbounds','اینباندهای راه‌دور'),`<div class="notice">${L('Read live from the remote DARK node.','به‌صورت Live از DARK نود راه‌دور خوانده شده است.')} · ${r.latency_ms} ms</div><div class="nv2-inbounds">${r.items.length?r.items.map(i=>`<div class="nv2-inbound"><span><b>${e(i.remark||i.tag)}</b><br><small>${e(i.protocol)} · ${e(i.listen||'0.0.0.0')}:${i.port}</small></span><span class="tag ${i.enable?'green':'red'}">${i.enable?'ON':'OFF'}</span></div>`).join(''):empty(L('No inbounds on node.','اینباندی روی نود نیست.'))}</div>`);}
async function refreshAfterRemote(fn){try{return await fn();}finally{if(state.page==='nodes')await renderPage();}}
runAction=async function(act,el){if(act==='nv2new'){await nodeDialog();return;}if(act==='nv2edit'){await nodeDialog(el.dataset.id);return;}if(act==='nv2probe'){await refreshAfterRemote(async()=>{let r=await api('/api/nodes/'+enc(el.dataset.id)+'/probe','POST',{});toast(`${L('Node online','نود آنلاین')} · ${r.latency_ms} ms`);});return;}if(act==='nv2inbounds'){await refreshAfterRemote(()=>showNodeInbounds(el.dataset.id));return;}if(act==='nv2sync'){await refreshAfterRemote(async()=>{let r=await api('/api/nodes/'+enc(el.dataset.id)+'/sync','POST',{});toast(`${L('Node synchronized','نود همگام شد')} · ${r.items.length} ${L('inbounds','اینباند')}`);});return;}if(act==='nv2core'){let action=el.dataset.core;if(action==='restart'&&!confirm(L('Restart Xray on the remote node? Active sessions may disconnect.','Xray روی نود راه‌دور ری‌استارت شود؟ اتصال‌ها ممکن است قطع شوند.')))return;await refreshAfterRemote(async()=>{await api('/api/nodes/'+enc(el.dataset.id)+'/core/'+action,'POST',{});toast(L('Remote core action completed.','عملیات Core راه‌دور انجام شد.'));});return;}if(act==='nv2delete'){if(confirm(L('Delete node registry entry? The remote node is not uninstalled.','رکورد نود حذف شود؟ خود نود Uninstall نمی‌شود.'))){await api('/api/nodes/'+enc(el.dataset.id),'DELETE');await renderPage();}return;}if(act==='nv2tokennew'){await createToken();return;}if(act==='nv2tokenrevoke'){if(confirm(L('Revoke this agent token immediately?','این Agent Token فوراً باطل شود؟'))){await api('/api/node-agent/tokens/'+enc(el.dataset.id),'DELETE');await renderPage();}return;}return baseRunAction(act,el);};
})();
