/* DARK XRAY Nodes V2 — real HTTPS node registry and dedicated agent tokens. */
(function(){
'use strict';
if(typeof enginePage!=='function'||typeof runAction!=='function')return;
const baseEnginePage=enginePage,baseRunAction=runAction;
const L=(en,fa)=>((localStorage.getItem('dark_lang')||'en')==='fa'?fa:en);
state.nv2={nodes:[],tokens:[]};
async function loadNodes(){const [nodes,tokens]=await Promise.all([api('/api/nodes'),api('/api/node-agent/tokens')]);state.nv2={nodes,tokens};return state.nv2;}
function healthMetric(label,value){return `<div><small>${e(label)}</small><b>${e(value??'—')}</b></div>`;}
function nodeCard(n){
 const h=n.health||{},core=h.core||{},status=!n.enabled?'disabled':n.online?'online':n.last_error?'error':'offline';
 const remote=n.enabled?`${button(L('Probe','پروب'),'nv2probe','activity',`data-id="${e(n.id)}"`)}${button(L('Inbounds','اینباندها'),'nv2inbounds','server',`data-id="${e(n.id)}"`)}${button(L('Clone inbound','کپی اینباند'),'nv2cloneinbound','copy',`data-id="${e(n.id)}"`)}${button(L('Validate','اعتبارسنجی'),'nv2core','check',`data-id="${e(n.id)}" data-core="validate"`)}${button(L('Restart Xray','ری‌استارت Xray'),'nv2core','refresh',`data-id="${e(n.id)}" data-core="restart"`)}`:'';
 return `<article class="panel nv2-node"><div class="nv2-head"><div><h3>${e(n.name)}</h3><small>${e(n.id)} · ${e(n.origin)}</small></div><div class="nv2-status ${status}"><i></i><b>${e(status)}</b></div></div><div class="nv2-metrics">${healthMetric('Latency',n.last_latency_ms?`${n.last_latency_ms} ms`:'—')}${healthMetric('Xray',core.state||'—')}${healthMetric('Clients',h.managed_clients??'—')}${healthMetric('Inbounds',h.inbounds??'—')}${healthMetric(L('Last seen','آخرین مشاهده'),n.last_seen?date(n.last_seen):'—')}</div>${n.last_error?`<div class="nv2-error">${e(n.last_error)}</div>`:''}${!n.enabled?`<div class="notice warning">${L('This node is disabled. Enable it from Edit before remote operations.','این نود غیرفعال است. قبل از عملیات راه‌دور از بخش ویرایش فعالش کن.')}</div>`:''}<div class="nv2-actions">${remote}${button(L('Edit','ویرایش'),'nv2edit','edit',`data-id="${e(n.id)}"`)}${button(L('Delete','حذف'),'nv2delete','trash',`data-id="${e(n.id)}"`)}</div></article>`;
}
function tokenList(tokens){const now=Date.now()/1000;return tokens.length?`<div class="xv2-list">${tokens.map(t=>{const active=!!t.enabled&&Number(t.expires_at)>now,stateLabel=!t.enabled?L('Revoked','باطل'):active?L('Enabled','فعال'):L('Expired','منقضی');return `<div class="xv2-item"><div class="xv2-item-head"><div><b>${e(t.name)}</b><br><small>${e(t.id)} · ${stateLabel} · ${L('expires','انقضا')} ${date(t.expires_at)}</small></div>${active?button(L('Revoke','ابطال'),'nv2tokenrevoke','trash',`data-id="${e(t.id)}"`):''}</div></div>`;}).join('')}</div>`:empty(L('No agent tokens on this server.','Agent Token روی این سرور وجود ندارد.'));}
async function nodesPage(){let d=await loadNodes();return heading(L('Nodes','نودها'),L('Real DARK-to-DARK HTTPS agents. No synthetic remote status.','Agent واقعی DARK-to-DARK روی HTTPS؛ بدون وضعیت ساختگی.'),button(L('Add node','افزودن نود'),'nv2new','plus','',true))+`<div class="nv2"><div class="notice">${L('Remote nodes must expose a valid HTTPS DARK panel and use a dedicated dkn_ agent token. The central server rejects private/reserved DNS targets to reduce SSRF risk.','نود راه‌دور باید DARK با HTTPS معتبر و Agent Token اختصاصی dkn_ داشته باشد. Central برای کاهش ریسک SSRF مقصدهای private/reserved را رد می‌کند.')}</div><div class="nv2-grid">${d.nodes.length?d.nodes.map(nodeCard).join(''):empty(L('No remote nodes registered.','نود راه‌دوری ثبت نشده است.'))}</div><div class="nv2-agent"><article class="panel xv2-card"><div class="xv2-toolbar"><div><h3>${L('This server as a node','این سرور به‌عنوان نود')}</h3><p>${L('Create an agent token here, then paste it into the central DARK panel.','اینجا Agent Token بساز و آن را در Central DARK وارد کن.')}</p></div><div class="spacer"></div>${button(L('New agent token','توکن جدید'),'nv2tokennew','plus','',true)}</div>${tokenList(d.tokens)}</article><article class="panel xv2-card"><h3>${L('Multi-node boundary','مرز Multi-node')}</h3><p>${L('Health, remote inbound inventory and core control are live. Distributed customer/traffic convergence remains a separate data-plane feature and is not claimed here.','Health، فهرست Inbound راه‌دور و کنترل Core واقعی است. همگرایی توزیع‌شده مشتری/ترافیک یک قابلیت Data-plane جداست و اینجا ادعای آن نمی‌شود.')}</p><div class="ov2-command">Authorization: Bearer dkn_...</div></article></div></div>`;}
enginePage=async function(){if(state.page==='nodes')return nodesPage();return baseEnginePage();};
async function nodeDialog(id=null){let n=id?state.nv2.nodes.find(x=>x.id===id):null;dialog(id?L('Edit node','ویرایش نود'):L('Add remote node','افزودن نود راه‌دور'),`<div class="nv2-form">${field(L('Node ID','شناسه نود'),'id',n?.id||'','text',id?'readonly':'required pattern="[A-Za-z0-9_.@+-]+"')}${field(L('Display name','نام نمایشی'),'name',n?.name||'','text','required maxlength="128"')}${field('HTTPS Origin','origin',n?.origin||'https://','url','required dir="ltr"')}${field(L('Agent token','Agent Token'),'token','','password',id?'placeholder="Paste a new token to rotate"':'required placeholder="dkn_..."')}<label>${L('Enabled','فعال')}<select name="enabled"><option value="true" ${(n?.enabled??1)?'selected':''}>true</option><option value="false" ${n&&!n.enabled?'selected':''}>false</option></select></label><div class="span-2 notice">${L('The token is encrypted at rest on Central and is never returned to the browser after saving.','توکن در Central رمزنگاری می‌شود و بعد از ذخیره دوباره به مرورگر برگردانده نمی‌شود.')}</div></div>`,async f=>{let body={id:f.get('id'),name:f.get('name'),origin:f.get('origin'),enabled:f.get('enabled')==='true'};if(f.get('token'))body.token=f.get('token');else if(id)body.keep_token=true;await api('/api/nodes'+(id?'/'+enc(id):''),id?'PATCH':'POST',body);closeDialog();toast(L('Node saved.','نود ذخیره شد.'));await renderPage();});}
async function createToken(){dialog(L('New node agent token','Agent Token جدید'),`<div class="nv2-form">${field(L('Token name','نام توکن'),'name','central','text','required maxlength="64"')}${field(L('Validity days','اعتبار روز'),'days',365,'number','required min="1" max="3650"')}</div>`,async f=>{let r=await api('/api/node-agent/tokens','POST',{name:f.get('name'),days:Number(f.get('days'))});await renderPage();dialog(L('Copy this token now','این توکن را همین حالا کپی کن'),`<div class="notice warning">${L('The plaintext token will never be shown again.','متن اصلی توکن دیگر نمایش داده نمی‌شود.')}</div><div class="nv2-token">${e(r.token)}</div>`);});}
async function showNodeInbounds(id){let r=await api('/api/nodes/'+enc(id)+'/inbounds');dialog(L('Remote inbounds','اینباندهای راه‌دور'),`<div class="notice">${L('Read live from the remote DARK node.','به‌صورت Live از DARK نود راه‌دور خوانده شده است.')} · ${r.latency_ms} ms</div><div class="nv2-inbounds">${r.items.length?r.items.map(i=>`<div class="nv2-inbound"><span><b>${e(i.remark||i.tag)}</b><br><small>${e(i.protocol)} · ${e(i.listen||'0.0.0.0')}:${i.port}</small></span><span class="tag ${i.enable?'green':'red'}">${i.enable?'ON':'OFF'}</span></div>`).join(''):empty(L('No inbounds on node.','اینباندی روی نود نیست.'))}</div>`);}
async function cloneInboundToNode(nodeId){if(!state.inbounds.length)throw Error(L('Create a local inbound first.','ابتدا یک اینباند محلی بساز.'));dialog(L('Clone local inbound to node','کپی اینباند محلی روی نود'),`<div class="nv2-form">${select(L('Source inbound','اینباند مبدا'),'source',state.inbounds.map(i=>[i.id,(i.remark||i.tag)+' · '+i.protocol+' :'+i.port]),state.inbounds[0].id)}${field(L('Remote port','پورت راه‌دور'),'port',state.inbounds[0].port,'number','required min="1" max="65535"')}${field(L('Remote remark','نام راه‌دور'),'remark',(state.inbounds[0].remark||'DARK')+' NODE','text','required maxlength="200"')}${field(L('Remote tag','تگ راه‌دور'),'tag',(state.inbounds[0].tag||'dark-in')+'-'+nodeId,'text','required pattern="[A-Za-z0-9_.-]+"')}<div class="span-2 notice">${L('The full inbound transport/REALITY/TLS/sniffing settings are copied. Clients and reseller ownership are never copied. The remote Xray stays dirty until Validate/Restart.','تمام تنظیمات Transport/REALITY/TLS/Sniffing کپی می‌شوند؛ Client و مالکیت نماینده هرگز کپی نمی‌شود. Xray راه‌دور تا Validate/Restart در حالت dirty می‌ماند.')}</div></div>`,async f=>{let src=await api('/api/inbounds/'+enc(f.get('source'))),payload=JSON.parse(JSON.stringify(src));for(const k of ['id','applied'])delete payload[k];payload.port=Number(f.get('port'));payload.remark=f.get('remark').trim();payload.tag=f.get('tag').trim();let r=await api('/api/nodes/'+enc(nodeId)+'/inbounds','POST',payload);closeDialog();toast(`${L('Inbound cloned','اینباند کپی شد')} · #${r.inbound.id} · ${r.latency_ms} ms`);await renderPage();});let sel=$('#dialog-form select[name="source"]');if(sel)sel.addEventListener('change',()=>{let ib=state.inbounds.find(x=>String(x.id)===String(sel.value));if(ib){let form=$('#dialog-form');form.elements.port.value=ib.port;form.elements.remark.value=(ib.remark||'DARK')+' NODE';form.elements.tag.value=(ib.tag||'dark-in')+'-'+nodeId;}});}
async function refreshAfterRemote(fn){try{return await fn();}finally{if(state.page==='nodes')await renderPage();}}
runAction=async function(act,el){if(act==='nv2new'){await nodeDialog();return;}if(act==='nv2edit'){await nodeDialog(el.dataset.id);return;}if(act==='nv2probe'){await refreshAfterRemote(async()=>{let r=await api('/api/nodes/'+enc(el.dataset.id)+'/probe','POST',{});toast(`${L('Node online','نود آنلاین')} · ${r.latency_ms} ms`);});return;}if(act==='nv2inbounds'){await refreshAfterRemote(()=>showNodeInbounds(el.dataset.id));return;}if(act==='nv2cloneinbound'){await cloneInboundToNode(el.dataset.id);return;}if(act==='nv2core'){let action=el.dataset.core;if(action==='restart'&&!confirm(L('Restart Xray on the remote node? Active sessions may disconnect.','Xray روی نود راه‌دور ری‌استارت شود؟ اتصال‌ها ممکن است قطع شوند.')))return;await refreshAfterRemote(async()=>{await api('/api/nodes/'+enc(el.dataset.id)+'/core/'+action,'POST',{});toast(L('Remote core action completed.','عملیات Core راه‌دور انجام شد.'));});return;}if(act==='nv2delete'){if(confirm(L('Delete node registry entry? The remote node is not uninstalled.','رکورد نود حذف شود؟ خود نود Uninstall نمی‌شود.'))){await api('/api/nodes/'+enc(el.dataset.id),'DELETE');await renderPage();}return;}if(act==='nv2tokennew'){await createToken();return;}if(act==='nv2tokenrevoke'){if(confirm(L('Revoke this agent token immediately?','این Agent Token فوراً باطل شود؟'))){await api('/api/node-agent/tokens/'+enc(el.dataset.id),'DELETE');await renderPage();}return;}return baseRunAction(act,el);};
})();
