/* DARK XRAY Nodes V4 — deployment and subscription orchestration. */
(function(){
'use strict';
if(typeof enginePage!=='function'||typeof runAction!=='function')return;
const baseEnginePage=enginePage,baseRunAction=runAction;
const L=(en,fa)=>((localStorage.getItem('dark_lang')||'en')==='fa'?fa:en);
state.nv2=state.nv2||{nodes:[],tokens:[],orchestration:null,nodeError:'',tokenError:'',orchestrationError:''};

async function loadNodes(){
 let nodes=[],tokens=[],orchestration=null,nodeError='',tokenError='',orchestrationError='';
 try{nodes=await api('/api/nodes');}catch(ex){nodeError=ex.message||String(ex);}
 try{orchestration=await api('/api/nodes/orchestration');}catch(ex){orchestrationError=ex.message||String(ex);}
 try{tokens=await api('/api/node-agent/tokens');}catch(ex){tokenError=ex.message||String(ex);}
 state.nv2={nodes,tokens,orchestration,nodeError,tokenError,orchestrationError};return state.nv2;
}
function healthMetric(label,value){return `<div><small>${e(label)}</small><b>${e(value??'—')}</b></div>`;}
function assignedNames(n){return (n.inboundIds||[]).map(id=>{let ib=state.inbounds.find(x=>x.id===id);return ib?(ib.remark||ib.tag):'#'+id;});}
const reasonLabels={
 ready:['IN SUBSCRIPTION','داخل اشتراک'],not_deployed:['NOT DEPLOYED','Deploy نشده'],sync_error:['SYNC ERROR','خطای Sync'],
 node_disabled:['NODE DISABLED','نود غیرفعال'],failover_disabled:['FAILOVER OFF','فیل‌اور خاموش'],
 data_address_missing:['NO DATA ADDRESS','Data Address ندارد'],node_offline:['NODE OFFLINE','نود آفلاین'],no_assignments:['NO ASSIGNMENTS','بدون تخصیص']
};
function reasonLabel(code){const pair=reasonLabels[code]||[String(code||'UNKNOWN').toUpperCase(),String(code||'نامشخص')];return L(pair[0],pair[1]);}
function reasonClass(code){return code==='ready'?'ready':code==='sync_error'?'error':['not_deployed','node_offline'].includes(code)?'warn':'off';}
function assignmentChip(a){
 const ib=state.inbounds.find(x=>x.id===Number(a.local_inbound_id)),name=ib?(ib.remark||ib.tag):'#'+a.local_inbound_id;
 return `<span class="nv4-assignment ${reasonClass(a.failover_reason)}"><b>${e(name)}</b><small>${e(a.deployment_state||'pending')} · ${e(reasonLabel(a.failover_reason))}</small></span>`;
}
function nodeCard(n){
 const h=n.health||{},core=h.core||{},status=!n.enabled?'disabled':n.online?'online':n.last_error?'error':'offline',assigned=assignedNames(n);
 const syncErrors=(n.assignments||[]).filter(x=>x.last_error);
 const remote=n.enabled?`${button(L('Probe','پروب'),'nv2probe','activity',`data-id="${e(n.id)}"`)}${button(L('Sync node','همگام‌سازی نود'),'nv2sync','refresh',`data-id="${e(n.id)}"`,true)}${button(L('Security sync','همگام‌سازی امنیت'),'nv2security','shield',`data-id="${e(n.id)}"`)}${button(L('Remote inbounds','اینباندهای نود'),'nv2inbounds','server',`data-id="${e(n.id)}"`)}${button(L('Validate','اعتبارسنجی'),'nv2core','check',`data-id="${e(n.id)}" data-core="validate"`)}${button(L('Restart Xray','ری‌استارت Xray'),'nv2core','refresh',`data-id="${e(n.id)}" data-core="restart"`)}`:'';
 return `<article class="panel nv2-node"><div class="nv2-head"><div><h3>${e(n.name)}</h3><small>${e(n.id)} · ${e(n.origin)} · DATA ${e(n.data_address||'—')} · P${e(n.priority||100)}</small></div><div class="nv2-status ${status}"><i></i><b>${e(status)}</b></div></div>
 <div class="nv2-assigned"><span>${L('ASSIGNMENT STATE','وضعیت تخصیص')}</span><div>${(n.assignments||[]).length?(n.assignments||[]).map(assignmentChip).join(''):`<small>${L('No inbound assigned','اینباندی انتخاب نشده')}</small>`}</div></div>
 <div class="nv2-metrics">${healthMetric('Latency',n.last_latency_ms?`${n.last_latency_ms} ms`:'—')}${healthMetric('Xray',core.state||'—')}${healthMetric(L('Assigned','اختصاص‌یافته'),assigned.length)}${healthMetric(L('Central traffic','ترافیک مرکزی'),bytes(n.traffic_current_bytes||0))}${healthMetric(L('Traffic sync','همگام‌سازی ترافیک'),n.traffic_last_sync?date(n.traffic_last_sync):'—')}${healthMetric(L('Subscription','اشتراک'),reasonLabel(n.failover_reason))}${healthMetric(L('Security','امنیت'),n.security?.last_error?L('ERROR','خطا'):n.security?.last_sync?(n.security?.source_verified?L('VERIFIED','تأییدشده'):L('OBSERVE','مانیتور')):'—')}${healthMetric(L('Recoveries','بازیابی‌ها'),n.recovery_count||0)}</div>
 ${n.last_error?`<div class="nv2-error">${e(n.last_error)}</div>`:''}${syncErrors.length?`<div class="nv2-error">${e(syncErrors.map(x=>'#'+x.local_inbound_id+': '+x.last_error).join(' · '))}</div>`:''}${!n.enabled?`<div class="notice warning">${L('This node is disabled. Enable it from Edit before remote operations.','این نود غیرفعال است. قبل از عملیات راه‌دور از بخش ویرایش فعالش کن.')}</div>`:''}
 <div class="nv2-actions">${remote}${button(L('Edit assignment','ویرایش نود'),'nv2edit','edit',`data-id="${e(n.id)}"`)}${button(L('Delete','حذف'),'nv2delete','trash',`data-id="${e(n.id)}"`)}</div></article>`;
}
function tokenList(tokens){const now=Date.now()/1000;return tokens.length?`<div class="xv2-list">${tokens.map(t=>{const active=!!t.enabled&&Number(t.expires_at)>now,stateLabel=!t.enabled?L('Revoked','باطل'):active?L('Enabled','فعال'):L('Expired','منقضی');return `<div class="xv2-item"><div class="xv2-item-head"><div><b>${e(t.name)}</b><br><small>${e(t.id)} · ${stateLabel} · ${L('expires','انقضا')} ${date(t.expires_at)}</small></div>${active?button(L('Revoke','ابطال'),'nv2tokenrevoke','trash',`data-id="${e(t.id)}"`):''}</div></div>`;}).join('')}</div>`:empty(L('No agent tokens on this server.','Agent Token روی این سرور وجود ندارد.'));}

function primaryEndpoint(p){return `<span class="nv4-primary"><b class="mono">${e(p.address)}:${e(p.port)}</b><small>${e(p.remark||'')}</small></span>`;}
function routeCard(r){
 const label=reasonLabel(r.subscription_reason),cls=reasonClass(r.subscription_reason);
 return `<article class="nv4-route ${cls}"><header><div><b>${e(r.name)}</b><small>${e(r.node_id)} · P${e(r.priority)} · ${r.latency_ms?e(r.latency_ms)+' ms':'—'}</small></div><span>${e(label)}</span></header>
 <div class="nv4-route-grid"><div><small>${L('FAILOVER ENDPOINT','Endpoint فیل‌اور')}</small><b class="mono">${e(r.data_address||'—')}:${e(r.data_port)}</b></div><div><small>${L('DEPLOYMENT','Deploy')}</small><b>${e(r.deployment_state)}</b></div><div><small>${L('REMOTE INBOUND','اینباند ریموت')}</small><b>${r.remote_inbound_id?'#'+e(r.remote_inbound_id):'—'}</b></div><div><small>${L('LAST SYNC','آخرین Sync')}</small><b>${r.last_sync?date(r.last_sync):'—'}</b></div></div>
 ${r.last_error?`<div class="nv2-error">${e(r.last_error)}</div>`:''}
 <footer>${button(L('Sync this node','Sync این نود'),'nv2sync','refresh',`data-id="${e(r.node_id)}"`,r.subscription_reason!=='ready')}${button(L('Edit node','ویرایش نود'),'nv2edit','edit',`data-id="${e(r.node_id)}"`)}</footer></article>`;
}
function orchestrationBoard(doc){
 if(!doc)return `<article class="panel nv4-orch-empty"><b>${L('Subscription orchestration unavailable.','Orchestration اشتراک در دسترس نیست.')}</b></article>`;
 const s=doc.summary||{},rows=doc.inbounds||[];
 return `<section class="nv4-orchestrator"><div class="nv4-orch-head"><div><span>DARK XRAY / NODE ORCHESTRATOR</span><h2>${L('Subscription Orchestrator','Orchestrator اشتراک')}</h2><p>${L('See exactly which node routes are deployed and which ones are actually emitted into customer subscriptions.','دقیقاً ببین کدام مسیر نود Deploy شده و کدام مسیر واقعاً داخل Subscription مشتری منتشر می‌شود.')}</p></div><div class="nv4-orch-summary">${healthMetric(L('Nodes','نود'),s.nodes||0)}${healthMetric(L('Inbounds','اینباند'),s.inbounds||0)}${healthMetric(L('Assigned routes','مسیر تخصیص'),s.assigned_routes||0)}${healthMetric(L('Deployed','Deploy شده'),s.deployed_routes||0)}${healthMetric(L('In subscription','داخل اشتراک'),s.subscription_routes||0)}</div></div>
 <div class="notice">${L('Primary routes come from Public Endpoints. Failover routes use the node Data Address plus the source inbound port. Only routes marked IN SUBSCRIPTION are delivered to customers.','مسیر اصلی از Public Endpoints می‌آید. مسیر Failover از Data Address نود به‌علاوه پورت Source Inbound استفاده می‌کند. فقط مسیرهایی که IN SUBSCRIPTION هستند به مشتری تحویل داده می‌شوند.')}</div>
 <div class="nv4-inbound-list">${rows.length?rows.map(inboundOrchestration).join(''):empty(L('No inbounds to orchestrate.','اینباندی برای Orchestration وجود ندارد.'))}</div></section>`;
}
function inboundOrchestration(row){
 const routes=row.routes||[],ready=routes.filter(x=>x.subscription_included).length;
 return `<article class="panel nv4-inbound"><header><div><small>#${e(row.inbound_id)} · ${e(String(row.protocol||'').toUpperCase())} · ${e(String(row.network||'').toUpperCase())} / ${e(String(row.security||'').toUpperCase())}</small><h3>${e(row.remark)}</h3></div><div class="nv4-inbound-stats"><span>${fa(row.client_count||0)} ${L('clients','کاربر')}</span><span class="${ready?'ready':'off'}">${fa(ready)} ${L('failover routes','مسیر فیل‌اور')}</span></div></header>
 <div class="nv4-primary-line"><span>${L('PRIMARY / PUBLIC ENDPOINTS','مسیر اصلی / Public Endpoint')}</span><div>${(row.primary_endpoints||[]).map(primaryEndpoint).join('')}</div></div>
 <div class="nv4-routes">${routes.length?routes.map(routeCard).join(''):`<div class="nv4-no-route"><b>${L('No node assigned to this inbound.','هیچ نودی به این اینباند اختصاص داده نشده.')}</b><small>${L('Edit a node and assign this inbound when you want remote deployment or failover.','برای Deploy یا Failover، از Edit Node این اینباند را به نود اختصاص بده.')}</small></div>`}</div></article>`;
}

async function nodesPage(){
 let d=await loadNodes(),errs='';
 if(d.nodeError)errs+=`<div class="notice error">${L('Node registry could not be loaded: ','فهرست نودها دریافت نشد: ')}${e(d.nodeError)}</div>`;
 if(d.orchestrationError)errs+=`<div class="notice warning">${L('Subscription orchestration could not be loaded: ','Orchestration اشتراک دریافت نشد: ')}${e(d.orchestrationError)}</div>`;
 if(d.tokenError)errs+=`<div class="notice warning">${L('Agent tokens could not be loaded; node management remains available: ','Agent Tokenها دریافت نشدند؛ مدیریت نود همچنان در دسترس است: ')}${e(d.tokenError)}</div>`;
 return heading(L('Nodes','نودها'),L('Deploy inbounds to remote DARK nodes and see exactly what reaches customer subscriptions.','اینباندها را روی نودهای DARK Deploy کن و دقیقاً ببین چه چیزی وارد Subscription مشتری می‌شود.'),button(L('Add node','افزودن نود'),'nv2new','plus','',true))+
 `<div class="nv2">${errs}${orchestrationBoard(d.orchestration)}<section><div class="nv4-section-title"><div><small>DARK NODE FLEET</small><h2>${L('Node maintenance','نگهداری نودها')}</h2></div><span>${fa(d.nodes.length)}</span></div><div class="nv2-grid">${d.nodes.length?d.nodes.map(nodeCard).join(''):empty(L('No remote nodes registered.','نود راه‌دوری ثبت نشده است.'))}</div></section>
 <div class="nv2-agent"><article class="panel xv2-card"><div class="xv2-toolbar"><div><h3>${L('This server as a node','این سرور به‌عنوان نود')}</h3><p>${L('Create an agent token here, then paste it into the central DARK panel.','اینجا Agent Token بساز و آن را در Central DARK وارد کن.')}</p></div><div class="spacer"></div>${button(L('New agent token','توکن جدید'),'nv2tokennew','plus','',true)}</div>${d.tokenError?empty(L('Agent token list unavailable.','فهرست Agent Token در دسترس نیست.')):tokenList(d.tokens)}</article><article class="panel xv2-card"><h3>${L('Multi-node security & failover','امنیت و فیل‌اور Multi-node')}</h3><p>${L('Central aggregates verified source-IP observations, device hashes and traffic from assigned nodes. Subscription inclusion is decided per deployed inbound, not merely by node health.','Central مشاهده IP، دستگاه و ترافیک نودها را تجمیع می‌کند. ورود به Subscription به ازای هر Inbound Deploy‌شده تصمیم‌گیری می‌شود، نه فقط سلامت کلی نود.')}</p><div class="ov2-command">Authorization: Bearer dkn_...</div></article></div></div>`;
}
enginePage=async function(){if(state.page==='nodes')return nodesPage();return baseEnginePage();};
function inboundPicker(selected=[]){return `<div class="nv2-picker">${state.inbounds.map(ib=>{let on=selected.includes(ib.id);return `<label class="${on?'active':''}"><input type="checkbox" name="inboundIds" value="${ib.id}" ${on?'checked':''}><span class="nv2-pick-dot"></span><span><b>${e(ib.remark||ib.tag)}</b><small>#${ib.id} · ${e(ib.protocol)} · ${e(ib.network||'tcp')} / ${e(ib.security||'none')} · :${ib.port}</small></span></label>`;}).join('')}</div>`;}
async function nodeDialog(id=null){
 let n=id?state.nv2.nodes.find(x=>x.id===id):null;if(!state.inbounds.length)throw Error(L('Create at least one inbound before adding a node.','قبل از افزودن نود حداقل یک اینباند بساز.'));
 dialog(id?L('Edit node assignment','ویرایش نود'):L('Add remote node','افزودن نود راه‌دور'),`<div class="nv2-form">${field(L('Node ID','شناسه نود'),'id',n?.id||'','text',id?'readonly':'required pattern="[A-Za-z0-9_.@+-]+"')}${field(L('Display name','نام نمایشی'),'name',n?.name||'','text','required maxlength="128"')}${field('HTTPS Origin','origin',n?.origin||'https://','url','required dir="ltr"')}${field(L('Data address','آدرس دیتاپلن'),'dataAddress',n?.data_address||'','text','placeholder="node.example.com" maxlength="253" dir="ltr"')}${field(L('Agent token','Agent Token'),'token','','password',id?'placeholder="Paste a new token to rotate"':'required placeholder="dkn_..."')}${field(L('Failover priority','اولویت فیل‌اور'),'priority',n?.priority||100,'number','required min="1" max="1000"')}<label>${L('Enabled','فعال')}<select name="enabled"><option value="true" ${(n?.enabled??1)?'selected':''}>true</option><option value="false" ${n&&!n.enabled?'selected':''}>false</option></select></label><label>${L('Failover','فیل‌اور')}<select name="failoverEnabled"><option value="true" ${(n?.failover_enabled??1)?'selected':''}>true</option><option value="false" ${n&&!n.failover_enabled?'selected':''}>false</option></select></label><div class="span-2"><div class="nv2-form-title"><b>${L('Assign inbounds to this node','انتخاب اینباندهای این نود')}</b><small>${L('Only selected inbounds and their attached clients are mirrored to this node.','فقط اینباندهای انتخاب‌شده و کاربران متصل به همان‌ها روی این نود Mirror می‌شوند.')}</small></div>${inboundPicker(n?.inboundIds||[])}</div><div class="span-2 notice">${L('Data Address is only the client-facing failover host. The failover port is the source inbound port, not the primary Public Endpoint tunnel/CDN port. Lower Priority numbers are preferred.','Data Address فقط Host فیل‌اور سمت مشتری است. پورت Failover همان پورت Source Inbound است، نه پورت تانل/CDN در Public Endpoint اصلی. Priority کمتر، اولویت بالاتری دارد.')}</div></div>`,async f=>{let inboundIds=f.getAll('inboundIds').map(Number);if(!inboundIds.length)throw Error(L('Select at least one inbound for this node.','حداقل یک اینباند برای نود انتخاب کن.'));let body={id:f.get('id'),name:f.get('name'),origin:f.get('origin'),dataAddress:f.get('dataAddress'),priority:Number(f.get('priority')),enabled:f.get('enabled')==='true',failoverEnabled:f.get('failoverEnabled')==='true',inboundIds};if(f.get('token'))body.token=f.get('token');else if(id)body.keep_token=true;let saved=await api('/api/nodes'+(id?'/'+enc(id):''),id?'PATCH':'POST',body);let syncError='';if(body.enabled){try{await api('/api/nodes/'+enc(saved.id)+'/sync','POST',{});}catch(ex){syncError=ex.message;}}closeDialog();toast(syncError?L('Node saved, but first sync failed: ','نود ذخیره شد ولی Sync اولیه خطا داد: ')+syncError:L('Node saved and orchestration state refreshed.','نود ذخیره شد و وضعیت Orchestration به‌روز شد.'),!!syncError);await renderPage();});
 let form=$('#dialog-form');if(form)form.addEventListener('change',ev=>{if(ev.target.name==='inboundIds')ev.target.closest('label')?.classList.toggle('active',ev.target.checked);});
}
async function createToken(){dialog(L('New node agent token','Agent Token جدید'),`<div class="nv2-form">${field(L('Token name','نام توکن'),'name','central','text','required maxlength="64"')}${field(L('Validity days','اعتبار روز'),'days',365,'number','required min="1" max="3650"')}</div>`,async f=>{let r=await api('/api/node-agent/tokens','POST',{name:f.get('name'),days:Number(f.get('days'))});await renderPage();dialog(L('Copy this token now','این توکن را همین حالا کپی کن'),`<div class="notice warning">${L('The plaintext token will never be shown again.','متن اصلی توکن دیگر نمایش داده نمی‌شود.')}</div><div class="nv2-token">${e(r.token)}</div>`);});}
async function showNodeInbounds(id){let r=await api('/api/nodes/'+enc(id)+'/inbounds');dialog(L('Remote inbounds','اینباندهای راه‌دور'),`<div class="notice">${L('Read live from the remote DARK node.','به‌صورت Live از DARK نود راه‌دور خوانده شده است.')} · ${r.latency_ms} ms</div><div class="nv2-inbounds">${r.items.length?r.items.map(i=>`<div class="nv2-inbound"><span><b>${e(i.remark||i.tag)}</b><br><small>${e(i.protocol)} · ${e(i.listen||'0.0.0.0')}:${i.port}</small></span><span class="tag ${i.enable?'green':'red'}">${i.enable?'ON':'OFF'}</span></div>`).join(''):empty(L('No inbounds on node.','اینباندی روی نود نیست.'))}</div>`);}
async function refreshAfterRemote(fn){try{return await fn();}finally{if(state.page==='nodes')await renderPage();}}
runAction=async function(act,el){
 if(act==='nv2new'){await nodeDialog();return;}if(act==='nv2edit'){await nodeDialog(el.dataset.id);return;}
 if(act==='nv2probe'){await refreshAfterRemote(async()=>{let r=await api('/api/nodes/'+enc(el.dataset.id)+'/probe','POST',{});toast(`${L('Node online','نود آنلاین')} · ${r.latency_ms} ms`);});return;}
 if(act==='nv2inbounds'){await refreshAfterRemote(()=>showNodeInbounds(el.dataset.id));return;}
 if(act==='nv2sync'){await refreshAfterRemote(async()=>{let r=await api('/api/nodes/'+enc(el.dataset.id)+'/sync','POST',{});toast(`${L('Node synchronized','نود همگام شد')} · ${r.items.length} ${L('inbounds','اینباند')} · ${bytes(r.traffic?.charged_bytes||0)} ${L('new traffic','ترافیک جدید')}`);});return;}
 if(act==='nv2security'){await refreshAfterRemote(async()=>{let r=await api('/api/nodes/'+enc(el.dataset.id)+'/security','POST',{});toast(`${L('Security synchronized','امنیت همگام شد')} · ${r.node.ips} IP · ${r.node.devices} ${L('devices','دستگاه')}`);});return;}
 if(act==='nv2core'){let action=el.dataset.core;if(action==='restart'&&!confirm(L('Restart Xray on the remote node? Active sessions may disconnect.','Xray روی نود راه‌دور ری‌استارت شود؟ اتصال‌ها ممکن است قطع شوند.')))return;await refreshAfterRemote(async()=>{await api('/api/nodes/'+enc(el.dataset.id)+'/core/'+action,'POST',{});toast(L('Remote core action completed.','عملیات Core راه‌دور انجام شد.'));});return;}
 if(act==='nv2delete'){if(confirm(L('Delete node registry entry? The remote node is not uninstalled.','رکورد نود حذف شود؟ خود نود Uninstall نمی‌شود.'))){await api('/api/nodes/'+enc(el.dataset.id),'DELETE');await renderPage();}return;}
 if(act==='nv2tokennew'){await createToken();return;}if(act==='nv2tokenrevoke'){if(confirm(L('Revoke this agent token immediately?','این Agent Token فوراً باطل شود؟'))){await api('/api/node-agent/tokens/'+enc(el.dataset.id),'DELETE');await renderPage();}return;}
 return baseRunAction(act,el);
};
})();
