/* DARK XRAY Operations V2 — real dashboard, runtime logs and safe backup surface. */
(function(){
'use strict';
if(typeof dashboard!=='function'||typeof load!=='function'||typeof enginePage!=='function'||typeof navItems!=='function'||typeof runAction!=='function'||typeof go!=='function')return;
const baseLoad=load,baseEnginePage=enginePage,baseNavItems=navItems,baseRunAction=runAction,baseGo=go;
state.ov2={audit:[],ip:null,core:null,backup:null,nodes:[],logKind:'process'};
enginePages.logs=['Logs'];enginePages.backup=['Backup'];
const L=(en,fa)=>((localStorage.getItem('dark_lang')||'en')==='fa'?fa:en);
navItems=function(){let n=baseNavItems();if(isOwner()){let at=n.findIndex(x=>x[0]==='sync');let extras=[['logs','Logs','terminal']];if(at<0)n.push(...extras);else n.splice(at,0,...extras);}return n;};
load=async function(){
 await baseLoad();
 if(!state.me){state.ov2.audit=[];state.ov2.ip=null;state.ov2.core=null;state.ov2.backup=null;state.ov2.nodes=[];return;}
 // Never retain privileged data in the in-memory dashboard cache after an
 // account/permission change. This matters on shared browsers after logout/login.
 if(!isOwner()){state.ov2.core=null;state.ov2.backup=null;state.ov2.nodes=[];}
 if(!can('audit.read'))state.ov2.audit=[];
 if(!can('clients.ip'))state.ov2.ip=null;
 // Audit/IP payloads can be large. Fetch them only while the operations dashboard
 // is visible instead of adding three extra requests to every 12-second refresh.
 if(state.page!=='dashboard')return;
 let jobs=[];
 if(isOwner()){jobs.push((async()=>{try{state.ov2.core=await api('/api/core/state');}catch{state.ov2.core=null;}})());jobs.push((async()=>{try{state.ov2.backup=await api('/api/backup/status');}catch{state.ov2.backup=null;}})());jobs.push((async()=>{try{state.ov2.nodes=await api('/api/nodes');}catch{state.ov2.nodes=[];}})());}
 if(can('audit.read'))jobs.push((async()=>{try{state.ov2.audit=await api('/api/audit');}catch{state.ov2.audit=[];}})());
 if(can('clients.ip'))jobs.push((async()=>{try{state.ov2.ip=await api('/api/ip/events');}catch{state.ov2.ip=null;}})());
 await Promise.all(jobs);
};
// `go()` renders immediately without loading. Refresh once when entering the
// dashboard so heavy operational data is fresh instead of waiting for the timer.
go=async function(page){await baseGo(page);if(page==='dashboard'&&state.me)await refresh();};
function kpi(label,value,sub=''){return `<div class="ov2-kpi"><small>${e(label)}</small><b>${e(value)}</b>${sub?`<span class="cv2-muted">${e(sub)}</span>`:''}</div>`;}
function eventFeed(){let rows=(state.ov2.audit||[]).slice(0,8);return rows.length?`<div class="ov2-feed">${rows.map(r=>`<div class="ov2-event"><time>${date(r.at)}</time><span>${e(r.actor)}</span><b>${e(r.action)} · ${e(r.target)}</b></div>`).join('')}</div>`:empty(L('No recent audit events.','رویداد اخیر وجود ندارد.'));}

function issueRow(kind,title,detail=''){return `<div class="ov2-issue ${kind}"><i></i><div><b>${e(title)}</b>${detail?`<small>${e(detail)}</small>`:''}</div></div>`;}
function healthPanel(){
 const core=state.ov2.core||state.sync?.runtime||{},nodes=state.ov2.nodes||[],enabled=nodes.filter(n=>n.enabled),offline=enabled.filter(n=>!n.online),nodeErrors=nodes.filter(n=>n.last_error||(n.assignments||[]).some(a=>a.last_error)),bans=state.ov2.ip?.bans?.length||0,up=state.updateCenter||{},broker=up.status?.broker_ready;
 const issues=[];
 if(core.last_error)issues.push(issueRow('bad',L('Runtime needs attention','Runtime نیاز به بررسی دارد'),core.last_error));
 if(core.dirty)issues.push(issueRow('warn',L('Xray configuration is pending apply','کانفیگ Xray در انتظار اعمال است'),L('Saved configuration differs from the running core.','تنظیمات ذخیره‌شده با Core در حال اجرا متفاوت است.')));
 if(offline.length)issues.push(issueRow('bad',L('Remote nodes offline','نودهای راه‌دور آفلاین هستند'),offline.map(n=>n.name||n.id).join(', ')));
 if(nodeErrors.length)issues.push(issueRow('warn',L('Node sync errors detected','خطای Sync نود وجود دارد'),nodeErrors.map(n=>n.name||n.id).join(', ')));
 if(up.error||broker===false)issues.push(issueRow('bad',L('Update Broker unavailable','Update Broker در دسترس نیست'),up.error||L('Broker health check failed.','Health Check بروکر ناموفق است.')));
 if(!issues.length)issues.push(issueRow('good',L('All monitored services nominal','همه سرویس‌های مانیتورشده سالم هستند'),L('No runtime, node or update-broker alert is active.','هیچ هشدار Runtime، Node یا Update Broker فعال نیست.')));
 return `<section class="ov2-priority"><div class="ov2-section-head"><div><span class="eyebrow">01 / HEALTH & ALERTS</span><h2>${L('Health & alerts','سلامت و هشدارها')}</h2><p>${L('Problems are shown before routine metrics so failures cannot hide below the fold.','مشکلات قبل از آمار عادی نمایش داده می‌شوند تا خطاها پایین صفحه پنهان نشوند.')}</p></div><div class="ov2-priority-actions"><button class="btn" data-act="ov2doctorhelp">${icon('activity')}${L('Doctor','Doctor')}</button><button class="btn" data-act="ov2logs">${icon('terminal')}${L('Logs','لاگ‌ها')}</button></div></div><div class="ov2-health-strip"><div><span>XRAY</span><b class="${core.state==='running'?'good':'bad'}">${e(core.state||'—')}</b></div><div><span>${L('CONFIG','کانفیگ')}</span><b class="${core.dirty?'warn':'good'}">${core.dirty?L('PENDING','در انتظار'):L('APPLIED','اعمال‌شده')}</b></div><div><span>NODES</span><b class="${offline.length?'bad':'good'}">${enabled.length-offline.length}/${enabled.length} ${L('online','آنلاین')}</b></div><div><span>IP GUARD</span><b class="${bans?'warn':'good'}">${bans} ${L('bans','بن')}</b></div><div><span>UPDATE BROKER</span><b class="${up.error||broker===false?'bad':broker===true?'good':''}">${up.error||broker===false?L('OFFLINE','قطع'):broker===true?L('READY','آماده'):'—'}</b></div></div><div class="ov2-issues">${issues.join('')}</div></section>`;
}
function nodesPanel(){
 if(!isOwner())return '';
 const nodes=state.ov2.nodes||[],enabled=nodes.filter(n=>n.enabled),online=enabled.filter(n=>n.online),offline=enabled.filter(n=>!n.online),disabled=nodes.filter(n=>!n.enabled),assigned=nodes.reduce((a,n)=>a+(n.inboundIds||[]).length,0),errors=nodes.filter(n=>n.last_error||(n.assignments||[]).some(x=>x.last_error));
 return `<section class="ov2-priority"><div class="ov2-section-head"><div><span class="eyebrow">02 / MULTI-NODE</span><h2>${L('Node fleet','ناوگان نودها')}</h2><p>${L('Central view of remote DARK agents and inbound assignment health.','نمای مرکزی Agentهای راه‌دور DARK و سلامت تخصیص Inboundها.')}</p></div><button class="btn btn-primary" data-act="ov2nodes">${icon('server')}${L('Manage nodes','مدیریت نودها')}</button></div><div class="ov2-node-summary"><div class="good"><span>${L('Online','آنلاین')}</span><b>${online.length}</b></div><div class="${offline.length?'bad':''}"><span>${L('Offline','آفلاین')}</span><b>${offline.length}</b></div><div><span>${L('Disabled','غیرفعال')}</span><b>${disabled.length}</b></div><div><span>${L('Assigned inbounds','اینباندهای تخصیص‌یافته')}</span><b>${assigned}</b></div><div class="${errors.length?'warn':''}"><span>${L('Sync errors','خطای Sync')}</span><b>${errors.length}</b></div></div>${nodes.length?`<div class="ov2-node-line">${nodes.slice(0,8).map(n=>{let bad=n.enabled&&!n.online,err=n.last_error||(n.assignments||[]).some(a=>a.last_error);return `<div class="${!n.enabled?'disabled':err?'warn':bad?'bad':'good'}"><i></i><span><b>${e(n.name||n.id)}</b><small>${e((n.inboundIds||[]).length+' '+L('inbounds','اینباند'))}${n.last_latency_ms?' · '+e(n.last_latency_ms)+' ms':''}</small></span></div>`;}).join('')}</div>`:empty(L('No remote nodes registered yet.','هنوز نود راه‌دوری ثبت نشده است.'))}</section>`;
}
function performancePanel(){
 let n=state.system?.engine||{},core=state.ov2.core||state.sync?.runtime||{},clients=state.clients||[],active=clients.filter(x=>x.client?.enable!==false&&!x.block_reasons?.length).length,blocked=clients.filter(x=>x.block_reasons?.length).length,total=clients.reduce((a,x)=>a+Number(x.used_bytes||0),0);
 return `<section class="ov2-performance"><div class="ov2-section-head"><div><span class="eyebrow">05 / LIVE OPERATIONS</span><h2>${L('Resources & activity','منابع و فعالیت')}</h2><p>${L('Routine host metrics and recent admin activity stay lower than operational controls.','آمار معمول سرور و فعالیت ادمین پایین‌تر از کنترل‌های عملیاتی قرار می‌گیرند.')}</p></div><button class="btn" data-act="syncnow">${icon('refresh')}${L('Reconcile now','همگام‌سازی')}</button></div><div class="ov2-grid">${kpi('CPU',n.cpu===undefined?'—':Number(n.cpu).toFixed(1)+'%','LOCAL HOST')}${kpi('RAM',percent(n.mem),`${bytes(n.mem?.current)} / ${bytes(n.mem?.total)}`)}${kpi(L('Network RX/s','دریافت شبکه'),bytes(n.netIO?.down))}${kpi(L('Network TX/s','ارسال شبکه'),bytes(n.netIO?.up))}</div><div class="ov2-grid">${kpi(L('Active clients','کاربران فعال'),fa(active),`${clients.length} total`)}${kpi(L('Observed traffic','مصرف ثبت‌شده'),bytes(total),`${blocked} blocked`)}${kpi(L('Inbounds','اینباندها'),fa(state.inbounds.length))}${kpi(L('Owners / resellers','مالک / نماینده'),fa(state.owners.length))}</div><div class="ov2-hero"><article class="panel"><div class="panel-head"><h2>${L('Recent admin activity','آخرین عملیات ادمین')}</h2>${button(L('Audit','گزارش'),'all-audit','log')}</div><div class="panel-body">${eventFeed()}</div></article><article class="panel"><div class="panel-head"><h2>${L('Runtime telemetry','تله‌متری Runtime')}</h2></div><div class="panel-body"><div class="xv2-kv"><div><span>PID</span><b>${e(core.pid||'—')}</b></div><div><span>${L('Uptime','آپ‌تایم')}</span><b>${n.uptime===undefined?'—':Math.floor(n.uptime/3600)+' h'}</b></div><div><span>${L('Last reconcile','آخرین همگام‌سازی')}</span><b>${state.sync?.last_poll?date(state.sync.last_poll):'—'}</b></div><div><span>${L('Blocked clients','کاربران محدود')}</span><b>${fa(blocked)}</b></div></div></div></article></div></section>`;
}
dashboard=function(){
 return heading(L('DARK Control Center','مرکز کنترل DARK'),L('Health, nodes, updates and recovery first; routine metrics last.','ابتدا سلامت، نودها، آپدیت و بازیابی؛ آمار معمول در انتهای صفحه.'))+notices()+`<div class="ov2 ov2-control-center">${healthPanel()}${nodesPanel()}<div id="dark-update-center-slot"></div>${maintenancePanel()}${performancePanel()}</div>`;
}
function maintenancePanel(){
 if(!isOwner())return '';
 const b=state.ov2.backup||{},core=state.ov2.core||state.sync?.runtime||{},dbHref=appUrl(b.database_download||'/api/backup');
 return `<section class="ov2-maintenance"><div class="ov2-maintenance-head"><div><span class="eyebrow">04 / BACKUP & RECOVERY</span><h2>${L('Backup & recovery','بکاپ و بازیابی')}</h2><p>${L('Backup and restore recovery live on the first page under the verified update workflow.','بکاپ و بازیابی در صفحه اول و زیر workflow تاییدشده آپدیت قرار دارند.')}</p></div></div><div class="ov2-maint-grid"><article class="panel ov2-maint-card"><div class="ov2-maint-icon">${icon('download')}</div><div><span class="ov2-maint-label">BACKUP</span><h3>${L('Backup & snapshots','بکاپ و اسنپ‌شات')}</h3><p>${L('Download a live database snapshot or start the encrypted full-backup workflow.','اسنپ‌شات زنده دیتابیس را دانلود کن یا بکاپ کامل رمزدار را اجرا کن.')}</p></div><div class="ov2-maint-kv"><div><span>${L('Database','دیتابیس')}</span><b>${b.database_bytes===undefined?'—':bytes(b.database_bytes)}</b></div><div><span>${L('Managed clients','کاربران')}</span><b>${b.managed_clients===undefined?'—':fa(b.managed_clients)}</b></div></div><div class="ov2-maint-actions"><a class="btn btn-primary" href="${dbHref}">${icon('download')}${L('Download DB snapshot','دانلود اسنپ‌شات DB')}</a><button class="btn" data-act="ov2backuphelp">${icon('shield')}${L('Encrypted full backup','بکاپ کامل رمزدار')}</button></div></article><article class="panel ov2-maint-card danger-zone"><div class="ov2-maint-icon">${icon('refresh')}</div><div><span class="ov2-maint-label">RESTORE / RECOVERY</span><h3>${L('Protected restore','ریستور محافظت‌شده')}</h3><p>${L('Encrypted restores stay isolated and require the backup passphrase from an interactive root terminal. Live data is never overwritten silently.','ریستور رمزدار ایزوله باقی می‌ماند و Passphrase را فقط در ترمینال تعاملی Root می‌گیرد. دیتای Live بی‌صدا جایگزین نمی‌شود.')}</p></div><div class="ov2-safe-state">${icon('shield')}<span>${b.restore_isolated===false?L('Isolation unavailable','ایزوله‌سازی در دسترس نیست'):L('Isolated restore enforced','ریستور ایزوله اجباری است')}</span></div><div class="ov2-maint-actions"><button class="btn" data-act="ov2restorehelp">${icon('terminal')}${L('Verify / Restore','Verify / Restore')}</button></div></article></div></section>`;
}
async function logsPage(){let kind=state.ov2.logKind;let data=await api('/api/logs/'+kind+'?limit=400');return heading('Logs',L('Read-only local runtime logs; secrets are not intentionally synthesized or expanded.','لاگ‌های محلی فقط‌خواندنی Runtime.'))+`<div class="ov2"><article class="panel" style="padding:12px"><div class="xv2-toolbar"><div class="ov2-logtabs">${[['process','Process'],['error','Xray Error'],['access','Access']].map(([k,l])=>`<button data-act="ov2logtab" data-kind="${k}" class="${kind===k?'active':''}">${l}</button>`).join('')}</div><div class="spacer"></div><span class="tag">${data.lines?.length||0}</span></div></article><pre class="ov2-terminal">${e((data.lines||[]).join('\n')||L('Log file is empty or does not exist yet.','فایل لاگ خالی است یا هنوز ساخته نشده.'))}</pre><div class="notice warning">${L('Access logs may contain customer IPs/identities. Do not publish them.','Access log ممکن است IP/هویت مشتری را داشته باشد؛ عمومی منتشر نکن.')}</div></div>`;}
async function backupPage(){let s=await api('/api/backup/status');return heading('Backup',L('Database export in web UI; encrypted full backup stays a terminal operation.','خروجی دیتابیس در Web؛ بکاپ کامل رمزدار در ترمینال باقی می‌ماند.'))+`<div class="ov2-backup"><article class="panel xv2-card"><h3>${L('Database snapshot','اسنپ‌شات دیتابیس')}</h3><p>${L('Download a point-in-time SQLite snapshot wrapped with a manifest.','دانلود اسنپ‌شات SQLite همراه Manifest.')}</p><div class="xv2-kv"><div><span>${L('Database size','حجم دیتابیس')}</span><b>${bytes(s.database_bytes||0)}</b></div><div><span>${L('Managed clients','کاربران مدیریت‌شده')}</span><b>${s.managed_clients}</b></div><div><span>${L('Audit rows','رویدادهای Audit')}</span><b>${s.audit_rows}</b></div></div><a class="btn btn-primary" href="${appUrl('/api/backup')}" style="margin-top:12px">${icon('download')}${L('Download DB backup','دانلود بکاپ DB')}</a></article><article class="panel xv2-card"><h3>${L('Encrypted full backup','بکاپ کامل رمزدار')}</h3><p>${L('Includes DARK data/config through the root-controlled backup workflow.','از مسیر کنترل‌شده Root برای دیتا/کانفیگ DARK استفاده می‌کند.')}</p><div class="ov2-command">sudo darkxray backup --output /root/dark-full.darkbackup</div><div class="notice" style="margin-top:12px">${L('Restore is intentionally isolated into a new directory; live data is never overwritten silently.','Restore عمداً در مسیر جدید انجام می‌شود و دیتای Live بی‌صدا overwrite نمی‌شود.')}</div></article></div>`;}
enginePage=async function(){if(state.page==='logs')return logsPage();if(state.page==='backup')return backupPage();return baseEnginePage();};
runAction=async function(act,el){
 if(act==='ov2logtab'){state.ov2.logKind=el.dataset.kind;await renderPage();return;}
 if(act==='all-audit'){await go('audit');return;}
 if(act==='ov2logs'){await go('logs');return;}
 if(act==='ov2nodes'){await go('nodes');return;}
 if(act==='ov2backuphelp'){dialog(L('Encrypted full backup','بکاپ کامل رمزدار'),`<div class="notice">${L('Passphrases are requested only by the interactive terminal and are never sent through the browser.','Passphrase فقط داخل ترمینال تعاملی دریافت می‌شود و هرگز از مرورگر ارسال نمی‌شود.')}</div><div class="ov2-command">sudo darkxray backup --output /root/dark-full.darkbackup</div>`);return;}
 if(act==='ov2restorehelp'){dialog(L('Verify / restore backup','Verify / Restore بکاپ'),`<div class="notice warning">${L('Always verify the archive first. Restore writes into a new isolated destination and does not replace the live installation.','همیشه اول آرشیو را Verify کن. Restore داخل مقصد ایزوله جدید نوشته می‌شود و نصب Live را جایگزین نمی‌کند.')}</div><div class="ov2-command">sudo darkxray backup-verify --archive /root/dark-full.darkbackup</div><div class="ov2-command" style="margin-top:8px">sudo darkxray restore --archive /root/dark-full.darkbackup --destination /root/dark-restore</div>`);return;}
 if(act==='ov2doctorhelp'){dialog(L('Doctor & production checks','Doctor و بررسی‌های Production'),`<div class="notice">${L('These checks are intentionally read-only from the browser surface. Run them over SSH when deeper host diagnostics are needed.','این بررسی‌ها عمداً از سطح مرورگر فقط‌خواندنی هستند. برای عیب‌یابی عمیق میزبان آن‌ها را از SSH اجرا کن.')}</div><div class="ov2-command">sudo darkxray doctor</div><div class="ov2-command" style="margin-top:8px">sudo darkxray vps-verify</div><div class="ov2-command" style="margin-top:8px">sudo darkxray production-gate</div>`);return;}
 return baseRunAction(act,el);
};
})();
