/* DARK XRAY Settings V2 — structured settings, staged privileged runtime changes. */
(function(){
'use strict';
if(typeof enginePage!=='function')return;
const baseEnginePage=enginePage;
const SV={tab:'general',data:null,logKind:'process'};
const L=(en,fa)=>((localStorage.getItem('dark_lang')||'en')==='fa'?fa:en);
const esc=v=>e(String(v??''));
const ico=n=>icon(n||'settings');
const list=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
const n=(v,d=0)=>{const x=Number(v);return Number.isFinite(x)?x:d;};
function segment(name,value,items){return `<div class="sv2-segment" data-sv2-segment="${esc(name)}"><input type="hidden" name="${esc(name)}" value="${esc(value)}">${items.map(([v,l])=>`<button type="button" data-sv2-action="segment" data-name="${esc(name)}" data-value="${esc(v)}" class="${String(v)===String(value)?'active':''}">${esc(l)}</button>`).join('')}</div>`;}
function field(label,name,value='',type='text',help='',attrs=''){return `<label class="sv2-field"><span>${esc(label)}</span><input name="${esc(name)}" type="${type}" value="${esc(value)}" ${attrs}>${help?`<small>${esc(help)}</small>`:''}</label>`;}
function toggle(label,name,on,help=''){return `<label class="sv2-toggle"><div><b>${esc(label)}</b>${help?`<small>${esc(help)}</small>`:''}</div><input type="hidden" name="${esc(name)}" value="${on?'true':'false'}"><button type="button" data-sv2-action="toggle" class="${on?'on':''}"><i></i></button></label>`;}
function card(title,sub,body,klass=''){return `<article class="panel sv2-card ${klass}"><div class="sv2-card-head"><div><h3>${esc(title)}</h3>${sub?`<p>${esc(sub)}</p>`:''}</div></div><div class="sv2-card-body">${body}</div></article>`;}
function saveButton(label=L('Save changes','ذخیره تغییرات')){return `<div class="sv2-form-actions"><button class="btn btn-primary" type="submit">${ico('check')}${esc(label)}</button></div>`;}
function tabs(){const items=[['general',L('General','عمومی'),'settings'],['security',L('Security','امنیت'),'shield'],['network',L('Network','شبکه'),'globe'],['tls',L('Domain / TLS','دامنه / TLS'),'lock'],['subscription',L('Subscription','اشتراک'),'link'],['ipguard',L('IP Guard','گارد IP'),'shield'],['appearance',L('Appearance','ظاهر'),'eye'],['operations',L('Operations','عملیات'),'log'],['system',L('System','سیستم'),'cpu']];return `<nav class="sv2-tabs">${items.map(([k,l,ic])=>`<button type="button" data-sv2-action="tab" data-tab="${k}" class="${SV.tab===k?'active':''}">${ico(ic)}<span>${esc(l)}</span></button>`).join('')}</nav>`;}
function applyPrefs(p={}){document.body.dataset.darkDensity=p.density||'comfortable';document.body.classList.toggle('dark-reduced-motion',!!p.reduced_motion);document.title=(p.title||'DARK XRAY')+L(' | Cyber Control Center',' | مرکز کنترل سایبری');}
async function fetchData(){
 const req=[['panel','/api/settings/panel'],['runtime','/api/settings/runtime'],['subscription','/api/settings/subscription'],['subscriptionStatus','/api/subscription/status'],['guard','/api/settings/ipguard'],['runtimeStatus','/api/runtime-config'],['core','/api/core/state']];
 const out={};await Promise.all(req.map(async([k,u])=>{try{const r=await api(u);out[k]=r.value??r;}catch(ex){out[k]={error:ex.message};}}));
 if(SV.tab==='operations'){
  try{out.logs=await api('/api/logs/'+SV.logKind+'?limit=400');}catch(ex){out.logs={lines:[],error:ex.message};}
  try{out.audit=await api('/api/audit');}catch(ex){out.audit={error:ex.message,items:[]};}
 }
 SV.data=out;applyPrefs(out.panel);return out;
}
function pending(status){const keys=Object.keys(status?.pending||{});if(!keys.length)return `<span class="sv2-state ok">${ico('check')}${L('Applied','اعمال‌شده')}</span>`;return `<span class="sv2-state warn">${ico('alert')}${keys.length} ${L('pending root changes','تغییر در انتظار دسترسی روت')}</span>`;}
function diff(status){const rows=Object.entries(status?.pending||{});if(!rows.length)return `<div class="sv2-empty-inline">${L('No privileged runtime changes are pending.','هیچ تغییر سیستمی در انتظار اعمال نیست.')}</div>`;return `<div class="sv2-diff">${rows.map(([k,v])=>`<div><b>${esc(k)}</b><code>${esc(v.from)} → ${esc(v.to)}</code></div>`).join('')}</div>`;}
function general(d){const p=d.panel;return `<form class="sv2-grid" data-sv2-form="panel-general">${card(L('Panel identity','هویت پنل'),L('Display and operator metadata.','اطلاعات نمایشی و مدیریتی.'),`<div class="sv2-form-grid">${field(L('Panel title','عنوان پنل'),'title',p.title||'DARK XRAY','text','', 'maxlength="80" required')}${field(L('Support URL','لینک پشتیبانی'),'support_url',p.support_url||'','url','', 'dir="ltr" placeholder="https://..."')}</div>`)}${card(L('Regional behavior','تنظیمات منطقه‌ای'),L('Saved server-side; English remains the clean default.','در سرور ذخیره می‌شود؛ انگلیسی پیش‌فرض تمیز پنل است.'),`<div class="sv2-form-grid"><label class="sv2-field"><span>${L('Default language','زبان پیش‌فرض')}</span>${segment('language',p.language||'en',[['en',L('English','انگلیسی')],['fa',L('Persian','فارسی')]])}</label>${field(L('Timezone','منطقه زمانی'),'timezone',p.timezone||'UTC','text',L('IANA name, e.g. Asia/Tehran','نام IANA مثل Asia/Tehran'),'dir="ltr"')}${field(L('Rows per page','تعداد ردیف صفحه'),'page_size',p.page_size||50,'number','', 'min="10" max="1000" required')}<label class="sv2-field"><span>${L('Calendar','تقویم')}</span>${segment('datepicker',p.datepicker||'gregorian',[['gregorian',L('Gregorian','میلادی')],['jalalian',L('Jalalian','جلالی')]])}</label></div>`) }${saveButton()}</form>`;}
function security(d){const p=d.panel;return `<form class="sv2-grid" data-sv2-form="security">${card(L('Session policy','سیاست نشست'),L('Changing this affects new logins; current sessions are not extended.','تغییر این مقدار روی ورودهای جدید اثر دارد.'),`<div class="sv2-form-grid">${field(L('Session lifetime (minutes)','عمر نشست (دقیقه)'),'session_max_age_minutes',p.session_max_age_minutes||480,'number','', 'min="60" max="525600" required')}</div>`)}${card(L('Account protection','محافظت حساب'),L('TOTP, password and API keys live in the dedicated account center.','TOTP، رمز و کلیدهای API در مرکز امنیت حساب مدیریت می‌شوند.'),`<div class="sv2-security-summary"><span>${ico('shield')}TOTP: <b>${state.me?.totp_enabled?L('Enabled','فعال'):L('Disabled','غیرفعال')}</b></span><button type="button" class="btn" data-sv2-action="account">${ico('lock')}${L('Open Account & Security','بازکردن حساب و امنیت')}</button></div>`) }${saveButton()}</form>`;}
function network(d){const r=d.runtime,s=d.runtimeStatus;return `<form class="sv2-grid" data-sv2-form="runtime-network">${card(L('Public proxy identity','هویت عمومی پروکسی'),L('Address used when DARK builds customer links.','آدرسی که DARK در لینک مشتری قرار می‌دهد.'),`<div class="sv2-form-grid">${field(L('Public proxy IP / DNS','IP / دامنه عمومی پروکسی'),'public_address',r.public_address||'','text','', 'required dir="ltr"')}${field(L('Panel port','پورت پنل'),'bind_port',r.bind_port||2087,'number',L('Root apply is required after staging.','بعد از ذخیره نیاز به اعمال با روت دارد.'),'min="1024" max="65535" required')}${field(L('Panel URI path','مسیر URI پنل'),'panel_path',r.panel_path||'/','text',L('Example: /dark-admin. Reserved: /api, /assets, /sub, /node, /health.','مثال: /dark-admin. مسیرهای /api، /assets، /sub، /node و /health رزرو هستند.'),'dir="ltr" maxlength="200" required')}<button type="button" class="btn" data-sv2-action="random-path">${ico('refresh')}${L('Generate random path','ساخت مسیر تصادفی')}</button></div>`)}${card(L('Runtime behavior','رفتار محیط اجرا'),L('Safe values are staged in DARK DB first.','ابتدا به‌صورت امن در دیتابیس DARK ذخیره می‌شوند.'),`<div class="sv2-form-grid">${field(L('Poll interval (seconds)','فاصله Poll (ثانیه)'),'poll_seconds',r.poll_seconds||5,'number','', 'min="1" max="3600" required')}<div class="sv2-span-2">${toggle(L('Autostart Xray core','اجرای خودکار Xray Core'),'core_autostart',!!r.core_autostart,L('Starts the child core when DARK service starts.','با شروع سرویس DARK هسته Xray را اجرا می‌کند.'))}</div></div>`)}${card(L('Privileged apply status','وضعیت اعمال سیستمی'),'','<div class="sv2-status-row">'+pending(s)+'</div>'+diff(s)+`<div class="sv2-command"><code>${esc(s.apply_command||'sudo darkxray settings-apply')}</code></div>`,'sv2-span-2')}${saveButton(L('Stage network changes','ذخیره تغییرات شبکه'))}</form>`;}
function tls(d){const r=d.runtime,s=d.runtimeStatus,a=s.actual||{};return `<form class="sv2-grid" data-sv2-form="runtime-tls">${card(L('Panel exposure mode','حالت دسترسی پنل'),L('SSH mode stays loopback-only. Domain mode requires real TLS.','حالت SSH فقط روی لوپ‌بک می‌ماند؛ حالت دامنه TLS واقعی می‌خواهد.'),`<label class="sv2-field sv2-span-2"><span>${L('Access mode','حالت دسترسی')}</span>${segment('access_mode',r.access_mode||'ssh',[['ssh',L('SSH Tunnel','تونل SSH')],['domain_tls',L('Domain + HTTPS/TLS','دامنه + HTTPS/TLS')]])}</label><div class="sv2-form-grid" data-sv2-domain-fields ${r.access_mode==='domain_tls'?'':'hidden'}>${field(L('Panel domain','دامنه پنل'),'domain',r.domain||'','text','', 'dir="ltr" placeholder="panel.example.com"')}${field(L('ACME email','ایمیل ACME'),'acme_email',r.acme_email||'','email','', 'dir="ltr" placeholder="admin@example.com"')}</div>`)}${card(L('Current TLS state','وضعیت فعلی TLS'),'',`<div class="sv2-kv"><div><span>${L('Origin','مبدأ')}</span><b class="mono">${esc(a.public_origin||'—')}</b></div><div><span>TLS</span><b>${a.tls_enabled?L('Enabled','فعال'):L('Disabled','غیرفعال')}</b></div><div><span>${L('Certificate','گواهی')}</span><b class="mono">${esc(a.tls_certificate||'—')}</b></div><div><span>${L('Secure cookie','کوکی امن')}</span><b>${a.secure_cookie?L('Yes','بله'):L('No','خیر')}</b></div></div>`)}${card(L('Apply boundary','مرز اعمال'),L('Root-owned listener changes are intentionally not performed by the web process.','تغییرات Listener که متعلق به root هستند عمداً توسط Web process انجام نمی‌شوند.'),diff(s)+`<div class="notice warning">${L('After staging, run the command below from SSH. Domain mode will use Certbot and may restart DARK/Xray.','بعد از ذخیره، دستور زیر را در SSH اجرا کن. حالت دامنه از Certbot استفاده می‌کند و ممکن است DARK/Xray ری‌استارت شود.')}</div><div class="sv2-command"><code>${esc(s.apply_command||'sudo darkxray settings-apply')}</code></div>`,'sv2-span-2')}${saveButton(L('Stage domain / TLS changes','ذخیره تغییرات دامنه / TLS'))}</form>`;}
function subFormatCard(name,desc,badge=''){return `<div class="sv3-format"><div><b>${esc(name)}</b>${badge?`<span>${esc(badge)}</span>`:''}</div><small>${esc(desc)}</small></div>`;}
function subStat(label,value,help=''){return `<div class="sv3-substat"><span>${esc(label)}</span><b>${esc(value)}</b>${help?`<small>${esc(help)}</small>`:''}</div>`;}
function subscription(d){
 const s=d.subscription,st=d.subscriptionStatus||{},dev=st.device_policy||{},actual=d.runtimeStatus?.actual||{};
 const base=st.base_url||((actual.public_origin||'')+(s.path||'/sub')+'/<token>');
 const resolver=s.auto_detect!==false
   ?L('No ?format: Clash/Mihomo User-Agent → Clash; everything else → default format.','بدون ?format: User-Agent کلش/میهومو → Clash؛ بقیه → فرمت پیش‌فرض.')
   :L('No ?format: always uses the default format. Explicit ?format always wins.','بدون ?format همیشه فرمت پیش‌فرض استفاده می‌شود؛ ?format صریح همیشه اولویت دارد.');
 const remark=(st.remark_preview||String(s.remark_template||'{remark} | {email}').replace('{remark}','TURKEY FAST').replace('{email}','customer@example').replace('{protocol}','VLESS'));
 return `<form class="sv2-grid sv3-subscription" data-sv2-form="subscription" data-sub-origin="${esc(actual.public_origin||'')}">
 ${card(L('Live subscription endpoint','نقطه اتصال زندهٔ اشتراک'),L('This is the public customer feed. Path changes apply immediately and invalidate old distributed URLs.','این Feed عمومی مشتری است؛ تغییر مسیر فوری اعمال می‌شود و لینک‌های قبلی را نامعتبر می‌کند.'),`
   <div class="sv2-span-2">${toggle(L('Enable customer subscription','فعال‌سازی اشتراک مشتری'),'enabled',s.enabled!==false,L('When off, subscription requests return 404 before any device registration is attempted.','وقتی خاموش باشد درخواست اشتراک قبل از ثبت دستگاه با 404 پاسخ می‌گیرد.'))}</div>
   <div class="sv3-live-url"><span>${L('Effective customer URL','آدرس مؤثر مشتری')}</span><code data-sub-url>${esc(base)}</code></div>
   <div class="sv2-form-grid">
     ${field(L('Subscription URI path','مسیر URI اشتراک'),'path',s.path||'/sub','text',L('Use a hard-to-guess path. Changing it breaks previously shared subscription URLs.','مسیر غیرقابل‌حدس انتخاب کن؛ تغییر آن لینک‌های قبلی را می‌شکند.'),'dir="ltr" maxlength="200" required')}
     <div class="sv3-inline-button"><button type="button" class="btn" data-sv2-action="random-sub-path">${ico('refresh')}${L('Generate random path','ساخت مسیر تصادفی')}</button></div>
     <label class="sv2-field"><span>${L('Default format','فرمت پیش‌فرض')}</span>${segment('default_format',s.default_format||'base64',[['base64','Base64'],['raw','Raw'],['clash','Clash / Mihomo'],['json','DARK JSON']])}</label>
     ${field(L('Profile update interval (hours)','بازه آپدیت پروفایل (ساعت)'),'profile_update_interval_hours',s.profile_update_interval_hours||6,'number',L('Sent as profile-update-interval.','در سرآیند با نام فنی profile-update-interval ارسال می‌شود.'),'min="1" max="168" required')}
     <div class="sv2-span-2">${toggle(L('Auto detect Clash / Mihomo','تشخیص خودکار Clash / Mihomo'),'auto_detect',s.auto_detect!==false,L('Only Clash/Mihomo User-Agent detection exists; other apps use the default format unless ?format is specified.','فقط User-Agent کلش/میهومو تشخیص داده می‌شود؛ بقیه برنامه‌ها فرمت پیش‌فرض می‌گیرند مگر ?format صریح باشد.'))}</div>
   </div>
   <div class="sv3-resolver"><span>${L('FORMAT RESOLUTION','انتخاب فرمت')}</span><b data-sub-resolver>${esc(resolver)}</b></div>`,'sv2-span-2')}
 ${card(L('Output formats','فرمت‌های خروجی'),L('These are real generators in DARK; explicit ?format overrides auto-detection.','این‌ها مولدهای واقعی DARK هستند و پارامتر فنی ?format بر تشخیص خودکار اولویت دارد.'),`
   <div class="sv3-formats">
    ${subFormatCard('Base64',L('Base64-encoded newline-separated share links.','لینک‌های Share خط‌به‌خط با Base64.'),s.default_format==='base64'?L('DEFAULT','پیش‌فرض'):'')}
    ${subFormatCard('Raw',L('Plain newline-separated share links.','لینک‌های Share به‌صورت متن ساده.'),s.default_format==='raw'?L('DEFAULT','پیش‌فرض'):'')}
    ${subFormatCard('Clash / Mihomo',L('Generated YAML with DARK AUTO / FAILOVER groups when node routes are available.','YAML با گروه DARK AUTO / FAILOVER وقتی مسیر نود آماده باشد.'),s.default_format==='clash'?L('DEFAULT','پیش‌فرض'):'')}
    ${subFormatCard('DARK JSON',L('Structured DARK output; Announcement is included here in the response body.','خروجی ساختاریافته DARK؛ Announcement فقط در body این فرمت قرار می‌گیرد.'),s.default_format==='json'?L('DEFAULT','پیش‌فرض'):'')}
   </div>`,'sv2-span-2')}
 ${card(L('Profile headers','Headerهای پروفایل'),L('Metadata compatible clients receive with every successful subscription response.','متادیتایی که همراه هر پاسخ موفق اشتراک ارسال می‌شود.'),`
   <div class="sv2-form-grid">
     ${field(L('Profile title','عنوان پروفایل'),'profile_title',s.profile_title||'DARK XRAY','text','profile-title','maxlength="120" required')}
     ${field(L('Profile page URL','لینک صفحه پروفایل'),'profile_url',s.profile_url||'','url','profile-web-page-url','dir="ltr"')}
     ${field(L('Support URL','لینک پشتیبانی'),'support_url',s.support_url||'','url','support-url','dir="ltr"')}
   </div>
   <div class="sv3-header-list">
    <code>profile-title: ${esc(s.profile_title||'DARK XRAY')}</code>
    <code>profile-update-interval: ${esc(s.profile_update_interval_hours||6)}</code>
    <code>subscription-userinfo: ${L('global local + node traffic','ترافیک سراسری محلی + نود')}</code>
    ${s.support_url?`<code>support-url: ${esc(s.support_url)}</code>`:''}
    ${s.profile_url?`<code>profile-web-page-url: ${esc(s.profile_url)}</code>`:''}
   </div>`)}
 ${card(L('Link naming & announcement','نام‌گذاری لینک و اعلان'),L('Naming affects every generated config. Announcement is body metadata in DARK JSON only.','نام‌گذاری روی همه کانفیگ‌ها اثر دارد؛ Announcement فقط متادیتای body در DARK JSON است.'),`
   <div class="sv2-form-grid">
     ${field(L('Remark template','قالب نام'),'remark_template',s.remark_template||'{remark} | {email}','text',L('Variables: {remark}, {email}, {protocol}','متغیرها: {remark}، {email}، {protocol}'),'maxlength="200" required')}
     <div class="sv3-remark-preview"><span>${L('PREVIEW','پیش‌نمایش')}</span><b data-sub-remark-preview>${esc(remark)}</b></div>
     <label class="sv2-field sv2-span-2"><span>${L('DARK JSON announcement','اعلان DARK JSON')}</span><textarea class="field-input" name="announce" maxlength="2000" rows="3">${esc(s.announce||'')}</textarea><small>${L('Included in DARK JSON body only; standard Raw/Base64/Clash clients do not receive this text.','فقط داخل body خروجی DARK JSON است؛ کلاینت‌های Raw/Base64/Clash این متن را دریافت نمی‌کنند.')}</small></label>
   </div>`)}
 ${card(L('Device / HWID delivery policy','سیاست Device / HWID اشتراک'),L('HWID is per-client, not a global subscription toggle.','HWID برای هر کاربر جداست و کلید سراسری اشتراک نیست.'),`
   <div class="sv3-substats">
    ${subStat(L('Managed clients','کاربران مدیریت‌شده'),fa(dev.managed_clients||0))}
    ${subStat(L('HWID-limited clients','کاربران با محدودیت HWID'),fa(dev.clients_with_hwid_limit||0),L('These clients require x-hwid on subscription access.','این کاربران هنگام دریافت اشتراک x-hwid لازم دارند.'))}
    ${subStat(L('Registered devices','دستگاه‌های ثبت‌شده'),fa(dev.registered_devices||0))}
    ${subStat(L('At device limit','در سقف دستگاه'),fa(dev.clients_at_device_limit||0))}
   </div>
   <div class="notice">${L('If limitHwid = 0, no device header is required. If limitHwid > 0, a compatible client must send x-hwid; x-device-os and x-device-model are optional metadata.','اگر limitHwid صفر باشد Header دستگاه لازم نیست. اگر بیشتر از صفر باشد کلاینت سازگار باید x-hwid بفرستد؛ x-device-os و x-device-model فقط متادیتای اختیاری هستند.')}</div>
   <div class="sv2-inline-actions"><button type="button" class="btn" data-sv2-action="subscription-clients">${ico('users')}${L('Open Clients / HWID limits','بازکردن کاربران / محدودیت HWID')}</button></div>`,'sv2-span-2')}
 ${saveButton(L('Save customer output policy','ذخیره سیاست خروجی مشتری'))}</form>`;
}
function ipguard(d){const g=d.guard,st=d.runtimeStatus;return `<form class="sv2-grid" data-sv2-form="ipguard">
${card('DARK Native IP Guard',L('Observe first; local nftables enforcement is allowed only after direct packet-source verification.','ابتدا در حالت مشاهده؛ اعمال محلی nftables فقط بعد از تأیید مبدأ واقعی بسته مجاز است.'),`<div class="sv2-form-grid"><label class="sv2-field"><span>${L('Mode','حالت')}</span>${segment('mode',g.mode||'observe',[['observe',L('Observe','مشاهده')],['enforce',L('Enforce','اعمال')]])}</label>${field(L('Activity window (seconds)','پنجره فعالیت (ثانیه)'),'window_seconds',g.window_seconds||120,'number',L('Distinct verified source IPs inside this rolling window are counted.','IPهای متمایز تأییدشده در این بازه شمرده می‌شوند.'), 'min="10" max="3600" required')}${field(L('Local ban duration (seconds)','مدت بن محلی (ثانیه)'),'ban_seconds',g.ban_seconds||1800,'number',L('Applied only by the DARK root-owned nftables broker on this host.','فقط توسط کارگزار روت DARK روی nftables همین سرور اعمال می‌شود.'), 'min="10" max="86400" required')}${field(L('Exempt IP / CIDR list','IP / CIDRهای معاف'),'exempt_ips',(g.exempt_ips||[]).join(', '),'text','Comma separated','dir="ltr"')}</div>`)}
${card(L('Source & enforcement boundary','مرز مبدأ و اعمال'),'','<div class="sv2-kv"><div><span>'+L('Direct source verified','مبدأ مستقیم تأیید شده')+'</span><b>'+(st.actual?.direct_source_verified?L('Yes','بله'):L('No','خیر'))+'</b></div><div><span>'+L('Native backend','هستهٔ پشتیبان بومی')+'</span><b>nftables</b></div><div><span>'+L('Local firewall scope','محدوده فایروال محلی')+'</span><b>'+L('Approved Xray data ports','پورت‌های دیتای تأییدشده Xray')+'</b></div><div><span>'+L('Multi-node policy','سیاست چندنودی')+'</span><b>'+L('Central client block','بلاک مرکزی کاربر')+'</b></div></div><div class="notice warning">'+L('If a tunnel hides the real packet source on this host, keep local Enforce off. Global Local+Node policy still relies only on fresh verified telemetry and never invents a remote firewall ban.','اگر تانل مبدأ واقعی بسته را روی این سرور مخفی می‌کند، اعمال محلی را خاموش نگه دار. سیاست سراسری محلی+نود فقط روی تله‌متری تازه و تأییدشده تصمیم می‌گیرد و هیچ بن فایروال راه‌دور ساختگی ایجاد نمی‌کند.')+'</div><div class="sv2-inline-actions"><button type="button" class="btn" data-sv2-action="security-center">'+ico('shield')+L('Open Security Center','بازکردن مرکز امنیت')+'</button></div>')}
${saveButton(L('Save Native Guard policy','ذخیره سیاست گارد بومی'))}</form>`;}
function appearance(d){const p=d.panel;return `<form class="sv2-grid" data-sv2-form="appearance">${card(L('Cyber appearance','ظاهر سایبری'),L('DARK keeps a focused dark theme; only useful density/motion controls are exposed.','DARK تم تاریک متمرکز را حفظ می‌کند و فقط کنترل‌های کاربردی نمایش داده می‌شوند.'),`<div class="sv2-form-grid"><label class="sv2-field"><span>${L('Density','تراکم')}</span>${segment('density',p.density||'comfortable',[['comfortable',L('Comfortable','راحت')],['compact',L('Compact','فشرده')]])}</label><div class="sv2-span-2">${toggle(L('Reduce motion','کاهش انیمیشن'),'reduced_motion',!!p.reduced_motion,L('Disables non-essential cyber animations.','انیمیشن‌های غیرضروری سایبری را کم می‌کند.'))}</div></div>`)}${saveButton()}</form>`;}
function operations(d){
 const log=d.logs||{},audit=Array.isArray(d.audit)?d.audit:[],logKinds=[['process','Process'],['error','Xray Error'],['access','Access']];
 const tabs='<div class="sv2-op-tabs">'+logKinds.map(([k,l])=>'<button type="button" data-sv2-action="log-kind" data-kind="'+k+'" class="'+(SV.logKind===k?'active':'')+'">'+esc(l)+'</button>').join('')+'</div>';
 const logBody=(log.error?'<div class="notice error">'+esc(log.error)+'</div>':'')+tabs+'<pre class="sv2-terminal">'+esc((log.lines||[]).join('\n')||L('Log file is empty or does not exist yet.','فایل لاگ خالی است یا هنوز ساخته نشده.'))+'</pre>'+(SV.logKind==='access'?'<div class="notice warning">'+L('Access logs may contain customer IPs or identities. Do not publish them.','لاگ دسترسی ممکن است IP یا هویت مشتری را داشته باشد؛ آن را عمومی منتشر نکن.')+'</div>':'');
 const auditRows=audit.slice(0,150);
 const auditBody=(d.audit?.error?'<div class="notice error">'+esc(d.audit.error)+'</div>':'')+(auditRows.length?'<div class="table-wrap"><table class="sv2-audit-table"><thead><tr><th>'+L('Time','زمان')+'</th><th>'+L('Actor','عامل')+'</th><th>'+L('Action','عملیات')+'</th><th>'+L('Target','هدف')+'</th><th>'+L('Detail','جزئیات')+'</th></tr></thead><tbody>'+auditRows.map(r=>'<tr><td>'+esc(date(r.at))+'</td><td class="mono">'+esc(r.actor||'—')+'</td><td>'+esc(r.action||'—')+'</td><td class="mono">'+esc(r.target||'—')+'</td><td>'+esc(r.detail||'')+'</td></tr>').join('')+'</tbody></table></div>':'<div class="sv2-empty-inline">'+L('No operation events recorded yet.','هنوز رویداد عملیاتی ثبت نشده است.')+'</div>');
 return '<div class="sv2-grid sv2-operations">'+card(L('Runtime logs','لاگ‌های محیط اجرا'),L('Read-only local logs for DARK/Xray diagnostics.','لاگ‌های محلی فقط‌خواندنی برای عیب‌یابی DARK/Xray.'),logBody,'sv2-span-2')+card(L('Operation report / Audit','گزارش عملیات'),L('Owner activity and security-sensitive changes from the immutable audit trail.','فعالیت مالک و تغییرات حساس از مسیر گزارش ماندگار.'),auditBody,'sv2-span-2')+'</div>';
}
function system(d){const c=d.core,s=d.runtimeStatus,a=s.actual||{};return `<div class="sv2-grid">${card(L('DARK service','سرویس DARK'),'','<div class="sv2-kv"><div><span>'+L('Xray state','وضعیت Xray')+'</span><b>'+esc(c.state||'—')+'</b></div><div><span>PID</span><b class="mono">'+esc(c.pid||'—')+'</b></div><div><span>'+L('Core version','نسخه هسته')+'</span><b class="mono">'+esc(c.version||'—')+'</b></div><div><span>'+L('Dirty config','تنظیمات اعمال‌نشده')+'</span><b>'+(c.dirty?L('Yes','بله'):L('No','خیر'))+'</b></div></div><div class="sv2-inline-actions"><button class="btn" type="button" data-sv2-action="core-validate">'+ico('check')+L('Validate Xray','اعتبارسنجی Xray')+'</button><button class="btn danger" type="button" data-sv2-action="core-restart">'+ico('refresh')+L('Restart / Apply','ری‌استارت / اعمال')+'</button></div>')}${card(L('Root-owned runtime','محیط اجرا تحت مالکیت روت'),'','<div class="sv2-kv"><div><span>'+L('Bind','اتصال شنونده')+'</span><b class="mono">'+esc(a.bind_host||'—')+':'+esc(a.bind_port||'—')+'</b></div><div><span>'+L('Public origin','مبدأ عمومی')+'</span><b class="mono">'+esc(a.public_origin||'—')+'</b></div><div><span>Xray API</span><b class="mono">'+esc(a.xray_api_port||'—')+'</b></div><div><span>'+L('Pending changes','تغییرات در انتظار')+'</span><b>'+Object.keys(s.pending||{}).length+'</b></div></div>'+diff(s)+'<div class="sv2-command"><code>'+esc(s.apply_command||'sudo darkxray settings-apply')+'</code></div>')}</div>`;}
function body(d){if(d.panel?.error||d.runtime?.error)return `<div class="notice error">${esc(d.panel?.error||d.runtime?.error)}</div>`;return {general,security,network,tls,subscription,ipguard,appearance,operations,system}[SV.tab](d);}
async function page(){const d=await fetchData();return heading(L('Settings','تنظیمات'),L('One control center for DARK UI, subscription, network staging, TLS and system state.','یک مرکز کنترل برای رابط کاربری، اشتراک، شبکه، TLS و وضعیت سیستم.'))+`<div class="settings-v2">${tabs()}<section class="sv2-content">${body(d)}</section></div>`;}
enginePage=async function(){if(state.page==='settings')return page();return baseEnginePage();};
function formValue(form,name){return form.elements[name]?.value??'';}
async function savePanel(form,kind){const old={...(SV.data.panel||{})};let languageChanged=false;if(kind==='panel-general'){old.title=formValue(form,'title').trim();old.support_url=formValue(form,'support_url').trim();old.language=formValue(form,'language');old.timezone=formValue(form,'timezone').trim();old.datepicker=formValue(form,'datepicker');languageChanged=(localStorage.getItem('dark_lang')||'en')!==old.language;localStorage.setItem('dark_lang',old.language);}else if(kind==='security'){old.session_max_age_minutes=n(formValue(form,'session_max_age_minutes'),480);}else{old.density=formValue(form,'density');old.reduced_motion=formValue(form,'reduced_motion')==='true';document.body.dataset.darkDensity=old.density;document.body.classList.toggle('dark-reduced-motion',old.reduced_motion);}await api('/api/settings/panel','PUT',{value:old});if(state.me)state.me.ui={...old};applyPrefs(old);toast(L('Settings saved.','تنظیمات ذخیره شد.'));if(languageChanged)location.reload();}
async function saveRuntime(form,kind){const old={...(SV.data.runtime||{})};if(kind==='runtime-network'){old.public_address=formValue(form,'public_address').trim();old.bind_port=n(formValue(form,'bind_port'));old.panel_path=formValue(form,'panel_path').trim()||'/';old.poll_seconds=n(formValue(form,'poll_seconds'));old.core_autostart=formValue(form,'core_autostart')==='true';}else{old.access_mode=formValue(form,'access_mode');if(old.access_mode==='ssh'){old.domain='';old.acme_email='';}else{old.domain=formValue(form,'domain').trim();old.acme_email=formValue(form,'acme_email').trim();}}await api('/api/settings/runtime','PUT',{value:old});toast(L('Privileged changes staged. Apply from SSH with darkxray settings-apply.','تغییرات سیستمی ذخیره شد؛ از SSH با darkxray settings-apply اعمال کن.'));}
function syncSubscriptionPreview(form){
 if(!form?.matches?.('[data-sv2-form="subscription"]'))return;
 const path=String(form.elements.path?.value||'/sub').trim()||'/sub',origin=String(form.dataset.subOrigin||'').replace(/\/$/,'');
 const url=form.querySelector('[data-sub-url]');if(url)url.textContent=origin+path+'/<token>';
 const tmpl=String(form.elements.remark_template?.value||'{remark} | {email}');
 const remark=form.querySelector('[data-sub-remark-preview]');if(remark)remark.textContent=tmpl.replaceAll('{remark}','TURKEY FAST').replaceAll('{email}','customer@example').replaceAll('{protocol}','VLESS');
 const auto=form.elements.auto_detect?.value!=='false',fmt=form.elements.default_format?.value||'base64';
 const resolver=form.querySelector('[data-sub-resolver]');if(resolver)resolver.textContent=auto
  ?L('No ?format: Clash/Mihomo User-Agent → Clash; everything else → '+fmt+'.','بدون ?format: User-Agent کلش/میهومو → Clash؛ بقیه → '+fmt+'.')
  :L('No ?format: '+fmt+'. Explicit ?format always wins.','بدون ?format: '+fmt+'؛ ?format صریح همیشه اولویت دارد.');
}
async function saveSubscription(form){const s={...(SV.data.subscription||{})};s.enabled=formValue(form,'enabled')==='true';s.default_format=formValue(form,'default_format');s.auto_detect=formValue(form,'auto_detect')==='true';s.profile_update_interval_hours=n(formValue(form,'profile_update_interval_hours'),6);s.path=formValue(form,'path').trim()||'/sub';s.remark_template=formValue(form,'remark_template');s.support_url=formValue(form,'support_url').trim();s.profile_title=formValue(form,'profile_title').trim();s.profile_url=formValue(form,'profile_url').trim();s.announce=formValue(form,'announce').trim();await api('/api/settings/subscription','PUT',{value:s});toast(L('Subscription settings saved.','تنظیمات اشتراک ذخیره شد.'));}
async function saveGuard(form){const g={mode:formValue(form,'mode'),window_seconds:n(formValue(form,'window_seconds')),ban_seconds:n(formValue(form,'ban_seconds')),exempt_ips:list(formValue(form,'exempt_ips'))};await api('/api/settings/ipguard','PUT',{value:g});toast(L('IP Guard settings saved.','تنظیمات IP Guard ذخیره شد.'));}
document.addEventListener('click',async ev=>{const el=ev.target.closest('[data-sv2-action]');if(!el)return;const act=el.dataset.sv2Action;try{if(act==='tab'){SV.tab=el.dataset.tab;await renderPage();return;}if(act==='log-kind'){SV.logKind=el.dataset.kind;SV.data=null;await renderPage();return;}if(act==='segment'){const box=el.closest('[data-sv2-segment]');box.querySelector('input[type=hidden]').value=el.dataset.value;box.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===el));if(el.dataset.name==='access_mode'){const f=el.closest('form');f.querySelector('[data-sv2-domain-fields]').hidden=el.dataset.value!=='domain_tls';}syncSubscriptionPreview(el.closest('form'));return;}if(act==='toggle'){el.classList.toggle('on');el.parentElement.querySelector('input[type=hidden]').value=el.classList.contains('on')?'true':'false';syncSubscriptionPreview(el.closest('form'));return;}if(act==='account'){await go('account');return;}if(act==='security-center'){await go('ipguard');return;}if(act==='random-path'){const bytes=new Uint8Array(12);crypto.getRandomValues(bytes);const token=Array.from(bytes,x=>x.toString(16).padStart(2,'0')).join('');const form=el.closest('form');if(form?.elements?.panel_path)form.elements.panel_path.value='/dark-'+token;return;}if(act==='random-sub-path'){const bytes=new Uint8Array(12);crypto.getRandomValues(bytes);const token=Array.from(bytes,x=>x.toString(16).padStart(2,'0')).join('');const form=el.closest('form');if(form?.elements?.path){form.elements.path.value='/feed-'+token;syncSubscriptionPreview(form);}return;}if(act==='subscription-clients'){await go('clients');return;}if(act==='core-validate'){await api('/api/core/validate','POST',{});toast(L('Xray validation passed.','اعتبارسنجی Xray موفق بود.'));return;}if(act==='core-restart'){if(confirm(L('Restart DARK Xray now? Active proxy sessions may disconnect.','Xray ری‌استارت شود؟ اتصال‌های فعال ممکن است قطع شوند.'))){await api('/api/core/restart','POST',{});toast(L('Xray restarted.','Xray ری‌استارت شد.'));await refresh();}return;}}catch(ex){toast(ex.message,true);}});
document.addEventListener('input',ev=>{const form=ev.target.closest?.('[data-sv2-form="subscription"]');if(form)syncSubscriptionPreview(form);});
document.addEventListener('change',ev=>{const form=ev.target.closest?.('[data-sv2-form="subscription"]');if(form)syncSubscriptionPreview(form);});
globalThis.DarkSettingsV2={open:async function(tab='general'){SV.tab=tab;SV.data=null;await go('settings');}};
document.addEventListener('submit',async ev=>{const form=ev.target.closest('[data-sv2-form]');if(!form)return;ev.preventDefault();const kind=form.dataset.sv2Form,b=form.querySelector('button[type=submit]');if(b)b.disabled=true;try{if(kind==='panel-general'||kind==='security'||kind==='appearance')await savePanel(form,kind);else if(kind.startsWith('runtime-'))await saveRuntime(form,kind);else if(kind==='subscription')await saveSubscription(form);else if(kind==='ipguard')await saveGuard(form);SV.data=null;await renderPage();}catch(ex){toast(ex.message,true);}finally{if(b?.isConnected)b.disabled=false;}});
})();
