/* DARK XRAY Settings V2 — structured settings, staged privileged runtime changes. */
(function(){
'use strict';
if(typeof enginePage!=='function')return;
const baseEnginePage=enginePage;
const SV={tab:'general',data:null};
const L=(en,fa)=>((localStorage.getItem('dark_lang')||'en')==='fa'?fa:en);
const esc=v=>e(String(v??''));
const ico=n=>icon(n||'settings');
const list=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
const n=(v,d=0)=>{const x=Number(v);return Number.isFinite(x)?x:d;};
function segment(name,value,items){return `<div class="sv2-segment" data-sv2-segment="${esc(name)}"><input type="hidden" name="${esc(name)}" value="${esc(value)}">${items.map(([v,l])=>`<button type="button" data-sv2-action="segment" data-name="${esc(name)}" data-value="${esc(v)}" class="${String(v)===String(value)?'active':''}">${esc(l)}</button>`).join('')}</div>`;}
function field(label,name,value='',type='text',help='',attrs=''){return `<label class="sv2-field"><span>${esc(label)}</span><input name="${esc(name)}" type="${type}" value="${esc(value)}" ${attrs}>${help?`<small>${esc(help)}</small>`:''}</label>`;}
function toggle(label,name,on,help=''){return `<label class="sv2-toggle"><div><b>${esc(label)}</b>${help?`<small>${esc(help)}</small>`:''}</div><input type="hidden" name="${esc(name)}" value="${on?'true':'false'}"><button type="button" data-sv2-action="toggle" class="${on?'on':''}"><i></i></button></label>`;}
function card(title,sub,body,klass=''){return `<article class="panel sv2-card ${klass}"><div class="sv2-card-head"><div><h3>${esc(title)}</h3>${sub?`<p>${esc(sub)}</p>`:''}</div></div><div class="sv2-card-body">${body}</div></article>`;}
function saveButton(label=L('Save changes','ذخیره تغییرات')){return `<div class="sv2-form-actions"><button class="btn btn-primary" type="submit">${ico('check')}${esc(label)}</button></div>`;}
function tabs(){const items=[['general',L('General','عمومی'),'settings'],['security',L('Security','امنیت'),'shield'],['network',L('Network','شبکه'),'globe'],['tls',L('Domain / TLS','دامنه / TLS'),'lock'],['subscription',L('Subscription','اشتراک'),'link'],['ipguard','IP Guard','shield'],['appearance',L('Appearance','ظاهر'),'eye'],['system',L('System','سیستم'),'cpu']];return `<nav class="sv2-tabs">${items.map(([k,l,ic])=>`<button type="button" data-sv2-action="tab" data-tab="${k}" class="${SV.tab===k?'active':''}">${ico(ic)}<span>${esc(l)}</span></button>`).join('')}</nav>`;}
function applyPrefs(p={}){document.body.dataset.darkDensity=p.density||'comfortable';document.body.classList.toggle('dark-reduced-motion',!!p.reduced_motion);document.title=(p.title||'DARK XRAY')+' | Cyber Control Center';}
async function fetchData(){const req=[['panel','/api/settings/panel'],['runtime','/api/settings/runtime'],['subscription','/api/settings/subscription'],['guard','/api/settings/ipguard'],['runtimeStatus','/api/runtime-config'],['core','/api/core/state']];const out={};await Promise.all(req.map(async([k,u])=>{try{const r=await api(u);out[k]=r.value??r;}catch(ex){out[k]={error:ex.message};}}));SV.data=out;applyPrefs(out.panel);return out;}
function pending(status){const keys=Object.keys(status?.pending||{});if(!keys.length)return `<span class="sv2-state ok">${ico('check')}${L('Applied','اعمال‌شده')}</span>`;return `<span class="sv2-state warn">${ico('alert')}${keys.length} ${L('pending root changes','تغییر در انتظار دسترسی روت')}</span>`;}
function diff(status){const rows=Object.entries(status?.pending||{});if(!rows.length)return `<div class="sv2-empty-inline">${L('No privileged runtime changes are pending.','هیچ تغییر سیستمی در انتظار اعمال نیست.')}</div>`;return `<div class="sv2-diff">${rows.map(([k,v])=>`<div><b>${esc(k)}</b><code>${esc(v.from)} → ${esc(v.to)}</code></div>`).join('')}</div>`;}
function general(d){const p=d.panel;return `<form class="sv2-grid" data-sv2-form="panel-general">${card(L('Panel identity','هویت پنل'),L('Display and operator metadata.','اطلاعات نمایشی و مدیریتی.'),`<div class="sv2-form-grid">${field(L('Panel title','عنوان پنل'),'title',p.title||'DARK XRAY','text','', 'maxlength="80" required')}${field(L('Support URL','لینک پشتیبانی'),'support_url',p.support_url||'','url','', 'dir="ltr" placeholder="https://..."')}</div>`)}${card(L('Regional behavior','تنظیمات منطقه‌ای'),L('Saved server-side; English remains the clean default.','در سرور ذخیره می‌شود؛ انگلیسی پیش‌فرض تمیز پنل است.'),`<div class="sv2-form-grid"><label class="sv2-field"><span>${L('Default language','زبان پیش‌فرض')}</span>${segment('language',p.language||'en',[['en','English'],['fa','فارسی']])}</label>${field(L('Timezone','منطقه زمانی'),'timezone',p.timezone||'UTC','text',L('IANA name, e.g. Asia/Tehran','نام IANA مثل Asia/Tehran'),'dir="ltr"')}${field(L('Rows per page','تعداد ردیف صفحه'),'page_size',p.page_size||50,'number','', 'min="10" max="1000" required')}<label class="sv2-field"><span>${L('Calendar','تقویم')}</span>${segment('datepicker',p.datepicker||'gregorian',[['gregorian','Gregorian'],['jalalian','Jalalian']])}</label></div>`) }${saveButton()}</form>`;}
function security(d){const p=d.panel;return `<form class="sv2-grid" data-sv2-form="security">${card(L('Session policy','سیاست نشست'),L('Changing this affects new logins; current sessions are not extended.','تغییر این مقدار روی ورودهای جدید اثر دارد.'),`<div class="sv2-form-grid">${field(L('Session lifetime (minutes)','عمر نشست (دقیقه)'),'session_max_age_minutes',p.session_max_age_minutes||480,'number','', 'min="60" max="525600" required')}</div>`)}${card(L('Account protection','محافظت حساب'),L('TOTP, password and API keys live in the dedicated account center.','TOTP، رمز و کلیدهای API در مرکز امنیت حساب مدیریت می‌شوند.'),`<div class="sv2-security-summary"><span>${ico('shield')}TOTP: <b>${state.me?.totp_enabled?L('Enabled','فعال'):L('Disabled','غیرفعال')}</b></span><button type="button" class="btn" data-sv2-action="account">${ico('lock')}${L('Open Account & Security','بازکردن حساب و امنیت')}</button></div>`) }${saveButton()}</form>`;}
function network(d){const r=d.runtime,s=d.runtimeStatus;return `<form class="sv2-grid" data-sv2-form="runtime-network">${card(L('Public proxy identity','هویت عمومی پروکسی'),L('Address used when DARK builds customer links.','آدرسی که DARK در لینک مشتری قرار می‌دهد.'),`<div class="sv2-form-grid">${field(L('Public proxy IP / DNS','IP / دامنه عمومی پروکسی'),'public_address',r.public_address||'','text','', 'required dir="ltr"')}${field(L('Panel port','پورت پنل'),'bind_port',r.bind_port||2087,'number',L('Root apply is required after staging.','بعد از ذخیره نیاز به اعمال با روت دارد.'),'min="1024" max="65535" required')}</div>`)}${card(L('Runtime behavior','رفتار Runtime'),L('Safe values are staged in DARK DB first.','ابتدا به‌صورت امن در دیتابیس DARK ذخیره می‌شوند.'),`<div class="sv2-form-grid">${field(L('Poll interval (seconds)','فاصله Poll (ثانیه)'),'poll_seconds',r.poll_seconds||5,'number','', 'min="1" max="3600" required')}<div class="sv2-span-2">${toggle(L('Autostart Xray core','اجرای خودکار Xray Core'),'core_autostart',!!r.core_autostart,L('Starts the child core when DARK service starts.','با شروع سرویس DARK هسته Xray را اجرا می‌کند.'))}</div></div>`)}${card(L('Privileged apply status','وضعیت اعمال سیستمی'),'','<div class="sv2-status-row">'+pending(s)+'</div>'+diff(s)+`<div class="sv2-command"><code>${esc(s.apply_command||'sudo darkxray settings-apply')}</code></div>`,'sv2-span-2')}${saveButton(L('Stage network changes','ذخیره تغییرات شبکه'))}</form>`;}
function tls(d){const r=d.runtime,s=d.runtimeStatus,a=s.actual||{};return `<form class="sv2-grid" data-sv2-form="runtime-tls">${card(L('Panel exposure mode','حالت دسترسی پنل'),L('SSH mode stays loopback-only. Domain mode requires real TLS.','حالت SSH فقط روی لوپ‌بک می‌ماند؛ حالت دامنه TLS واقعی می‌خواهد.'),`<label class="sv2-field sv2-span-2"><span>${L('Access mode','حالت دسترسی')}</span>${segment('access_mode',r.access_mode||'ssh',[['ssh','SSH Tunnel'],['domain_tls','Domain + HTTPS/TLS']])}</label><div class="sv2-form-grid" data-sv2-domain-fields ${r.access_mode==='domain_tls'?'':'hidden'}>${field(L('Panel domain','دامنه پنل'),'domain',r.domain||'','text','', 'dir="ltr" placeholder="panel.example.com"')}${field(L('ACME email','ایمیل ACME'),'acme_email',r.acme_email||'','email','', 'dir="ltr" placeholder="admin@example.com"')}</div>`)}${card(L('Current TLS state','وضعیت فعلی TLS'),'',`<div class="sv2-kv"><div><span>Origin</span><b class="mono">${esc(a.public_origin||'—')}</b></div><div><span>TLS</span><b>${a.tls_enabled?L('Enabled','فعال'):L('Disabled','غیرفعال')}</b></div><div><span>${L('Certificate','گواهی')}</span><b class="mono">${esc(a.tls_certificate||'—')}</b></div><div><span>${L('Secure cookie','کوکی امن')}</span><b>${a.secure_cookie?L('Yes','بله'):L('No','خیر')}</b></div></div>`)}${card(L('Apply boundary','مرز اعمال'),L('Root-owned listener changes are intentionally not performed by the web process.','تغییرات Listener که متعلق به root هستند عمداً توسط Web process انجام نمی‌شوند.'),diff(s)+`<div class="notice warning">${L('After staging, run the command below from SSH. Domain mode will use Certbot and may restart DARK/Xray.','بعد از ذخیره، دستور زیر را در SSH اجرا کن. حالت دامنه از Certbot استفاده می‌کند و ممکن است DARK/Xray ری‌استارت شود.')}</div><div class="sv2-command"><code>${esc(s.apply_command||'sudo darkxray settings-apply')}</code></div>`,'sv2-span-2')}${saveButton(L('Stage domain / TLS changes','ذخیره تغییرات دامنه / TLS'))}</form>`;}
function subscription(d){const s=d.subscription;return `<form class="sv2-grid" data-sv2-form="subscription">${card(L('Subscription service','سرویس اشتراک'),L('Only formats actually supported by DARK are exposed.','فقط فرمت‌هایی که واقعاً توسط DARK پشتیبانی می‌شوند نمایش داده می‌شوند.'),`<div class="sv2-span-2">${toggle(L('Enable subscription endpoint','فعال‌سازی لینک اشتراک'),'enabled',s.enabled!==false)}</div><div class="sv2-form-grid"><label class="sv2-field"><span>${L('Default format','فرمت پیش‌فرض')}</span>${segment('default_format',s.default_format||'base64',[['base64','Base64'],['raw','Raw']])}</label>${field(L('Profile update interval (hours)','بازه آپدیت پروفایل (ساعت)'),'profile_update_interval_hours',s.profile_update_interval_hours||6,'number','', 'min="1" max="168" required')}</div>`)}${card(L('Link naming','نام‌گذاری لینک‌ها'),L('Variables: {remark}, {email}, {protocol}.','متغیرها: {remark}، {email}، {protocol}.'),`<div class="sv2-form-grid">${field(L('Remark template','قالب نام'),'remark_template',s.remark_template||'{remark} | {email}','text','', 'maxlength="200"')}${field(L('Support URL','لینک پشتیبانی'),'support_url',s.support_url||'','url','', 'dir="ltr"')}</div>`)}${saveButton()}</form>`;}
function ipguard(d){const g=d.guard,st=d.runtimeStatus;return `<form class="sv2-grid" data-sv2-form="ipguard">${card('DARK IP Guard',L('Observe first; enforce only after real source-IP verification.','ابتدا Observe؛ Enforce فقط بعد از تأیید IP واقعی.'),`<div class="sv2-form-grid"><label class="sv2-field"><span>${L('Mode','حالت')}</span>${segment('mode',g.mode||'observe',[['observe','Observe'],['enforce','Enforce']])}</label>${field(L('Activity window (seconds)','پنجره فعالیت (ثانیه)'),'window_seconds',g.window_seconds||120,'number','', 'min="10" max="3600" required')}${field(L('Ban duration (seconds)','مدت مسدودی (ثانیه)'),'ban_seconds',g.ban_seconds||1800,'number','', 'min="10" max="86400" required')}${field(L('Exempt IP / CIDR list','IP / CIDRهای معاف'),'exempt_ips',(g.exempt_ips||[]).join(', '),'text','Comma separated','dir="ltr"')}</div>`)}${card(L('Source verification','تأیید مبدأ'),'','<div class="sv2-kv"><div><span>'+L('Direct source verified','مبدأ مستقیم تأیید شده')+'</span><b>'+(st.actual?.direct_source_verified?L('Yes','بله'):L('No','خیر'))+'</b></div><div><span>'+L('Guard socket','سوکت Guard')+'</span><b class="mono">'+esc(st.actual?.guard_socket||'—')+'</b></div></div><div class="notice warning">'+L('If a tunnel hides the real client source IP, keep Observe mode.','اگر تانل IP واقعی مشتری را مخفی می‌کند، حالت Observe را نگه دار.')+'</div>')}${saveButton()}</form>`;}
function appearance(d){const p=d.panel;return `<form class="sv2-grid" data-sv2-form="appearance">${card(L('Cyber appearance','ظاهر سایبری'),L('DARK keeps a focused dark theme; only useful density/motion controls are exposed.','DARK تم تاریک متمرکز را حفظ می‌کند و فقط کنترل‌های کاربردی نمایش داده می‌شوند.'),`<div class="sv2-form-grid"><label class="sv2-field"><span>${L('Density','تراکم')}</span>${segment('density',p.density||'comfortable',[['comfortable',L('Comfortable','راحت')],['compact',L('Compact','فشرده')]])}</label><div class="sv2-span-2">${toggle(L('Reduce motion','کاهش انیمیشن'),'reduced_motion',!!p.reduced_motion,L('Disables non-essential cyber animations.','انیمیشن‌های غیرضروری سایبری را کم می‌کند.'))}</div></div>`)}${saveButton()}</form>`;}
function system(d){const c=d.core,s=d.runtimeStatus,a=s.actual||{};return `<div class="sv2-grid">${card(L('DARK service','سرویس DARK'),'','<div class="sv2-kv"><div><span>'+L('Xray state','وضعیت Xray')+'</span><b>'+esc(c.state||'—')+'</b></div><div><span>PID</span><b class="mono">'+esc(c.pid||'—')+'</b></div><div><span>'+L('Core version','نسخه هسته')+'</span><b class="mono">'+esc(c.version||'—')+'</b></div><div><span>'+L('Dirty config','تنظیمات اعمال‌نشده')+'</span><b>'+(c.dirty?L('Yes','بله'):L('No','خیر'))+'</b></div></div><div class="sv2-inline-actions"><button class="btn" type="button" data-sv2-action="core-validate">'+ico('check')+L('Validate Xray','اعتبارسنجی Xray')+'</button><button class="btn danger" type="button" data-sv2-action="core-restart">'+ico('refresh')+L('Restart / Apply','ری‌استارت / اعمال')+'</button></div>')}${card(L('Root-owned runtime','Runtime تحت مالکیت root'),'','<div class="sv2-kv"><div><span>Bind</span><b class="mono">'+esc(a.bind_host||'—')+':'+esc(a.bind_port||'—')+'</b></div><div><span>Public origin</span><b class="mono">'+esc(a.public_origin||'—')+'</b></div><div><span>Xray API</span><b class="mono">'+esc(a.xray_api_port||'—')+'</b></div><div><span>'+L('Pending changes','تغییرات در انتظار')+'</span><b>'+Object.keys(s.pending||{}).length+'</b></div></div>'+diff(s)+'<div class="sv2-command"><code>'+esc(s.apply_command||'sudo darkxray settings-apply')+'</code></div>')}</div>`;}
function body(d){if(d.panel?.error||d.runtime?.error)return `<div class="notice error">${esc(d.panel?.error||d.runtime?.error)}</div>`;return {general,security,network,tls,subscription,ipguard,appearance,system}[SV.tab](d);}
async function page(){const d=await fetchData();return heading(L('Settings','تنظیمات'),L('One control center for DARK UI, subscription, network staging, TLS and system state.','یک مرکز کنترل برای UI، اشتراک، شبکه، TLS و وضعیت سیستم.'))+`<div class="settings-v2">${tabs()}<section class="sv2-content">${body(d)}</section></div>`;}
enginePage=async function(){if(state.page==='settings')return page();return baseEnginePage();};
function formValue(form,name){return form.elements[name]?.value??'';}
async function savePanel(form,kind){const old={...(SV.data.panel||{})};if(kind==='panel-general'){old.title=formValue(form,'title').trim();old.support_url=formValue(form,'support_url').trim();old.language=formValue(form,'language');old.timezone=formValue(form,'timezone').trim();old.datepicker=formValue(form,'datepicker');localStorage.setItem('dark_lang',old.language);}else if(kind==='security'){old.session_max_age_minutes=n(formValue(form,'session_max_age_minutes'),480);}else{old.density=formValue(form,'density');old.reduced_motion=formValue(form,'reduced_motion')==='true';document.body.dataset.darkDensity=old.density;document.body.classList.toggle('dark-reduced-motion',old.reduced_motion);}await api('/api/settings/panel','PUT',{value:old});if(state.me)state.me.ui={...old};applyPrefs(old);toast(L('Settings saved.','تنظیمات ذخیره شد.'));}
async function saveRuntime(form,kind){const old={...(SV.data.runtime||{})};if(kind==='runtime-network'){old.public_address=formValue(form,'public_address').trim();old.bind_port=n(formValue(form,'bind_port'));old.poll_seconds=n(formValue(form,'poll_seconds'));old.core_autostart=formValue(form,'core_autostart')==='true';}else{old.access_mode=formValue(form,'access_mode');if(old.access_mode==='ssh'){old.domain='';old.acme_email='';}else{old.domain=formValue(form,'domain').trim();old.acme_email=formValue(form,'acme_email').trim();}}await api('/api/settings/runtime','PUT',{value:old});toast(L('Privileged changes staged. Apply from SSH with darkxray settings-apply.','تغییرات سیستمی ذخیره شد؛ از SSH با darkxray settings-apply اعمال کن.'));}
async function saveSubscription(form){const s={...(SV.data.subscription||{})};s.enabled=formValue(form,'enabled')==='true';s.default_format=formValue(form,'default_format');s.profile_update_interval_hours=n(formValue(form,'profile_update_interval_hours'),6);s.remark_template=formValue(form,'remark_template');s.support_url=formValue(form,'support_url').trim();await api('/api/settings/subscription','PUT',{value:s});toast(L('Subscription settings saved.','تنظیمات اشتراک ذخیره شد.'));}
async function saveGuard(form){const g={mode:formValue(form,'mode'),window_seconds:n(formValue(form,'window_seconds')),ban_seconds:n(formValue(form,'ban_seconds')),exempt_ips:list(formValue(form,'exempt_ips'))};await api('/api/settings/ipguard','PUT',{value:g});toast(L('IP Guard settings saved.','تنظیمات IP Guard ذخیره شد.'));}
document.addEventListener('click',async ev=>{const el=ev.target.closest('[data-sv2-action]');if(!el)return;const act=el.dataset.sv2Action;try{if(act==='tab'){SV.tab=el.dataset.tab;await renderPage();return;}if(act==='segment'){const box=el.closest('[data-sv2-segment]');box.querySelector('input[type=hidden]').value=el.dataset.value;box.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===el));if(el.dataset.name==='access_mode'){const f=el.closest('form');f.querySelector('[data-sv2-domain-fields]').hidden=el.dataset.value!=='domain_tls';}return;}if(act==='toggle'){el.classList.toggle('on');el.parentElement.querySelector('input[type=hidden]').value=el.classList.contains('on')?'true':'false';return;}if(act==='account'){await go('account');return;}if(act==='core-validate'){await api('/api/core/validate','POST',{});toast(L('Xray validation passed.','اعتبارسنجی Xray موفق بود.'));return;}if(act==='core-restart'){if(confirm(L('Restart DARK Xray now? Active proxy sessions may disconnect.','Xray ری‌استارت شود؟ اتصال‌های فعال ممکن است قطع شوند.'))){await api('/api/core/restart','POST',{});toast(L('Xray restarted.','Xray ری‌استارت شد.'));await refresh();}return;}}catch(ex){toast(ex.message,true);}});
document.addEventListener('submit',async ev=>{const form=ev.target.closest('[data-sv2-form]');if(!form)return;ev.preventDefault();const kind=form.dataset.sv2Form,b=form.querySelector('button[type=submit]');if(b)b.disabled=true;try{if(kind==='panel-general'||kind==='security'||kind==='appearance')await savePanel(form,kind);else if(kind.startsWith('runtime-'))await saveRuntime(form,kind);else if(kind==='subscription')await saveSubscription(form);else if(kind==='ipguard')await saveGuard(form);SV.data=null;await renderPage();}catch(ex){toast(ex.message,true);}finally{if(b?.isConnected)b.disabled=false;}});
})();
