(()=>{const d=window.__DARK_SUB__||{},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],fmt=n=>{n=Number(n||0);if(n<1024)return n+' B';const u=['KB','MB','GB','TB'];let i=-1;do{n/=1024;i++}while(n>=1024&&i<u.length-1);return n.toFixed(n>=100?0:n>=10?1:2)+' '+u[i]},toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)},copy=async value=>{try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(value);else{const x=document.createElement('textarea');x.value=value;x.style.position='fixed';x.style.opacity='0';document.body.appendChild(x);x.select();document.execCommand('copy');x.remove()}return true}catch{return false}};
const appIcons=window.__DARK_APP_ICONS__||{};$$('[data-app-icon]').forEach(el=>{const src=appIcons[el.dataset.appIcon];if(!src)return;const img=document.createElement('img');img.alt='';img.decoding='async';img.loading='eager';img.src=src;el.appendChild(img)});
$('#profileTitle').textContent=d.title||'DARK XRAY';$('#clientId').textContent=d.client||'—';$('#subUrl').textContent=d.url||location.href.split('?')[0];const used=Number(d.used||0),total=Number(d.total||0),rem=total>0?Math.max(0,total-used):0,pct=total>0?Math.min(100,Math.max(0,used/total*100)):0;$('#usedTraffic').textContent=fmt(used);$('#remainTraffic').textContent=total>0?fmt(rem):'UNLIMITED';$('#quotaHint').textContent=total>0?fmt(total)+' total quota':'no traffic cap';$('#quotaPercent').textContent=total>0?pct.toFixed(1)+'%':'∞';$('#quotaBar').style.width=(total>0?pct:100)+'%';if(!total)$('#quotaBar').style.opacity='.4';
function renderExpiry(){
  const ex=Number(d.expiry||0);
  if(ex>0){
    const dt=new Date(ex*1000),left=dt.getTime()-Date.now(),pad=n=>String(n).padStart(2,'0');
    $('#expiry').textContent=dt.getFullYear()+'-'+pad(dt.getMonth()+1)+'-'+pad(dt.getDate());
    const remaining=left<=0?'EXPIRED':left<86400000?Math.ceil(left/3600000)+' HOURS LEFT':Math.ceil(left/86400000)+' DAYS LEFT';
    const clock=new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(dt);
    $('#expiryHint').textContent=clock+' · '+remaining;
  }else if(d.activation_pending){
    $('#expiry').textContent=Number(d.duration_days||0)>0?Number(d.duration_days)+' DAYS':'WAITING';
    $('#expiryHint').textContent='STARTS ON FIRST CONNECTION · EXPIRY NOT SET YET';
  }else{
    $('#expiry').textContent='UNLIMITED';$('#expiryHint').textContent='no expiry date';
  }
}
renderExpiry();setInterval(renderExpiry,60000);
$('#updateEvery').textContent='AUTO UPDATE / '+(d.update_hours||6)+'H';if(d.announce){$('#announceWrap').hidden=false;$('#announce').textContent=d.announce}
const base=d.url||location.href.split('?')[0],title=d.title||'DARK XRAY',name=encodeURIComponent(title),enc=encodeURIComponent(base);$('#rawBtn').href=base+'?format=raw';$('#clashBtn').href=base+'?format=clash';$('#jsonBtn').href=base+'?format=json';$('#copyBtn').onclick=async()=>toast(await copy(base)?'SUBSCRIPTION COPIED':'COPY FAILED');$('#qrBtn').onclick=()=>{const w=$('#qrWrap');w.hidden=!w.hidden;if(!w.hidden&&!$('#qr').children.length){try{const q=qrcode(0,'L');q.addData(base);q.make();$('#qr').innerHTML=q.createSvgTag()}catch{toast('QR UNAVAILABLE')}}};
const ua=navigator.userAgent||'',platform=/Android/i.test(ua)?'android':/iPhone|iPad|iPod/i.test(ua)?'ios':/Windows/i.test(ua)?'windows':'android',labels={android:'ANDROID DETECTED',ios:'IPHONE DETECTED',windows:'WINDOWS DETECTED'};function showPlatform(p){$$('[data-platform-tab]').forEach(b=>b.classList.toggle('active',b.dataset.platformTab===p));$$('[data-platform-panel]').forEach(x=>x.classList.toggle('active',x.dataset.platformPanel===p));$('#detectedPlatform').textContent=labels[p]||p.toUpperCase()}$$('[data-platform-tab]').forEach(b=>b.onclick=()=>showPlatform(b.dataset.platformTab));showPlatform(platform);
const schemes={v2box:()=>`v2box://install-sub?url=${enc}&name=${name}`,happ:()=>`happ://add/${base}`,streisand:()=>`streisand://import/${base}#${name}`,hiddify:()=>`hiddify://import/${base}#${name}`};$$('.app-copy').forEach(b=>b.onclick=async()=>toast(await copy(base)?'SUBSCRIPTION COPIED':'COPY FAILED'));$$('.app-import').forEach(b=>b.onclick=async()=>{const app=b.dataset.app,card=b.closest('.app-card');card?.classList.add('launching');setTimeout(()=>card?.classList.remove('launching'),850);if(app==='v2rayn'){const ok=await copy(base);$('#appHelp').innerHTML=ok?'<strong>v2rayN:</strong> link copied — open Subscriptions and add from clipboard.':'Copy failed — use the COPY button above.';toast(ok?'COPIED FOR V2RAYN':'COPY FAILED');return}const make=schemes[app];if(!make)return;await copy(base);$('#appHelp').innerHTML='<strong>'+b.closest('.app-card').querySelector('.app-info b').textContent+':</strong> opening app… subscription is also copied as fallback.';location.href=make();setTimeout(()=>toast('LINK ALSO COPIED'),500)});
if(d.suspended){$('#serviceState').textContent='SUSPENDED';$('.status i').style.background='var(--danger)'}})();
