/* DARK XRAY Update Center — owner-only broker-backed updates. */
(function(){
'use strict';
if(typeof dashboard!=='function'||typeof load!=='function'||typeof renderPage!=='function'||typeof runAction!=='function')return;
var baseDashboardUpdate=dashboard,baseLoadUpdate=load,baseRenderPageUpdate=renderPage,baseRunActionUpdate=runAction;
enginePages.update=['آپدیت پنل'];
state.updateCenter=state.updateCenter||{channel:'main',status:null,error:''};
function UL(en,fa){return (localStorage.getItem('dark_lang')||'en')==='fa'?fa:en;}
function UE(v){return e(String(v==null?'':v));}
function USha(v){return v?String(v).slice(0,12):'—';}
function UPhase(v){var map={idle:UL('Idle','آماده'),resolve:UL('Resolve candidate','یافتن نسخه'),current_health:UL('Current health','سلامت فعلی'),validate_source:UL('Validate source','اعتبارسنجی سورس'),rollback_preflight:UL('Rollback preflight','آماده‌سازی بازگشت'),dependencies:UL('Dependency preflight','بررسی وابستگی‌ها'),snapshot_source:UL('Source snapshot','بکاپ سورس'),snapshot_database:UL('Database snapshot','بکاپ دیتابیس'),apply_source:UL('Apply source','اعمال سورس'),restart:UL('Restart + health','ری‌استارت و سلامت'),rollback:UL('Automatic rollback','بازگشت خودکار'),rollback_failed:UL('Rollback failed','خطای بازگشت'),complete:UL('Complete','تکمیل'),failed:UL('Failed','ناموفق'),preflight:UL('Preflight','پیش‌بررسی'),queued:UL('Queued','در صف')};return map[v]||v||'—';}
load=async function(){
 await baseLoadUpdate();
 if(!state.me||!isOwner()){state.updateCenter.status=null;state.updateCenter.error='';return;}
 if(state.page!=='dashboard'&&state.page!=='update')return;
 try{state.updateCenter.status=await api('/api/update/status');state.updateCenter.error='';}
 catch(ex){state.updateCenter.status=null;state.updateCenter.error=ex.message;}
};
function UCurrent(st){var c=st&&st.current||{};return '<article class="up-card up-current"><div class="up-card-label">DARK XRAY / CURRENT</div><div class="up-version"><b>'+UE(c.version||state.me&&state.me.version||'—')+'</b><span>'+UE(USha(c.commit))+'</span></div><div class="up-mini-grid"><div><span>'+UL('Broker','بروکر')+'</span><b class="'+(st&&st.broker_ready?'good':'bad')+'">'+(st&&st.broker_ready?UL('READY','آماده'):UL('OFFLINE','قطع'))+'</b></div><div><span>'+UL('Last source','آخرین منبع')+'</span><b>'+UE(c.ref||'—')+'</b></div></div></article>';}
function UChannel(key,title,sub,active,ic){return '<button class="up-channel '+(active?'active':'')+'" data-act="upchannel" data-channel="'+key+'"><span class="up-channel-icon">'+icon(ic)+'</span><span><b>'+title+'</b><small>'+sub+'</small></span><i></i></button>';}
function UCandidate(st){var c=st&&st.candidate;if(!c)return '<article class="up-card up-empty"><div>'+icon('refresh')+'</div><b>'+UL('Check for an update','برای آپدیت بررسی کن')+'</b><small>'+UL('DARK resolves the selected channel to an immutable commit before installation.','DARK کانال انتخابی را قبل از نصب به Commit ثابت تبدیل می‌کند.')+'</small></article>';var ci=c.ci||{},pre=st.preflight||{},ready=!!c.ready;var checks=[['DB',pre.database],['SERVICE',pre.panel_service],['DISK',pre.disk],['GIT',pre.git],['CI',ci.verified]];var html='<article class="up-card up-candidate '+(ready?'ready':'blocked')+'"><header><div><span>'+UL('CANDIDATE','نسخه پیشنهادی')+'</span><h2>'+UE(c.version||'—')+'</h2></div><span class="up-ci '+(ci.verified?'ok':'bad')+'">'+(ci.verified?'CI VERIFIED':'CI '+String(ci.state||'UNKNOWN').toUpperCase())+'</span></header><div class="up-commit"><span>'+UL('Immutable commit','Commit ثابت')+'</span><code>'+UE(c.commit||'—')+'</code></div><div class="up-checks">';checks.forEach(function(x){html+='<div class="'+(x[1]?'ok':'bad')+'"><i></i><span>'+x[0]+'</span><b>'+(x[1]?'PASS':'FAIL')+'</b></div>';});html+='</div>';((st&&st.warnings)||[]).forEach(function(w){html+='<div class="up-warning">'+icon('alert')+UE(w)+'</div>';});html+='<div class="up-candidate-actions">';if(c.update_available)html+='<button class="btn btn-primary" data-act="upstart" data-commit="'+UE(c.commit)+'" '+(ready?'':'disabled')+'>'+icon('refresh')+UL('Install verified update','نصب آپدیت تاییدشده')+'</button>';else html+='<span class="up-latest">'+icon('check')+UL('Already on this build','همین نسخه نصب است')+'</span>';return html+'</div></article>';}
function UProgress(st){if(!st||['queued','running','restarting','rolling_back','success','failed','rolled_back'].indexOf(st.state)<0)return '';var pct=Math.max(0,Math.min(100,Number(st.percent||0))),steps=['resolve','current_health','validate_source','rollback_preflight','dependencies','snapshot_source','snapshot_database','apply_source','restart','complete'],cur=steps.indexOf(st.phase),klass=['success','ready'].indexOf(st.state)>=0?'ok':['failed','rolled_back'].indexOf(st.state)>=0?'bad':'live';var html='<article class="up-card up-progress '+klass+'"><header><div><span>'+UL('UPDATE JOB','عملیات آپدیت')+'</span><h3>'+UE(UPhase(st.phase))+'</h3></div><b>'+pct+'%</b></header><div class="up-progress-track"><i style="width:'+pct+'%"></i></div><p>'+UE(st.message||'')+'</p><div class="up-timeline">';steps.forEach(function(x,i){html+='<div class="'+(i<cur?'done':i===cur?'active':'')+'"><i></i><span>'+UE(UPhase(x))+'</span></div>';});html+='</div>';if(st.state==='rolled_back')html+='<div class="up-warning">'+icon('alert')+UL('The update failed, but DARK restored the previous source and database automatically.','آپدیت ناموفق بود ولی DARK سورس و دیتابیس قبلی را خودکار برگرداند.')+'</div>';return html+'</article>';}
function UChangelog(st){var c=st&&st.candidate;if(!c||!c.notes)return '';return '<article class="up-card up-changelog"><header><span>'+UL('WHAT CHANGED','چه چیزهایی تغییر کرده')+'</span><code>'+UE(c.ref||c.channel||'')+'</code></header><pre>'+UE(c.notes)+'</pre></article>';}
function ULog(st){var lines=st&&st.log_tail||[];if(!lines.length)return '';return '<details class="up-card up-log"><summary>'+icon('terminal')+'<span>'+UL('Update log','لاگ آپدیت')+'</span><b>'+lines.length+'</b></summary><pre>'+UE(lines.join('\n'))+'</pre></details>';}
function UUnavailable(msg){return heading(UL('Update Center','مرکز آپدیت'),UL('Rollback-safe DARK XRAY updates without SSH after the broker is installed.','آپدیت امن DARK XRAY بدون SSH بعد از نصب Broker.'))+'<div class="update-center"><article class="up-card up-unavailable">'+icon('alert')+'<div><b>'+UL('Update Broker is not available','Update Broker در دسترس نیست')+'</b><p>'+UE(msg||'')+'</p><small>'+UL('This server needs one CLI upgrade to the first broker-enabled build. After that, future updates can be installed here.','این سرور فقط یک بار باید با CLI به اولین نسخه دارای Broker آپدیت شود؛ بعد از آن آپدیت‌های بعدی از همین صفحه انجام می‌شوند.')+'</small></div></article></div>';}
function UWorkspace(st,embedded){
 var ch=state.updateCenter.channel,run=['queued','running','restarting','rolling_back','checking'].indexOf(st&&st.state)>=0;
 if(run)setTimeout(function(){if(state.page==='update'||state.page==='dashboard')UPoll();},1200);
 var h='<div class="update-center '+(embedded?'up-embedded':'')+'">';
 if(embedded)h+='<div class="up-dashboard-title"><div><span class="eyebrow">03 / UPDATE & ROLLBACK</span><h2>'+UL('Update Center','مرکز آپدیت')+'</h2><p>'+UL('Verified source · CI gate · snapshots · automatic rollback · live progress','سورس تاییدشده · گیت CI · Snapshot · Rollback خودکار · پیشرفت زنده')+'</p></div><button class="btn" data-act="uprefresh">'+icon('refresh')+UL('Refresh','بروزرسانی')+'</button></div>';
 h+=UCurrent(st)+'<section class="up-select"><div class="up-section-title"><span>01</span><div><b>'+UL('Choose update channel','کانال آپدیت را انتخاب کن')+'</b><small>'+UL('Latest Verified uses the newest tested main commit.','Latest Verified جدیدترین Commit تست‌شده main را استفاده می‌کند.')+'</small></div></div><div class="up-channels">';
 h+=UChannel('main',UL('Latest Verified','آخرین نسخه تاییدشده'),UL('Newest main commit · CI must be green','جدیدترین main · فقط با CI سبز'),ch==='main','activity');
 h+=UChannel('stable',UL('Stable','پایدار'),UL('Newest stable release tag','آخرین Tag پایدار'),ch==='stable','shield');
 h+=UChannel('rc',UL('Release Candidate','نسخه RC'),UL('Newest RC release tag','آخرین Tag آزمایشی'),ch==='rc','server');
 h+=UChannel('exact',UL('Exact Ref','Ref دقیق'),UL('Tag / branch / commit for advanced use','Tag / Branch / Commit برای حالت پیشرفته'),ch==='exact','terminal');
 h+='</div><div class="up-checkbar">'+(ch==='exact'?'<input id="up-exact-ref" class="field-input" maxlength="128" placeholder="v0.9.0-rc7 / commit / branch" dir="ltr">':'')+'<button class="btn btn-primary" data-act="upcheck">'+icon('search')+UL('Check update','بررسی آپدیت')+'</button></div></section>'+UCandidate(st)+UProgress(st)+UChangelog(st)+ULog(st)+'</div>';
 return h;
}
function UDashboard(){
 if(!isOwner())return '';
 var open='<button class="btn" data-act="upopen">'+icon('settings')+UL('Open Update Center','بازکردن مرکز آپدیت')+'</button>';
 var refresh='<button class="btn" data-act="uprefresh">'+icon('refresh')+UL('Refresh','بروزرسانی')+'</button>';
 if(state.updateCenter.error)return '<section class="up-dashboard-shell up-dashboard-compact"><div class="update-center up-embedded up-dashboard-compact-inner"><div class="up-dashboard-title"><div><span class="eyebrow">03 / UPDATE & ROLLBACK</span><h2>'+UL('Update Center','مرکز آپدیت')+'</h2><p>'+UL('Compact status on the dashboard; full controls open separately.','وضعیت فشرده در داشبورد؛ کنترل کامل جدا باز می‌شود.')+'</p></div><div class="up-dashboard-actions">'+refresh+open+'</div></div><article class="up-card up-unavailable up-unavailable-compact">'+icon('alert')+'<div><b>'+UL('Update Broker is not available','Update Broker در دسترس نیست')+'</b><p>'+UE(state.updateCenter.error)+'</p></div></article></div></section>';
 var st=state.updateCenter.status;
 if(!st)return '<section class="up-dashboard-shell up-dashboard-compact"><div class="update-center up-embedded up-dashboard-compact-inner"><div class="up-dashboard-title"><div><span class="eyebrow">03 / UPDATE & ROLLBACK</span><h2>'+UL('Update Center','مرکز آپدیت')+'</h2></div><div class="up-dashboard-actions">'+refresh+open+'</div></div><article class="up-card up-empty up-empty-compact"><div>'+icon('refresh')+'</div><b>'+UL('Loading update status…','در حال دریافت وضعیت آپدیت…')+'</b></article></div></section>';
 var current=st.current||{},cand=st.candidate||{},run=['queued','running','restarting','rolling_back','checking'].indexOf(st.state)>=0;
 if(run)setTimeout(function(){if(state.page==='dashboard')UPoll();},1200);
 var candidate=cand.version||UL('Not checked','بررسی نشده');
 var candidateClass=cand.update_available?(cand.ready?'good':'warn'):'';
 var job=run?'<div class="up-dashboard-job"><div><span>'+UE(UPhase(st.phase))+'</span><b>'+Math.max(0,Math.min(100,Number(st.percent||0)))+'%</b></div><i><em style="width:'+Math.max(0,Math.min(100,Number(st.percent||0)))+'%"></em></i></div>':'';
 var install=cand.update_available?'<button class="btn btn-primary" data-act="upstart" data-commit="'+UE(cand.commit||'')+'" '+(cand.ready?'':'disabled')+'>'+icon('refresh')+UL('Install verified','نصب تاییدشده')+'</button>':'';
 return '<section class="up-dashboard-shell up-dashboard-compact"><div class="update-center up-embedded up-dashboard-compact-inner"><div class="up-dashboard-title"><div><span class="eyebrow">03 / UPDATE & ROLLBACK</span><h2>'+UL('Update Center','مرکز آپدیت')+'</h2><p>'+UL('Verified updates stay available without stretching the overview.','آپدیت تاییدشده بدون کش‌دادن نمای کلی در دسترس می‌ماند.')+'</p></div><div class="up-dashboard-actions">'+refresh+open+'</div></div><article class="up-card up-dashboard-summary"><div class="up-dashboard-metrics"><div><span>'+UL('Current','فعلی')+'</span><b>'+UE(current.version||state.me&&state.me.version||'—')+'</b></div><div><span>'+UL('Broker','بروکر')+'</span><b class="'+(st.broker_ready?'good':'bad')+'">'+(st.broker_ready?UL('READY','آماده'):UL('OFFLINE','قطع'))+'</b></div><div><span>'+UL('State','وضعیت')+'</span><b>'+UE(UPhase(st.phase||st.state||'idle'))+'</b></div><div><span>'+UL('Candidate','پیشنهادی')+'</span><b class="'+candidateClass+'">'+UE(candidate)+'</b></div></div>'+job+'<div class="up-dashboard-actions up-dashboard-actions-bottom"><button class="btn" data-act="upquickcheck">'+icon('search')+UL('Check Latest Verified','بررسی آخرین تاییدشده')+'</button>'+install+'</div></article></div></section>';
}
dashboard=function(){var base=baseDashboardUpdate(),slot='<div id="dark-update-center-slot"></div>';if(!isOwner())return base.replace(slot,'');var update=UDashboard();return base.includes(slot)?base.replace(slot,update):base+update;};
async function UPage(){
 var st;try{st=await api('/api/update/status');state.updateCenter.status=st;state.updateCenter.error='';}catch(ex){state.updateCenter.error=ex.message;return UUnavailable(ex.message);}
 return heading(UL('Update Center','مرکز آپدیت'),UL('Verified source · CI gate · snapshots · automatic rollback · live progress','سورس تاییدشده · گیت CI · Snapshot · Rollback خودکار · پیشرفت زنده'),'<button class="btn" data-act="uprefresh">'+icon('refresh')+UL('Refresh','بروزرسانی')+'</button>')+UWorkspace(st,false);
}
async function UPoll(){if(state.page!=='update'&&state.page!=='dashboard')return;try{var st=await api('/api/update/status');state.updateCenter.status=st;if(['queued','running','restarting','rolling_back','checking'].indexOf(st.state)>=0){await renderPage();return;}await load();await renderPage();}catch(ex){var p=document.querySelector('.up-progress p');if(p)p.textContent=UL('Panel is restarting… reconnecting automatically.','پنل در حال ری‌استارت است… اتصال خودکار برقرار می‌شود.');setTimeout(UPoll,1800);}}
renderPage=async function(){if(state.page==='update'){var html;try{html=await UPage();}catch(ex){html=UUnavailable(ex.message);}var c=document.querySelector('#content');if(c)c.innerHTML=html+'<footer><span>DARK UPDATE BROKER · ROLLBACK SAFE</span><span class="mono">'+UE(state.me&&state.me.version||'DARK')+'</span></footer>';return;}return baseRenderPageUpdate();};
runAction=async function(act,el){if(act==='upopen'){await go('update');return;}if(act==='upquickcheck'){try{state.updateCenter.channel='main';state.updateCenter.status=await api('/api/update/check','POST',{channel:'main',ref:''});toast(UL('Latest Verified checked.','آخرین نسخه تاییدشده بررسی شد.'));await renderPage();}catch(ex){toast(ex.message,true);}return;}if(act==='upchannel'){state.updateCenter.channel=el.dataset.channel;var st=state.updateCenter.status;if(st&&['queued','running','restarting','rolling_back'].indexOf(st.state)<0){delete st.candidate;delete st.preflight;st.warnings=[];}return renderPage();}if(act==='uprefresh')return renderPage();if(act==='upcheck'){var ch=state.updateCenter.channel,ref=ch==='exact'?(document.querySelector('#up-exact-ref')&&document.querySelector('#up-exact-ref').value||'').trim():'';if(ch==='exact'&&!ref)return toast(UL('Enter a Tag / Branch / Commit first.','اول Tag / Branch / Commit را وارد کن.'),true);try{state.updateCenter.status=await api('/api/update/check','POST',{channel:ch,ref:ref});toast(UL('Update candidate checked.','نسخه آپدیت بررسی شد.'));await renderPage();}catch(ex){toast(ex.message,true);}return;}if(act==='upstart'){var commit=el.dataset.commit;if(!commit)return;var cand=state.updateCenter.status&&state.updateCenter.status.candidate||{};var body='<div class="up-confirm"><div class="up-confirm-shield">'+icon('shield')+'</div><h3>'+UE(cand.version||'DARK')+'</h3><code>'+UE(commit)+'</code><p>'+UL('DARK will create rollback snapshots, apply the verified commit, restart the panel, and automatically restore the previous source + database if health checks fail.','DARK ابتدا Snapshot بازگشت می‌سازد، Commit تاییدشده را اعمال می‌کند، پنل را ری‌استارت می‌کند و اگر Health Check شکست بخورد سورس و دیتابیس قبلی را خودکار برمی‌گرداند.')+'</p><label>'+UL('Type UPDATE to continue','برای ادامه UPDATE را تایپ کن')+'<input class="field-input" name="confirm" autocomplete="off"></label></div>';dialog(UL('Install DARK update','نصب آپدیت DARK'),body,async function(f){if(f.get('confirm')!=='UPDATE')throw Error(UL('Confirmation must be exactly UPDATE.','تایید باید دقیقاً UPDATE باشد.'));state.updateCenter.status=await api('/api/update/start','POST',{commit:commit});closeDialog();await renderPage();setTimeout(UPoll,800);},UL('Start verified update','شروع آپدیت تاییدشده'));return;}return baseRunActionUpdate(act,el);};
})();